// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/terminal/v1/terminal_output.proto

/* eslint-disable */
import { Error } from "../../common/v1/error.js";
import {
  TerminalJsonMessage,
  TerminalSession,
  TerminalStatus,
  terminalStatusFromJSON,
  terminalStatusToJSON,
} from "./terminal.js";

export const protobufPackage = "boxteam.terminal.v1";

export interface TerminalOutputChunk {
  sequence: number;
  data: string;
}

export interface TerminalStateChanged {
  status: TerminalStatus;
  sequence: number;
}

export interface TerminalCompleted {
  exit_code: number;
  signal?: string | undefined;
}

export interface TerminalServerMessage {
  payload:
    | { $case: "attached"; attached: TerminalSession }
    | { $case: "detached"; detached: TerminalSession }
    | { $case: "output"; output: TerminalOutputChunk }
    | { $case: "state_changed"; state_changed: TerminalStateChanged }
    | { $case: "completed"; completed: TerminalCompleted }
    | { $case: "error"; error: Error }
    | { $case: "json"; json: TerminalJsonMessage }
    | undefined;
}

function createBaseTerminalOutputChunk(): TerminalOutputChunk {
  return { sequence: 0, data: "" };
}

export const TerminalOutputChunk: MessageFns<TerminalOutputChunk> = {
  fromJSON(object: any): TerminalOutputChunk {
    return {
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      data: isSet(object.data) ? globalThis.String(object.data) : "",
    };
  },

  toJSON(message: TerminalOutputChunk): unknown {
    const obj: any = {};
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalOutputChunk>, I>>(base?: I): TerminalOutputChunk {
    return TerminalOutputChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalOutputChunk>, I>>(object: I): TerminalOutputChunk {
    const message = createBaseTerminalOutputChunk();
    message.sequence = object.sequence ?? 0;
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseTerminalStateChanged(): TerminalStateChanged {
  return { status: 0, sequence: 0 };
}

export const TerminalStateChanged: MessageFns<TerminalStateChanged> = {
  fromJSON(object: any): TerminalStateChanged {
    return {
      status: isSet(object.status) ? terminalStatusFromJSON(object.status) : 0,
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
    };
  },

  toJSON(message: TerminalStateChanged): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = terminalStatusToJSON(message.status);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalStateChanged>, I>>(base?: I): TerminalStateChanged {
    return TerminalStateChanged.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalStateChanged>, I>>(object: I): TerminalStateChanged {
    const message = createBaseTerminalStateChanged();
    message.status = object.status ?? 0;
    message.sequence = object.sequence ?? 0;
    return message;
  },
};

function createBaseTerminalCompleted(): TerminalCompleted {
  return { exit_code: 0, signal: undefined };
}

export const TerminalCompleted: MessageFns<TerminalCompleted> = {
  fromJSON(object: any): TerminalCompleted {
    return {
      exit_code: isSet(object.exit_code) ? globalThis.Number(object.exit_code) : 0,
      signal: isSet(object.signal) ? globalThis.String(object.signal) : undefined,
    };
  },

  toJSON(message: TerminalCompleted): unknown {
    const obj: any = {};
    if (message.exit_code !== 0) {
      obj.exit_code = Math.round(message.exit_code);
    }
    if (message.signal !== undefined) {
      obj.signal = message.signal;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalCompleted>, I>>(base?: I): TerminalCompleted {
    return TerminalCompleted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalCompleted>, I>>(object: I): TerminalCompleted {
    const message = createBaseTerminalCompleted();
    message.exit_code = object.exit_code ?? 0;
    message.signal = object.signal ?? undefined;
    return message;
  },
};

function createBaseTerminalServerMessage(): TerminalServerMessage {
  return { payload: undefined };
}

export const TerminalServerMessage: MessageFns<TerminalServerMessage> = {
  fromJSON(object: any): TerminalServerMessage {
    return {
      payload: isSet(object.attached)
        ? { $case: "attached", attached: TerminalSession.fromJSON(object.attached) }
        : isSet(object.detached)
        ? { $case: "detached", detached: TerminalSession.fromJSON(object.detached) }
        : isSet(object.output)
        ? { $case: "output", output: TerminalOutputChunk.fromJSON(object.output) }
        : isSet(object.state_changed)
        ? { $case: "state_changed", state_changed: TerminalStateChanged.fromJSON(object.state_changed) }
        : isSet(object.completed)
        ? { $case: "completed", completed: TerminalCompleted.fromJSON(object.completed) }
        : isSet(object.error)
        ? { $case: "error", error: Error.fromJSON(object.error) }
        : isSet(object.json)
        ? { $case: "json", json: TerminalJsonMessage.fromJSON(object.json) }
        : undefined,
    };
  },

  toJSON(message: TerminalServerMessage): unknown {
    const obj: any = {};
    if (message.payload?.$case === "attached") {
      obj.attached = TerminalSession.toJSON(message.payload.attached);
    } else if (message.payload?.$case === "detached") {
      obj.detached = TerminalSession.toJSON(message.payload.detached);
    } else if (message.payload?.$case === "output") {
      obj.output = TerminalOutputChunk.toJSON(message.payload.output);
    } else if (message.payload?.$case === "state_changed") {
      obj.state_changed = TerminalStateChanged.toJSON(message.payload.state_changed);
    } else if (message.payload?.$case === "completed") {
      obj.completed = TerminalCompleted.toJSON(message.payload.completed);
    } else if (message.payload?.$case === "error") {
      obj.error = Error.toJSON(message.payload.error);
    } else if (message.payload?.$case === "json") {
      obj.json = TerminalJsonMessage.toJSON(message.payload.json);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalServerMessage>, I>>(base?: I): TerminalServerMessage {
    return TerminalServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalServerMessage>, I>>(object: I): TerminalServerMessage {
    const message = createBaseTerminalServerMessage();
    switch (object.payload?.$case) {
      case "attached": {
        if (object.payload?.attached !== undefined && object.payload?.attached !== null) {
          message.payload = { $case: "attached", attached: TerminalSession.fromPartial(object.payload.attached) };
        }
        break;
      }
      case "detached": {
        if (object.payload?.detached !== undefined && object.payload?.detached !== null) {
          message.payload = { $case: "detached", detached: TerminalSession.fromPartial(object.payload.detached) };
        }
        break;
      }
      case "output": {
        if (object.payload?.output !== undefined && object.payload?.output !== null) {
          message.payload = { $case: "output", output: TerminalOutputChunk.fromPartial(object.payload.output) };
        }
        break;
      }
      case "state_changed": {
        if (object.payload?.state_changed !== undefined && object.payload?.state_changed !== null) {
          message.payload = {
            $case: "state_changed",
            state_changed: TerminalStateChanged.fromPartial(object.payload.state_changed),
          };
        }
        break;
      }
      case "completed": {
        if (object.payload?.completed !== undefined && object.payload?.completed !== null) {
          message.payload = { $case: "completed", completed: TerminalCompleted.fromPartial(object.payload.completed) };
        }
        break;
      }
      case "error": {
        if (object.payload?.error !== undefined && object.payload?.error !== null) {
          message.payload = { $case: "error", error: Error.fromPartial(object.payload.error) };
        }
        break;
      }
      case "json": {
        if (object.payload?.json !== undefined && object.payload?.json !== null) {
          message.payload = { $case: "json", json: TerminalJsonMessage.fromPartial(object.payload.json) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
