// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/terminal/v1/terminal.proto

/* eslint-disable */

export const protobufPackage = "boxteam.terminal.v1";

export enum TerminalStatus {
  TERMINAL_STATUS_UNSPECIFIED = 0,
  TERMINAL_STATUS_CREATED = 1,
  TERMINAL_STATUS_RUNNING = 2,
  TERMINAL_STATUS_EXITED = 3,
  TERMINAL_STATUS_TERMINATED = 4,
  TERMINAL_STATUS_DELETED = 5,
  UNRECOGNIZED = -1,
}

export function terminalStatusFromJSON(object: any): TerminalStatus {
  switch (object) {
    case 0:
    case "TERMINAL_STATUS_UNSPECIFIED":
      return TerminalStatus.TERMINAL_STATUS_UNSPECIFIED;
    case 1:
    case "TERMINAL_STATUS_CREATED":
      return TerminalStatus.TERMINAL_STATUS_CREATED;
    case 2:
    case "TERMINAL_STATUS_RUNNING":
      return TerminalStatus.TERMINAL_STATUS_RUNNING;
    case 3:
    case "TERMINAL_STATUS_EXITED":
      return TerminalStatus.TERMINAL_STATUS_EXITED;
    case 4:
    case "TERMINAL_STATUS_TERMINATED":
      return TerminalStatus.TERMINAL_STATUS_TERMINATED;
    case 5:
    case "TERMINAL_STATUS_DELETED":
      return TerminalStatus.TERMINAL_STATUS_DELETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TerminalStatus.UNRECOGNIZED;
  }
}

export function terminalStatusToJSON(object: TerminalStatus): string {
  switch (object) {
    case TerminalStatus.TERMINAL_STATUS_UNSPECIFIED:
      return "TERMINAL_STATUS_UNSPECIFIED";
    case TerminalStatus.TERMINAL_STATUS_CREATED:
      return "TERMINAL_STATUS_CREATED";
    case TerminalStatus.TERMINAL_STATUS_RUNNING:
      return "TERMINAL_STATUS_RUNNING";
    case TerminalStatus.TERMINAL_STATUS_EXITED:
      return "TERMINAL_STATUS_EXITED";
    case TerminalStatus.TERMINAL_STATUS_TERMINATED:
      return "TERMINAL_STATUS_TERMINATED";
    case TerminalStatus.TERMINAL_STATUS_DELETED:
      return "TERMINAL_STATUS_DELETED";
    case TerminalStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TerminalSession {
  terminal_id: string;
  session_id: string;
  title: string;
  cwd: string;
  cols: number;
  rows: number;
  status: TerminalStatus;
  sequence: number;
  metadata: { [key: string]: any } | undefined;
  created_at: string | undefined;
  updated_at: string | undefined;
}

export interface TerminalJsonMessage {
  type: string;
  payload: { [key: string]: any } | undefined;
}

function createBaseTerminalSession(): TerminalSession {
  return {
    terminal_id: "",
    session_id: "",
    title: "",
    cwd: "",
    cols: 0,
    rows: 0,
    status: 0,
    sequence: 0,
    metadata: undefined,
    created_at: undefined,
    updated_at: undefined,
  };
}

export const TerminalSession: MessageFns<TerminalSession> = {
  fromJSON(object: any): TerminalSession {
    return {
      terminal_id: isSet(object.terminal_id) ? globalThis.String(object.terminal_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      cwd: isSet(object.cwd) ? globalThis.String(object.cwd) : "",
      cols: isSet(object.cols) ? globalThis.Number(object.cols) : 0,
      rows: isSet(object.rows) ? globalThis.Number(object.rows) : 0,
      status: isSet(object.status) ? terminalStatusFromJSON(object.status) : 0,
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : undefined,
      updated_at: isSet(object.updated_at) ? globalThis.String(object.updated_at) : undefined,
    };
  },

  toJSON(message: TerminalSession): unknown {
    const obj: any = {};
    if (message.terminal_id !== "") {
      obj.terminal_id = message.terminal_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.cwd !== "") {
      obj.cwd = message.cwd;
    }
    if (message.cols !== 0) {
      obj.cols = Math.round(message.cols);
    }
    if (message.rows !== 0) {
      obj.rows = Math.round(message.rows);
    }
    if (message.status !== 0) {
      obj.status = terminalStatusToJSON(message.status);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at;
    }
    if (message.updated_at !== undefined) {
      obj.updated_at = message.updated_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalSession>, I>>(base?: I): TerminalSession {
    return TerminalSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalSession>, I>>(object: I): TerminalSession {
    const message = createBaseTerminalSession();
    message.terminal_id = object.terminal_id ?? "";
    message.session_id = object.session_id ?? "";
    message.title = object.title ?? "";
    message.cwd = object.cwd ?? "";
    message.cols = object.cols ?? 0;
    message.rows = object.rows ?? 0;
    message.status = object.status ?? 0;
    message.sequence = object.sequence ?? 0;
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? undefined;
    message.updated_at = object.updated_at ?? undefined;
    return message;
  },
};

function createBaseTerminalJsonMessage(): TerminalJsonMessage {
  return { type: "", payload: undefined };
}

export const TerminalJsonMessage: MessageFns<TerminalJsonMessage> = {
  fromJSON(object: any): TerminalJsonMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      payload: isObject(object.payload) ? object.payload : undefined,
    };
  },

  toJSON(message: TerminalJsonMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalJsonMessage>, I>>(base?: I): TerminalJsonMessage {
    return TerminalJsonMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalJsonMessage>, I>>(object: I): TerminalJsonMessage {
    const message = createBaseTerminalJsonMessage();
    message.type = object.type ?? "";
    message.payload = object.payload ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
