// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/terminal/v1/terminal_input.proto

/* eslint-disable */
import { TerminalJsonMessage } from "./terminal.js";

export const protobufPackage = "boxteam.terminal.v1";

export interface TerminalAttach {
  terminal_id: string;
  cols?: number | undefined;
  rows?: number | undefined;
  after_sequence?: number | undefined;
}

export interface TerminalDetach {
  terminal_id?: string | undefined;
}

export interface TerminalInput {
  data: string;
  source: string;
}

export interface TerminalResize {
  cols: number;
  rows: number;
}

export interface TerminalAcknowledge {
  sequence: number;
}

export interface TerminalClientMessage {
  payload:
    | { $case: "attach"; attach: TerminalAttach }
    | { $case: "detach"; detach: TerminalDetach }
    | { $case: "input"; input: TerminalInput }
    | { $case: "agent_input"; agent_input: TerminalInput }
    | { $case: "resize"; resize: TerminalResize }
    | { $case: "acknowledge"; acknowledge: TerminalAcknowledge }
    | { $case: "json"; json: TerminalJsonMessage }
    | undefined;
}

function createBaseTerminalAttach(): TerminalAttach {
  return { terminal_id: "", cols: undefined, rows: undefined, after_sequence: undefined };
}

export const TerminalAttach: MessageFns<TerminalAttach> = {
  fromJSON(object: any): TerminalAttach {
    return {
      terminal_id: isSet(object.terminal_id) ? globalThis.String(object.terminal_id) : "",
      cols: isSet(object.cols) ? globalThis.Number(object.cols) : undefined,
      rows: isSet(object.rows) ? globalThis.Number(object.rows) : undefined,
      after_sequence: isSet(object.after_sequence) ? globalThis.Number(object.after_sequence) : undefined,
    };
  },

  toJSON(message: TerminalAttach): unknown {
    const obj: any = {};
    if (message.terminal_id !== "") {
      obj.terminal_id = message.terminal_id;
    }
    if (message.cols !== undefined) {
      obj.cols = Math.round(message.cols);
    }
    if (message.rows !== undefined) {
      obj.rows = Math.round(message.rows);
    }
    if (message.after_sequence !== undefined) {
      obj.after_sequence = Math.round(message.after_sequence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalAttach>, I>>(base?: I): TerminalAttach {
    return TerminalAttach.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalAttach>, I>>(object: I): TerminalAttach {
    const message = createBaseTerminalAttach();
    message.terminal_id = object.terminal_id ?? "";
    message.cols = object.cols ?? undefined;
    message.rows = object.rows ?? undefined;
    message.after_sequence = object.after_sequence ?? undefined;
    return message;
  },
};

function createBaseTerminalDetach(): TerminalDetach {
  return { terminal_id: undefined };
}

export const TerminalDetach: MessageFns<TerminalDetach> = {
  fromJSON(object: any): TerminalDetach {
    return { terminal_id: isSet(object.terminal_id) ? globalThis.String(object.terminal_id) : undefined };
  },

  toJSON(message: TerminalDetach): unknown {
    const obj: any = {};
    if (message.terminal_id !== undefined) {
      obj.terminal_id = message.terminal_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalDetach>, I>>(base?: I): TerminalDetach {
    return TerminalDetach.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalDetach>, I>>(object: I): TerminalDetach {
    const message = createBaseTerminalDetach();
    message.terminal_id = object.terminal_id ?? undefined;
    return message;
  },
};

function createBaseTerminalInput(): TerminalInput {
  return { data: "", source: "" };
}

export const TerminalInput: MessageFns<TerminalInput> = {
  fromJSON(object: any): TerminalInput {
    return {
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
    };
  },

  toJSON(message: TerminalInput): unknown {
    const obj: any = {};
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalInput>, I>>(base?: I): TerminalInput {
    return TerminalInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalInput>, I>>(object: I): TerminalInput {
    const message = createBaseTerminalInput();
    message.data = object.data ?? "";
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseTerminalResize(): TerminalResize {
  return { cols: 0, rows: 0 };
}

export const TerminalResize: MessageFns<TerminalResize> = {
  fromJSON(object: any): TerminalResize {
    return {
      cols: isSet(object.cols) ? globalThis.Number(object.cols) : 0,
      rows: isSet(object.rows) ? globalThis.Number(object.rows) : 0,
    };
  },

  toJSON(message: TerminalResize): unknown {
    const obj: any = {};
    if (message.cols !== 0) {
      obj.cols = Math.round(message.cols);
    }
    if (message.rows !== 0) {
      obj.rows = Math.round(message.rows);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalResize>, I>>(base?: I): TerminalResize {
    return TerminalResize.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalResize>, I>>(object: I): TerminalResize {
    const message = createBaseTerminalResize();
    message.cols = object.cols ?? 0;
    message.rows = object.rows ?? 0;
    return message;
  },
};

function createBaseTerminalAcknowledge(): TerminalAcknowledge {
  return { sequence: 0 };
}

export const TerminalAcknowledge: MessageFns<TerminalAcknowledge> = {
  fromJSON(object: any): TerminalAcknowledge {
    return { sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0 };
  },

  toJSON(message: TerminalAcknowledge): unknown {
    const obj: any = {};
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalAcknowledge>, I>>(base?: I): TerminalAcknowledge {
    return TerminalAcknowledge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalAcknowledge>, I>>(object: I): TerminalAcknowledge {
    const message = createBaseTerminalAcknowledge();
    message.sequence = object.sequence ?? 0;
    return message;
  },
};

function createBaseTerminalClientMessage(): TerminalClientMessage {
  return { payload: undefined };
}

export const TerminalClientMessage: MessageFns<TerminalClientMessage> = {
  fromJSON(object: any): TerminalClientMessage {
    return {
      payload: isSet(object.attach)
        ? { $case: "attach", attach: TerminalAttach.fromJSON(object.attach) }
        : isSet(object.detach)
        ? { $case: "detach", detach: TerminalDetach.fromJSON(object.detach) }
        : isSet(object.input)
        ? { $case: "input", input: TerminalInput.fromJSON(object.input) }
        : isSet(object.agent_input)
        ? { $case: "agent_input", agent_input: TerminalInput.fromJSON(object.agent_input) }
        : isSet(object.resize)
        ? { $case: "resize", resize: TerminalResize.fromJSON(object.resize) }
        : isSet(object.acknowledge)
        ? { $case: "acknowledge", acknowledge: TerminalAcknowledge.fromJSON(object.acknowledge) }
        : isSet(object.json)
        ? { $case: "json", json: TerminalJsonMessage.fromJSON(object.json) }
        : undefined,
    };
  },

  toJSON(message: TerminalClientMessage): unknown {
    const obj: any = {};
    if (message.payload?.$case === "attach") {
      obj.attach = TerminalAttach.toJSON(message.payload.attach);
    } else if (message.payload?.$case === "detach") {
      obj.detach = TerminalDetach.toJSON(message.payload.detach);
    } else if (message.payload?.$case === "input") {
      obj.input = TerminalInput.toJSON(message.payload.input);
    } else if (message.payload?.$case === "agent_input") {
      obj.agent_input = TerminalInput.toJSON(message.payload.agent_input);
    } else if (message.payload?.$case === "resize") {
      obj.resize = TerminalResize.toJSON(message.payload.resize);
    } else if (message.payload?.$case === "acknowledge") {
      obj.acknowledge = TerminalAcknowledge.toJSON(message.payload.acknowledge);
    } else if (message.payload?.$case === "json") {
      obj.json = TerminalJsonMessage.toJSON(message.payload.json);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TerminalClientMessage>, I>>(base?: I): TerminalClientMessage {
    return TerminalClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TerminalClientMessage>, I>>(object: I): TerminalClientMessage {
    const message = createBaseTerminalClientMessage();
    switch (object.payload?.$case) {
      case "attach": {
        if (object.payload?.attach !== undefined && object.payload?.attach !== null) {
          message.payload = { $case: "attach", attach: TerminalAttach.fromPartial(object.payload.attach) };
        }
        break;
      }
      case "detach": {
        if (object.payload?.detach !== undefined && object.payload?.detach !== null) {
          message.payload = { $case: "detach", detach: TerminalDetach.fromPartial(object.payload.detach) };
        }
        break;
      }
      case "input": {
        if (object.payload?.input !== undefined && object.payload?.input !== null) {
          message.payload = { $case: "input", input: TerminalInput.fromPartial(object.payload.input) };
        }
        break;
      }
      case "agent_input": {
        if (object.payload?.agent_input !== undefined && object.payload?.agent_input !== null) {
          message.payload = {
            $case: "agent_input",
            agent_input: TerminalInput.fromPartial(object.payload.agent_input),
          };
        }
        break;
      }
      case "resize": {
        if (object.payload?.resize !== undefined && object.payload?.resize !== null) {
          message.payload = { $case: "resize", resize: TerminalResize.fromPartial(object.payload.resize) };
        }
        break;
      }
      case "acknowledge": {
        if (object.payload?.acknowledge !== undefined && object.payload?.acknowledge !== null) {
          message.payload = {
            $case: "acknowledge",
            acknowledge: TerminalAcknowledge.fromPartial(object.payload.acknowledge),
          };
        }
        break;
      }
      case "json": {
        if (object.payload?.json !== undefined && object.payload?.json !== null) {
          message.payload = { $case: "json", json: TerminalJsonMessage.fromPartial(object.payload.json) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
