"""v2 itemized domain primitives。"""

from app.domain.itemized.assembly_snapshot import ContextAssemblySnapshot
from app.domain.itemized.enums import (
    BaseDeltaRole,
    CanonicalItemStatus,
    CommitKind,
    CommitMode,
    ControlOutcome,
    DetailAvailability,
    DetailProtection,
    PayloadKind,
    SelectionKind,
    SemanticKind,
    TurnScope,
    TurnStatus,
)
from app.domain.itemized.errors import FormatDispatchError, ItemSchemaError
from app.domain.itemized.hashing import (
    canonical_json_bytes,
    content_hash,
    contribution_content_hash,
    sha256_jcs,
    validate_hash_token,
)
from app.domain.itemized.parts import ContentPart, ContentPartAnchor
from app.domain.itemized.prefix_epoch import (
    PENDING_TRANSITION_REASONS,
    REBUILD_EPOCH_REASONS,
    AppendedItemRef,
    EpochContractError,
    EpochReason,
    ParentAssemblyRef,
    PendingPrefixEpochTransition,
    PrefixEpoch,
    PrefixEpochState,
    ProviderProfileChangeRequiresRebuildError,
    ProviderProfileItemFrame,
    SealedPrefixAssembly,
    SourceIdentityConflictError,
    StablePrefixDigest,
    StablePrefixViolationError,
    ToolSetRebaseRequiredError,
    append_items,
    initial_epoch_state,
    open_rebuild_epoch,
    seal_assembly,
    stable_prefix_bytes,
    stable_prefix_digest,
    stable_prefix_hash,
    toolset_compatibility_key,
    verify_stable_prefix,
)
from app.domain.itemized.records import (
    CanonicalItemRecord,
    ProducerRef,
)
from app.domain.itemized.refs import (
    ContextRef,
    ToolSetRef,
    ref_identity,
    require_manifest_token,
    selection_ref_identity,
    unique_ref_identities,
)
from app.domain.itemized.request_plan import ContextContribution, ContextRequestPlan
from app.domain.itemized.root_compilation import (
    CompiledRootItem,
    CompiledRootSourceProvenance,
    IncludedReason,
    RootCandidateSource,
    RootCompileBoundaryError,
    RootCompileConflictError,
    RootPlacement,
    RootPlacementViolationError,
    WireRole,
    compile_root_item,
    resolve_source_wire_role,
    validate_epoch_root_uniqueness,
)
from app.domain.itemized.runtime import (
    ExecutionRecord,
    ItemDraft,
    ModelCallRecord,
    ProvenanceEdge,
    TurnRecord,
)
from app.domain.itemized.schema import (
    validate_item_compatibility,
    validate_selection_compatibility,
)
from app.domain.itemized.selection import ContextSelectionEntry
from app.domain.itemized.serialization import ordered_selection
from app.domain.itemized.validation import validate_turn_transition

__all__ = [
    "PENDING_TRANSITION_REASONS",
    "REBUILD_EPOCH_REASONS",
    "AppendedItemRef",
    "BaseDeltaRole",
    "CanonicalItemRecord",
    "CanonicalItemStatus",
    "CommitKind",
    "CommitMode",
    "CompiledRootItem",
    "CompiledRootSourceProvenance",
    "ContentPart",
    "ContentPartAnchor",
    "ContextAssemblySnapshot",
    "ContextContribution",
    "ContextRef",
    "ContextRequestPlan",
    "ContextSelectionEntry",
    "ControlOutcome",
    "DetailAvailability",
    "DetailProtection",
    "EpochContractError",
    "EpochReason",
    "ExecutionRecord",
    "FormatDispatchError",
    "IncludedReason",
    "ItemDraft",
    "ItemSchemaError",
    "ModelCallRecord",
    "ParentAssemblyRef",
    "PayloadKind",
    "PendingPrefixEpochTransition",
    "PrefixEpoch",
    "PrefixEpochState",
    "ProducerRef",
    "ProvenanceEdge",
    "ProviderProfileChangeRequiresRebuildError",
    "ProviderProfileItemFrame",
    "RootCandidateSource",
    "RootCompileBoundaryError",
    "RootCompileConflictError",
    "RootPlacement",
    "RootPlacementViolationError",
    "SealedPrefixAssembly",
    "SelectionKind",
    "SemanticKind",
    "SourceIdentityConflictError",
    "StablePrefixDigest",
    "StablePrefixViolationError",
    "ToolSetRebaseRequiredError",
    "ToolSetRef",
    "TurnRecord",
    "TurnScope",
    "TurnStatus",
    "WireRole",
    "append_items",
    "canonical_json_bytes",
    "compile_root_item",
    "content_hash",
    "contribution_content_hash",
    "initial_epoch_state",
    "open_rebuild_epoch",
    "ordered_selection",
    "ref_identity",
    "require_manifest_token",
    "selection_ref_identity",
    "resolve_source_wire_role",
    "seal_assembly",
    "sha256_jcs",
    "stable_prefix_bytes",
    "stable_prefix_digest",
    "stable_prefix_hash",
    "toolset_compatibility_key",
    "unique_ref_identities",
    "validate_epoch_root_uniqueness",
    "validate_hash_token",
    "validate_item_compatibility",
    "validate_selection_compatibility",
    "validate_turn_transition",
    "verify_stable_prefix",
]
