// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/gateway/v1/health.proto

/* eslint-disable */
import {
  ServiceHealth,
  ServiceStatus,
  serviceStatusFromJSON,
  serviceStatusToJSON,
} from "../../common/v1/service_lifecycle.js";

export const protobufPackage = "boxteam.gateway.v1";

export interface GatewayHealth {
  gateway_id: string;
  status: ServiceStatus;
  active_workspace_id: string;
  services: ServiceHealth[];
  process_id: number;
  development_restart_available: boolean;
}

function createBaseGatewayHealth(): GatewayHealth {
  return {
    gateway_id: "",
    status: 0,
    active_workspace_id: "",
    services: [],
    process_id: 0,
    development_restart_available: false,
  };
}

export const GatewayHealth: MessageFns<GatewayHealth> = {
  fromJSON(object: any): GatewayHealth {
    return {
      gateway_id: isSet(object.gateway_id) ? globalThis.String(object.gateway_id) : "",
      status: isSet(object.status) ? serviceStatusFromJSON(object.status) : 0,
      active_workspace_id: isSet(object.active_workspace_id) ? globalThis.String(object.active_workspace_id) : "",
      services: globalThis.Array.isArray(object?.services)
        ? object.services.map((e: any) => ServiceHealth.fromJSON(e))
        : [],
      process_id: isSet(object.process_id) ? globalThis.Number(object.process_id) : 0,
      development_restart_available: isSet(object.development_restart_available)
        ? globalThis.Boolean(object.development_restart_available)
        : false,
    };
  },

  toJSON(message: GatewayHealth): unknown {
    const obj: any = {};
    if (message.gateway_id !== "") {
      obj.gateway_id = message.gateway_id;
    }
    if (message.status !== 0) {
      obj.status = serviceStatusToJSON(message.status);
    }
    if (message.active_workspace_id !== "") {
      obj.active_workspace_id = message.active_workspace_id;
    }
    if (message.services?.length) {
      obj.services = message.services.map((e) => ServiceHealth.toJSON(e));
    }
    if (message.process_id !== 0) {
      obj.process_id = Math.round(message.process_id);
    }
    if (message.development_restart_available !== false) {
      obj.development_restart_available = message.development_restart_available;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GatewayHealth>, I>>(base?: I): GatewayHealth {
    return GatewayHealth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GatewayHealth>, I>>(object: I): GatewayHealth {
    const message = createBaseGatewayHealth();
    message.gateway_id = object.gateway_id ?? "";
    message.status = object.status ?? 0;
    message.active_workspace_id = object.active_workspace_id ?? "";
    message.services = object.services?.map((e) => ServiceHealth.fromPartial(e)) || [];
    message.process_id = object.process_id ?? 0;
    message.development_restart_available = object.development_restart_available ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
