// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/gateway/v1/proxy.proto

/* eslint-disable */

export const protobufPackage = "boxteam.gateway.v1";

export interface ProxyTarget {
  workspace_id: string;
  service: string;
  path: string;
}

export interface ProxyResponseMetadata {
  status_code: number;
  headers: { [key: string]: string };
}

export interface ProxyResponseMetadata_HeadersEntry {
  key: string;
  value: string;
}

function createBaseProxyTarget(): ProxyTarget {
  return { workspace_id: "", service: "", path: "" };
}

export const ProxyTarget: MessageFns<ProxyTarget> = {
  fromJSON(object: any): ProxyTarget {
    return {
      workspace_id: isSet(object.workspace_id) ? globalThis.String(object.workspace_id) : "",
      service: isSet(object.service) ? globalThis.String(object.service) : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: ProxyTarget): unknown {
    const obj: any = {};
    if (message.workspace_id !== "") {
      obj.workspace_id = message.workspace_id;
    }
    if (message.service !== "") {
      obj.service = message.service;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxyTarget>, I>>(base?: I): ProxyTarget {
    return ProxyTarget.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxyTarget>, I>>(object: I): ProxyTarget {
    const message = createBaseProxyTarget();
    message.workspace_id = object.workspace_id ?? "";
    message.service = object.service ?? "";
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseProxyResponseMetadata(): ProxyResponseMetadata {
  return { status_code: 0, headers: {} };
}

export const ProxyResponseMetadata: MessageFns<ProxyResponseMetadata> = {
  fromJSON(object: any): ProxyResponseMetadata {
    return {
      status_code: isSet(object.status_code) ? globalThis.Number(object.status_code) : 0,
      headers: isObject(object.headers)
        ? (globalThis.Object.entries(object.headers) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            globalThis.Object.defineProperty(acc, key, {
              value: globalThis.String(value),
              enumerable: true,
              configurable: true,
              writable: true,
            });
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ProxyResponseMetadata): unknown {
    const obj: any = {};
    if (message.status_code !== 0) {
      obj.status_code = Math.round(message.status_code);
    }
    if (message.headers) {
      const entries = globalThis.Object.entries(message.headers) as [string, string][];
      if (entries.length > 0) {
        obj.headers = {};
        entries.forEach(([k, v]) => {
          obj.headers[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxyResponseMetadata>, I>>(base?: I): ProxyResponseMetadata {
    return ProxyResponseMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxyResponseMetadata>, I>>(object: I): ProxyResponseMetadata {
    const message = createBaseProxyResponseMetadata();
    message.status_code = object.status_code ?? 0;
    message.headers = (globalThis.Object.entries(object.headers ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseProxyResponseMetadata_HeadersEntry(): ProxyResponseMetadata_HeadersEntry {
  return { key: "", value: "" };
}

export const ProxyResponseMetadata_HeadersEntry: MessageFns<ProxyResponseMetadata_HeadersEntry> = {
  fromJSON(object: any): ProxyResponseMetadata_HeadersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ProxyResponseMetadata_HeadersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxyResponseMetadata_HeadersEntry>, I>>(
    base?: I,
  ): ProxyResponseMetadata_HeadersEntry {
    return ProxyResponseMetadata_HeadersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxyResponseMetadata_HeadersEntry>, I>>(
    object: I,
  ): ProxyResponseMetadata_HeadersEntry {
    const message = createBaseProxyResponseMetadata_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
