// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/gateway/v1/workspace_registry.proto

/* eslint-disable */

export const protobufPackage = "boxteam.gateway.v1";

export enum WorkspaceStatus {
  WORKSPACE_STATUS_UNSPECIFIED = 0,
  WORKSPACE_STATUS_READY = 1,
  WORKSPACE_STATUS_OFFLINE = 2,
  UNRECOGNIZED = -1,
}

export function workspaceStatusFromJSON(object: any): WorkspaceStatus {
  switch (object) {
    case 0:
    case "WORKSPACE_STATUS_UNSPECIFIED":
      return WorkspaceStatus.WORKSPACE_STATUS_UNSPECIFIED;
    case 1:
    case "WORKSPACE_STATUS_READY":
      return WorkspaceStatus.WORKSPACE_STATUS_READY;
    case 2:
    case "WORKSPACE_STATUS_OFFLINE":
      return WorkspaceStatus.WORKSPACE_STATUS_OFFLINE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WorkspaceStatus.UNRECOGNIZED;
  }
}

export function workspaceStatusToJSON(object: WorkspaceStatus): string {
  switch (object) {
    case WorkspaceStatus.WORKSPACE_STATUS_UNSPECIFIED:
      return "WORKSPACE_STATUS_UNSPECIFIED";
    case WorkspaceStatus.WORKSPACE_STATUS_READY:
      return "WORKSPACE_STATUS_READY";
    case WorkspaceStatus.WORKSPACE_STATUS_OFFLINE:
      return "WORKSPACE_STATUS_OFFLINE";
    case WorkspaceStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface WorkspaceSummary {
  workspace_id: string;
  name: string;
  root_path: string;
  backend_url: string;
  status: WorkspaceStatus;
  active: boolean;
  connection_kind: string;
}

export interface WorkspaceRegistry {
  active_workspace_id: string;
  items: WorkspaceSummary[];
}

function createBaseWorkspaceSummary(): WorkspaceSummary {
  return { workspace_id: "", name: "", root_path: "", backend_url: "", status: 0, active: false, connection_kind: "" };
}

export const WorkspaceSummary: MessageFns<WorkspaceSummary> = {
  fromJSON(object: any): WorkspaceSummary {
    return {
      workspace_id: isSet(object.workspace_id) ? globalThis.String(object.workspace_id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      root_path: isSet(object.root_path) ? globalThis.String(object.root_path) : "",
      backend_url: isSet(object.backend_url) ? globalThis.String(object.backend_url) : "",
      status: isSet(object.status) ? workspaceStatusFromJSON(object.status) : 0,
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      connection_kind: isSet(object.connection_kind) ? globalThis.String(object.connection_kind) : "",
    };
  },

  toJSON(message: WorkspaceSummary): unknown {
    const obj: any = {};
    if (message.workspace_id !== "") {
      obj.workspace_id = message.workspace_id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.root_path !== "") {
      obj.root_path = message.root_path;
    }
    if (message.backend_url !== "") {
      obj.backend_url = message.backend_url;
    }
    if (message.status !== 0) {
      obj.status = workspaceStatusToJSON(message.status);
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.connection_kind !== "") {
      obj.connection_kind = message.connection_kind;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkspaceSummary>, I>>(base?: I): WorkspaceSummary {
    return WorkspaceSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkspaceSummary>, I>>(object: I): WorkspaceSummary {
    const message = createBaseWorkspaceSummary();
    message.workspace_id = object.workspace_id ?? "";
    message.name = object.name ?? "";
    message.root_path = object.root_path ?? "";
    message.backend_url = object.backend_url ?? "";
    message.status = object.status ?? 0;
    message.active = object.active ?? false;
    message.connection_kind = object.connection_kind ?? "";
    return message;
  },
};

function createBaseWorkspaceRegistry(): WorkspaceRegistry {
  return { active_workspace_id: "", items: [] };
}

export const WorkspaceRegistry: MessageFns<WorkspaceRegistry> = {
  fromJSON(object: any): WorkspaceRegistry {
    return {
      active_workspace_id: isSet(object.active_workspace_id) ? globalThis.String(object.active_workspace_id) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => WorkspaceSummary.fromJSON(e)) : [],
    };
  },

  toJSON(message: WorkspaceRegistry): unknown {
    const obj: any = {};
    if (message.active_workspace_id !== "") {
      obj.active_workspace_id = message.active_workspace_id;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => WorkspaceSummary.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkspaceRegistry>, I>>(base?: I): WorkspaceRegistry {
    return WorkspaceRegistry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkspaceRegistry>, I>>(object: I): WorkspaceRegistry {
    const message = createBaseWorkspaceRegistry();
    message.active_workspace_id = object.active_workspace_id ?? "";
    message.items = object.items?.map((e) => WorkspaceSummary.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
