from typing import Literal

ThemeBase = Literal["warm", "green", "blue"]

WARM_TOKENS = {
    "--bt-font-family": 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--bt-font-family-mono": '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "--bt-font-size": "13px",
    "--bt-font-size-heading": "18px",
    "--bt-font-size-label": "11px",
    "--bt-font-weight": "400",
    "--bt-page-background": "#f2ecd9",
    "--bt-canvas-background": "var(--bt-page-background)",
    "--bt-chrome-surface": "color-mix(in srgb, var(--bt-panel-background) 58%, transparent)",
    "--bt-workspace-surface": "color-mix(in srgb, var(--bt-surface-background) 42%, transparent)",
    "--bt-panel-surface": "color-mix(in srgb, var(--bt-surface-raised) 84%, transparent)",
    "--bt-floating-surface": "var(--bt-overlay-background)",
    "--bt-critical-surface": "var(--bt-surface-raised)",
    "--bt-toolbar-background": "color-mix(in srgb, var(--bt-panel-background) 22%, transparent)",
    "--bt-workspace-header-background": "color-mix(in srgb, var(--bt-panel-background) 34%, transparent)",
    "--bt-bottom-panel-background": "color-mix(in srgb, var(--bt-panel-background) 58%, transparent)",
    "--bt-bottom-panel-header-background": "color-mix(in srgb, var(--bt-surface-muted) 28%, transparent)",
    "--bt-bottom-panel-toolbar-background": "color-mix(in srgb, var(--bt-surface-background) 42%, transparent)",
    "--bt-bottom-panel-list-background": "color-mix(in srgb, var(--bt-panel-background) 68%, transparent)",
    "--bt-bottom-panel-viewer-background": "color-mix(in srgb, var(--bt-critical-surface) 68%, transparent)",
    "--bt-runtime-preview-background": "color-mix(in srgb, var(--bt-critical-surface) 62%, transparent)",
    "--bt-runtime-preview-header-background": "color-mix(in srgb, var(--bt-surface-muted) 28%, transparent)",
    "--bt-runtime-preview-border": "var(--bt-panel-border)",
    "--bt-surface-backdrop-filter": "blur(12px) saturate(1.08)",
    "--bt-chrome-backdrop-filter": "var(--bt-surface-backdrop-filter)",
    "--bt-workspace-backdrop-filter": "none",
    "--bt-panel-background": "#fff8e8",
    "--bt-surface-background": "#fbf3df",
    "--bt-surface-raised": "#fffaf0",
    "--bt-surface-muted": "#eee3c9",
    "--bt-overlay-background": "#fffaf0",
    "--bt-input-background": "#f8efd9",
    "--bt-input-foreground": "#39352b",
    "--bt-dropdown-background": "#fff8e8",
    "--bt-dropdown-foreground": "#39352b",
    "--bt-menu-background": "#fff8e8",
    "--bt-menu-foreground": "#39352b",
    "--bt-code-background": "#eee3c9",
    "--bt-chat-input-background": "#d8cfb9",
    "--bt-text-primary": "#39352b",
    "--bt-text-muted": "#766f5e",
    "--bt-text-subtle": "#8a826d",
    "--bt-text-disabled": "rgba(57, 53, 43, 0.42)",
    "--bt-text-on-strong": "#fffaf0",
    "--bt-icon-foreground": "#625b4b",
    "--bt-link-foreground": "#a85d27",
    "--bt-border": "rgba(108, 96, 70, 0.24)",
    "--bt-panel-border": "rgba(108, 96, 70, 0.24)",
    "--bt-input-border": "rgba(108, 96, 70, 0.28)",
    "--bt-menu-border": "rgba(108, 96, 70, 0.24)",
    "--bt-overlay-border": "rgba(108, 96, 70, 0.3)",
    "--bt-chat-input-border": "rgba(92, 82, 58, 0.18)",
    "--bt-chat-request-border": "rgba(108, 96, 70, 0.22)",
    "--bt-quote-border": "rgba(108, 96, 70, 0.32)",
    "--bt-focus-border": "color-mix(in srgb, var(--bt-accent) 62%, transparent)",
    "--bt-chat-input-focus-border": "color-mix(in srgb, var(--bt-accent) 62%, transparent)",
    "--bt-selection-background": "rgba(74, 84, 102, 0.2)",
    "--bt-selection-muted-background": "rgba(74, 84, 102, 0.1)",
    "--bt-active-selection-background": "rgba(74, 84, 102, 0.14)",
    "--bt-active-selection-foreground": "#26231c",
    "--bt-menu-selection-background": "rgba(74, 84, 102, 0.14)",
    "--bt-menu-selection-foreground": "#26231c",
    "--bt-menu-separator-background": "rgba(108, 96, 70, 0.18)",
    "--bt-hover-background": "rgba(72, 66, 51, 0.11)",
    "--bt-toolbar-hover-background": "rgba(72, 66, 51, 0.11)",
    "--bt-toolbar-active-background": "rgba(72, 66, 51, 0.16)",
    "--bt-section-header-background": "rgba(72, 66, 51, 0.06)",
    "--bt-surface-shadow": "0 8px 24px rgba(61, 54, 38, 0.12)",
    "--bt-scrim-background": "rgba(31, 29, 24, 0.5)",
    "--bt-highlight-soft": "rgba(255, 250, 240, 0.35)",
    "--bt-accent": "#b96f32",
    "--bt-accent-soft": "#e0b27c",
    "--bt-button-background": "#b96f32",
    "--bt-button-foreground": "#fffaf0",
    "--bt-button-border": "rgba(185, 111, 50, 0.42)",
    "--bt-button-secondary-background": "#e4d8ba",
    "--bt-button-secondary-foreground": "#39352b",
    "--bt-badge-background": "#e8ddc3",
    "--bt-badge-foreground": "#514a3c",
    "--bt-progress-background": "#b96f32",
    "--bt-status-success": "#258a55",
    "--bt-status-warning": "#b7791f",
    "--bt-status-danger": "#b33a31",
    "--bt-status-danger-background": "rgba(179, 58, 49, 0.08)",
    "--bt-status-info": "#6f5da8",
    "--bt-status-bar-background": "color-mix(in srgb, var(--bt-panel-background) 58%, transparent)",
    "--bt-status-bar-border": "var(--bt-panel-border)",
    "--bt-status-bar-foreground": "var(--bt-text-primary)",
    "--bt-chat-avatar-background": "#e4d8ba",
    "--bt-chat-request-background": "rgba(221, 212, 184, 0.58)",
    "--bt-chat-input-foreground": "#39352b",
    "--bt-chat-input-placeholder": "rgba(67, 62, 49, 0.54)",
    "--bt-scrollbar-background": "rgba(108, 96, 70, 0.2)",
    "--bt-scrollbar-hover-background": "rgba(108, 96, 70, 0.34)",
    "--bt-terminal-background": "#111827",
    "--bt-terminal-foreground": "#fffaf0",
    "--bt-terminal-muted": "rgba(255, 250, 240, 0.7)",
    "--bt-terminal-border": "rgba(255, 250, 240, 0.3)",
    "--bt-radius-small": "4px",
    "--bt-radius-medium": "6px",
    "--bt-radius-large": "8px",
    "--bt-panel-radius": "14px",
    "--bt-surface-gap": "10px",
    "--bt-surface-border": "1px solid var(--bt-panel-border)",
    "--bt-background-image": "none",
    "--bt-background-position": "center",
    "--bt-background-size": "cover",
    "--bt-background-repeat": "no-repeat",
    "--bt-background-overlay": "radial-gradient(circle at top right, rgba(45, 112, 172, 0.06), transparent 38%), radial-gradient(circle at bottom left, rgba(183, 121, 31, 0.05), transparent 32%)",
}

VARIANTS: dict[ThemeBase, dict[str, str]] = {
    "warm": {},
    "green": {
        "--bt-page-background": "#e6efe7",
        "--bt-panel-background": "#f4faf4",
        "--bt-surface-background": "#edf6ee",
        "--bt-surface-raised": "#f8fcf8",
        "--bt-surface-muted": "#d9e9db",
        "--bt-input-background": "#e8f3e9",
        "--bt-chat-input-background": "#cfdfd1",
        "--bt-text-primary": "#26382c",
        "--bt-text-muted": "#5d7062",
        "--bt-icon-foreground": "#496052",
        "--bt-accent": "#287a55",
        "--bt-button-background": "#287a55",
        "--bt-progress-background": "#287a55",
        "--bt-accent-soft": "#9bd1b4",
        "--bt-button-secondary-background": "#d3e7d6",
        "--bt-badge-background": "#d9ebdc",
        "--bt-chat-avatar-background": "#d3e7d6",
        "--bt-background-overlay": "radial-gradient(circle at top right, rgba(40, 122, 85, 0.09), transparent 40%)",
    },
    "blue": {
        "--bt-page-background": "#e6edf7",
        "--bt-panel-background": "#f3f7fc",
        "--bt-surface-background": "#ebf1f9",
        "--bt-surface-raised": "#f8faff",
        "--bt-surface-muted": "#d8e3f2",
        "--bt-input-background": "#e7eef8",
        "--bt-chat-input-background": "#cedbea",
        "--bt-text-primary": "#25354b",
        "--bt-text-muted": "#5c6d83",
        "--bt-icon-foreground": "#485d78",
        "--bt-accent": "#2f64b4",
        "--bt-button-background": "#2f64b4",
        "--bt-progress-background": "#2f64b4",
        "--bt-accent-soft": "#a8c4ef",
        "--bt-button-secondary-background": "#d3e0f1",
        "--bt-badge-background": "#dae5f4",
        "--bt-chat-avatar-background": "#d3e0f1",
        "--bt-background-overlay": "radial-gradient(circle at top right, rgba(47, 100, 180, 0.09), transparent 40%)",
    },
}
