// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/browser/v1/browser_input.proto (package boxteam.browser.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_boxteam_browser_v1_browser } from "./browser_pb.js";

/**
 * Describes the file boxteam/browser/v1/browser_input.proto.
 */
export const file_boxteam_browser_v1_browser_input = /*@__PURE__*/
  fileDesc("CiZib3h0ZWFtL2Jyb3dzZXIvdjEvYnJvd3Nlcl9pbnB1dC5wcm90bxISYm94dGVhbS5icm93c2VyLnYxIlMKDUJyb3dzZXJBdHRhY2gSEgoKYnJvd3Nlcl9pZBgBIAEoCRIbCg5wYXJ0aWNpcGFudF9pZBgCIAEoCUgAiAEBQhEKD19wYXJ0aWNpcGFudF9pZCI3Cg1Ccm93c2VyRGV0YWNoEhcKCmJyb3dzZXJfaWQYASABKAlIAIgBAUINCgtfYnJvd3Nlcl9pZCJoCg5Ccm93c2VyUG9pbnRlchIOCgZhY3Rpb24YASABKAkSCQoBeBgCIAEoARIJCgF5GAMgASgBEg4KBmJ1dHRvbhgEIAEoCRIPCgdkZWx0YV94GAUgASgBEg8KB2RlbHRhX3kYBiABKAEiYwoKQnJvd3NlcktleRIOCgZhY3Rpb24YASABKAkSCwoDa2V5GAIgASgJEgwKBGNvZGUYAyABKAkSEQoEdGV4dBgEIAEoCUgAiAEBEg4KBnJlcGVhdBgFIAEoCEIHCgVfdGV4dCItCg5Ccm93c2VyQ29tbWFuZBIMCgRuYW1lGAEgASgJEg0KBXZhbHVlGAIgASgJIjYKFUJyb3dzZXJWaWV3cG9ydFVwZGF0ZRINCgV3aWR0aBgBIAEoDRIOCgZoZWlnaHQYAiABKA0iQwoXQnJvd3NlckZyYW1lQWNrbm93bGVkZ2USEAoIZnJhbWVfaWQYASABKA0SFgoOcmVjZWl2ZWRfYnl0ZXMYAiABKA0i4QMKFEJyb3dzZXJDbGllbnRNZXNzYWdlEjMKBmF0dGFjaBgBIAEoCzIhLmJveHRlYW0uYnJvd3Nlci52MS5Ccm93c2VyQXR0YWNoSAASMwoGZGV0YWNoGAIgASgLMiEuYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJEZXRhY2hIABI1Cgdwb2ludGVyGAMgASgLMiIuYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJQb2ludGVySAASLQoDa2V5GAQgASgLMh4uYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJLZXlIABI1Cgdjb21tYW5kGAUgASgLMiIuYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJDb21tYW5kSAASPQoIdmlld3BvcnQYBiABKAsyKS5ib3h0ZWFtLmJyb3dzZXIudjEuQnJvd3NlclZpZXdwb3J0VXBkYXRlSAASQAoJZnJhbWVfYWNrGAcgASgLMisuYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJGcmFtZUFja25vd2xlZGdlSAASNgoEanNvbhgIIAEoCzImLmJveHRlYW0uYnJvd3Nlci52MS5Ccm93c2VySnNvbk1lc3NhZ2VIAEIJCgdwYXlsb2FkYgZwcm90bzM", [file_boxteam_browser_v1_browser]);

/**
 * Describes the message boxteam.browser.v1.BrowserAttach.
 * Use `create(BrowserAttachSchema)` to create a new message.
 */
export const BrowserAttachSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 0);

/**
 * Describes the message boxteam.browser.v1.BrowserDetach.
 * Use `create(BrowserDetachSchema)` to create a new message.
 */
export const BrowserDetachSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 1);

/**
 * Describes the message boxteam.browser.v1.BrowserPointer.
 * Use `create(BrowserPointerSchema)` to create a new message.
 */
export const BrowserPointerSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 2);

/**
 * Describes the message boxteam.browser.v1.BrowserKey.
 * Use `create(BrowserKeySchema)` to create a new message.
 */
export const BrowserKeySchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 3);

/**
 * Describes the message boxteam.browser.v1.BrowserCommand.
 * Use `create(BrowserCommandSchema)` to create a new message.
 */
export const BrowserCommandSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 4);

/**
 * Describes the message boxteam.browser.v1.BrowserViewportUpdate.
 * Use `create(BrowserViewportUpdateSchema)` to create a new message.
 */
export const BrowserViewportUpdateSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 5);

/**
 * Describes the message boxteam.browser.v1.BrowserFrameAcknowledge.
 * Use `create(BrowserFrameAcknowledgeSchema)` to create a new message.
 */
export const BrowserFrameAcknowledgeSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 6);

/**
 * Describes the message boxteam.browser.v1.BrowserClientMessage.
 * Use `create(BrowserClientMessageSchema)` to create a new message.
 */
export const BrowserClientMessageSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser_input, 7);

