// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/browser/v1/browser.proto (package boxteam.browser.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/browser/v1/browser.proto.
 */
export declare const file_boxteam_browser_v1_browser: GenFile;

/**
 * @generated from message boxteam.browser.v1.BrowserViewport
 */
export declare type BrowserViewport = Message<"boxteam.browser.v1.BrowserViewport"> & {
  /**
   * @generated from field: uint32 width = 1;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 2;
   */
  height: number;
};

/**
 * Describes the message boxteam.browser.v1.BrowserViewport.
 * Use `create(BrowserViewportSchema)` to create a new message.
 */
export declare const BrowserViewportSchema: GenMessage<BrowserViewport>;

/**
 * @generated from message boxteam.browser.v1.BrowserPage
 */
export declare type BrowserPage = Message<"boxteam.browser.v1.BrowserPage"> & {
  /**
   * @generated from field: string browser_id = 1;
   */
  browserId: string;

  /**
   * @generated from field: string page_id = 2;
   */
  pageId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * @generated from field: string url = 5;
   */
  url: string;

  /**
   * @generated from field: boxteam.browser.v1.BrowserViewport viewport = 6;
   */
  viewport?: BrowserViewport | undefined;

  /**
   * @generated from field: boxteam.browser.v1.BrowserStatus status = 7;
   */
  status: BrowserStatus;

  /**
   * @generated from field: uint32 sequence = 8;
   */
  sequence: number;

  /**
   * @generated from field: google.protobuf.Struct metadata = 9;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 11;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.browser.v1.BrowserPage.
 * Use `create(BrowserPageSchema)` to create a new message.
 */
export declare const BrowserPageSchema: GenMessage<BrowserPage>;

/**
 * @generated from message boxteam.browser.v1.BrowserJsonMessage
 */
export declare type BrowserJsonMessage = Message<"boxteam.browser.v1.BrowserJsonMessage"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Struct payload = 2;
   */
  payload?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.browser.v1.BrowserJsonMessage.
 * Use `create(BrowserJsonMessageSchema)` to create a new message.
 */
export declare const BrowserJsonMessageSchema: GenMessage<BrowserJsonMessage>;

/**
 * @generated from enum boxteam.browser.v1.BrowserStatus
 */
export enum BrowserStatus {
  /**
   * @generated from enum value: BROWSER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BROWSER_STATUS_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: BROWSER_STATUS_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: BROWSER_STATUS_FROZEN = 3;
   */
  FROZEN = 3,

  /**
   * @generated from enum value: BROWSER_STATUS_DISCARDED = 4;
   */
  DISCARDED = 4,

  /**
   * @generated from enum value: BROWSER_STATUS_LOST = 5;
   */
  LOST = 5,

  /**
   * @generated from enum value: BROWSER_STATUS_CLOSED = 6;
   */
  CLOSED = 6,

  /**
   * @generated from enum value: BROWSER_STATUS_DELETED = 7;
   */
  DELETED = 7,

  /**
   * @generated from enum value: BROWSER_STATUS_FAILED = 8;
   */
  FAILED = 8,
}

/**
 * Describes the enum boxteam.browser.v1.BrowserStatus.
 */
export declare const BrowserStatusSchema: GenEnum<BrowserStatus>;

