// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/browser/v1/browser.proto (package boxteam.browser.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/browser/v1/browser.proto.
 */
export const file_boxteam_browser_v1_browser = /*@__PURE__*/
  fileDesc("CiBib3h0ZWFtL2Jyb3dzZXIvdjEvYnJvd3Nlci5wcm90bxISYm94dGVhbS5icm93c2VyLnYxIjAKD0Jyb3dzZXJWaWV3cG9ydBINCgV3aWR0aBgBIAEoDRIOCgZoZWlnaHQYAiABKA0i6QIKC0Jyb3dzZXJQYWdlEhIKCmJyb3dzZXJfaWQYASABKAkSDwoHcGFnZV9pZBgCIAEoCRISCgpzZXNzaW9uX2lkGAMgASgJEg0KBXRpdGxlGAQgASgJEgsKA3VybBgFIAEoCRI1Cgh2aWV3cG9ydBgGIAEoCzIjLmJveHRlYW0uYnJvd3Nlci52MS5Ccm93c2VyVmlld3BvcnQSMQoGc3RhdHVzGAcgASgOMiEuYm94dGVhbS5icm93c2VyLnYxLkJyb3dzZXJTdGF0dXMSEAoIc2VxdWVuY2UYCCABKA0SKQoIbWV0YWRhdGEYCSABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0Ei4KCmNyZWF0ZWRfYXQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIkwKEkJyb3dzZXJKc29uTWVzc2FnZRIMCgR0eXBlGAEgASgJEigKB3BheWxvYWQYAiABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0KosCCg1Ccm93c2VyU3RhdHVzEh4KGkJST1dTRVJfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGgoWQlJPV1NFUl9TVEFUVVNfQ1JFQVRFRBABEhoKFkJST1dTRVJfU1RBVFVTX1JVTk5JTkcQAhIZChVCUk9XU0VSX1NUQVRVU19GUk9aRU4QAxIcChhCUk9XU0VSX1NUQVRVU19ESVNDQVJERUQQBBIXChNCUk9XU0VSX1NUQVRVU19MT1NUEAUSGQoVQlJPV1NFUl9TVEFUVVNfQ0xPU0VEEAYSGgoWQlJPV1NFUl9TVEFUVVNfREVMRVRFRBAHEhkKFUJST1dTRVJfU1RBVFVTX0ZBSUxFRBAIYgZwcm90bzM", [file_google_protobuf_struct, file_google_protobuf_timestamp]);

/**
 * Describes the message boxteam.browser.v1.BrowserViewport.
 * Use `create(BrowserViewportSchema)` to create a new message.
 */
export const BrowserViewportSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser, 0);

/**
 * Describes the message boxteam.browser.v1.BrowserPage.
 * Use `create(BrowserPageSchema)` to create a new message.
 */
export const BrowserPageSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser, 1);

/**
 * Describes the message boxteam.browser.v1.BrowserJsonMessage.
 * Use `create(BrowserJsonMessageSchema)` to create a new message.
 */
export const BrowserJsonMessageSchema = /*@__PURE__*/
  messageDesc(file_boxteam_browser_v1_browser, 2);

/**
 * Describes the enum boxteam.browser.v1.BrowserStatus.
 */
export const BrowserStatusSchema = /*@__PURE__*/
  enumDesc(file_boxteam_browser_v1_browser, 0);

/**
 * @generated from enum boxteam.browser.v1.BrowserStatus
 */
export const BrowserStatus = /*@__PURE__*/
  tsEnum(BrowserStatusSchema);

