// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/common/v1/error.proto (package boxteam.common.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/common/v1/error.proto.
 */
export const file_boxteam_common_v1_error = /*@__PURE__*/
  fileDesc("Ch1ib3h0ZWFtL2NvbW1vbi92MS9lcnJvci5wcm90bxIRYm94dGVhbS5jb21tb24udjEiUAoFRXJyb3ISDAoEY29kZRgBIAEoCRIPCgdtZXNzYWdlGAIgASgJEigKB2RldGFpbHMYAyABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IjMKDlJlcXVlc3RDb250ZXh0EhIKCnJlcXVlc3RfaWQYASABKAkSDQoFYWN0b3IYAiABKAliBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * Describes the message boxteam.common.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema = /*@__PURE__*/
  messageDesc(file_boxteam_common_v1_error, 0);

/**
 * Describes the message boxteam.common.v1.RequestContext.
 * Use `create(RequestContextSchema)` to create a new message.
 */
export const RequestContextSchema = /*@__PURE__*/
  messageDesc(file_boxteam_common_v1_error, 1);

