// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/common/v1/service_lifecycle.proto (package boxteam.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/common/v1/service_lifecycle.proto.
 */
export declare const file_boxteam_common_v1_service_lifecycle: GenFile;

/**
 * @generated from message boxteam.common.v1.ServiceHealth
 */
export declare type ServiceHealth = Message<"boxteam.common.v1.ServiceHealth"> & {
  /**
   * @generated from field: string service_id = 1;
   */
  serviceId: string;

  /**
   * @generated from field: boxteam.common.v1.ServiceStatus status = 2;
   */
  status: ServiceStatus;

  /**
   * @generated from field: string health_path = 3;
   */
  healthPath: string;

  /**
   * @generated from field: string error = 4;
   */
  error: string;

  /**
   * @generated from field: google.protobuf.Timestamp checked_at = 5;
   */
  checkedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.common.v1.ServiceHealth.
 * Use `create(ServiceHealthSchema)` to create a new message.
 */
export declare const ServiceHealthSchema: GenMessage<ServiceHealth>;

/**
 * @generated from enum boxteam.common.v1.ServiceStatus
 */
export enum ServiceStatus {
  /**
   * @generated from enum value: SERVICE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SERVICE_STATUS_READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: SERVICE_STATUS_DEGRADED = 2;
   */
  DEGRADED = 2,

  /**
   * @generated from enum value: SERVICE_STATUS_OFFLINE = 3;
   */
  OFFLINE = 3,

  /**
   * @generated from enum value: SERVICE_STATUS_UNAVAILABLE = 4;
   */
  UNAVAILABLE = 4,
}

/**
 * Describes the enum boxteam.common.v1.ServiceStatus.
 */
export declare const ServiceStatusSchema: GenEnum<ServiceStatus>;

