// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/common/v1/service_lifecycle.proto (package boxteam.common.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/common/v1/service_lifecycle.proto.
 */
export const file_boxteam_common_v1_service_lifecycle = /*@__PURE__*/
  fileDesc("Cilib3h0ZWFtL2NvbW1vbi92MS9zZXJ2aWNlX2xpZmVjeWNsZS5wcm90bxIRYm94dGVhbS5jb21tb24udjEiqQEKDVNlcnZpY2VIZWFsdGgSEgoKc2VydmljZV9pZBgBIAEoCRIwCgZzdGF0dXMYAiABKA4yIC5ib3h0ZWFtLmNvbW1vbi52MS5TZXJ2aWNlU3RhdHVzEhMKC2hlYWx0aF9wYXRoGAMgASgJEg0KBWVycm9yGAQgASgJEi4KCmNoZWNrZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKqIBCg1TZXJ2aWNlU3RhdHVzEh4KGlNFUlZJQ0VfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUU0VSVklDRV9TVEFUVVNfUkVBRFkQARIbChdTRVJWSUNFX1NUQVRVU19ERUdSQURFRBACEhoKFlNFUlZJQ0VfU1RBVFVTX09GRkxJTkUQAxIeChpTRVJWSUNFX1NUQVRVU19VTkFWQUlMQUJMRRAEYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message boxteam.common.v1.ServiceHealth.
 * Use `create(ServiceHealthSchema)` to create a new message.
 */
export const ServiceHealthSchema = /*@__PURE__*/
  messageDesc(file_boxteam_common_v1_service_lifecycle, 0);

/**
 * Describes the enum boxteam.common.v1.ServiceStatus.
 */
export const ServiceStatusSchema = /*@__PURE__*/
  enumDesc(file_boxteam_common_v1_service_lifecycle, 0);

/**
 * @generated from enum boxteam.common.v1.ServiceStatus
 */
export const ServiceStatus = /*@__PURE__*/
  tsEnum(ServiceStatusSchema);

