// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/gateway/v1/health.proto (package boxteam.gateway.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ServiceHealth, ServiceStatus } from "../../common/v1/service_lifecycle_pb.js";

/**
 * Describes the file boxteam/gateway/v1/health.proto.
 */
export declare const file_boxteam_gateway_v1_health: GenFile;

/**
 * @generated from message boxteam.gateway.v1.GatewayHealth
 */
export declare type GatewayHealth = Message<"boxteam.gateway.v1.GatewayHealth"> & {
  /**
   * @generated from field: string gateway_id = 1;
   */
  gatewayId: string;

  /**
   * @generated from field: boxteam.common.v1.ServiceStatus status = 2;
   */
  status: ServiceStatus;

  /**
   * @generated from field: string active_workspace_id = 3;
   */
  activeWorkspaceId: string;

  /**
   * @generated from field: repeated boxteam.common.v1.ServiceHealth services = 4;
   */
  services: ServiceHealth[];

  /**
   * @generated from field: uint64 process_id = 5;
   */
  processId: bigint;

  /**
   * @generated from field: bool development_restart_available = 6;
   */
  developmentRestartAvailable: boolean;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayHealth.
 * Use `create(GatewayHealthSchema)` to create a new message.
 */
export declare const GatewayHealthSchema: GenMessage<GatewayHealth>;

