// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/gateway/v1/public.proto (package boxteam.gateway.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/gateway/v1/public.proto.
 */
export declare const file_boxteam_gateway_v1_public: GenFile;

/**
 * @generated from message boxteam.gateway.v1.AcquireGatewayUserRequest
 */
export declare type AcquireGatewayUserRequest = Message<"boxteam.gateway.v1.AcquireGatewayUserRequest"> & {
  /**
   * @generated from field: optional string client_label = 1;
   */
  clientLabel?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.AcquireGatewayUserRequest.
 * Use `create(AcquireGatewayUserRequestSchema)` to create a new message.
 */
export declare const AcquireGatewayUserRequestSchema: GenMessage<AcquireGatewayUserRequest>;

/**
 * @generated from message boxteam.gateway.v1.ActivateGatewayWorkspaceResultDTO
 */
export declare type ActivateGatewayWorkspaceResultDTO = Message<"boxteam.gateway.v1.ActivateGatewayWorkspaceResultDTO"> & {
  /**
   * @generated from field: string active_workspace_id = 1;
   */
  activeWorkspaceId: string;
};

/**
 * Describes the message boxteam.gateway.v1.ActivateGatewayWorkspaceResultDTO.
 * Use `create(ActivateGatewayWorkspaceResultDTOSchema)` to create a new message.
 */
export declare const ActivateGatewayWorkspaceResultDTOSchema: GenMessage<ActivateGatewayWorkspaceResultDTO>;

/**
 * @generated from message boxteam.gateway.v1.AddLocalWorkspaceRequest
 */
export declare type AddLocalWorkspaceRequest = Message<"boxteam.gateway.v1.AddLocalWorkspaceRequest"> & {
  /**
   * @generated from field: string root_path = 1;
   */
  rootPath: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string backend_url = 3;
   */
  backendUrl?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.AddLocalWorkspaceRequest.
 * Use `create(AddLocalWorkspaceRequestSchema)` to create a new message.
 */
export declare const AddLocalWorkspaceRequestSchema: GenMessage<AddLocalWorkspaceRequest>;

/**
 * @generated from message boxteam.gateway.v1.AddRemoteGatewayRequest
 */
export declare type AddRemoteGatewayRequest = Message<"boxteam.gateway.v1.AddRemoteGatewayRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string connection_workspace_id = 2;
   */
  connectionWorkspaceId?: string | undefined;

  /**
   * @generated from field: optional string ssh_config_host = 3;
   */
  sshConfigHost?: string | undefined;

  /**
   * @generated from field: optional string host = 4;
   */
  host?: string | undefined;

  /**
   * @generated from field: optional int64 port = 5;
   */
  port?: bigint | undefined;

  /**
   * @generated from field: optional string username = 6;
   */
  username?: string | undefined;

  /**
   * @generated from field: optional string private_key_path = 7;
   */
  privateKeyPath?: string | undefined;

  /**
   * @generated from field: optional int64 remote_gateway_port = 8;
   */
  remoteGatewayPort?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.AddRemoteGatewayRequest.
 * Use `create(AddRemoteGatewayRequestSchema)` to create a new message.
 */
export declare const AddRemoteGatewayRequestSchema: GenMessage<AddRemoteGatewayRequest>;

/**
 * @generated from message boxteam.gateway.v1.AddSshWorkspaceRequest
 */
export declare type AddSshWorkspaceRequest = Message<"boxteam.gateway.v1.AddSshWorkspaceRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string connection_workspace_id = 2;
   */
  connectionWorkspaceId?: string | undefined;

  /**
   * @generated from field: optional string ssh_config_host = 3;
   */
  sshConfigHost?: string | undefined;

  /**
   * @generated from field: optional string host = 4;
   */
  host?: string | undefined;

  /**
   * @generated from field: optional int64 port = 5;
   */
  port?: bigint | undefined;

  /**
   * @generated from field: optional string username = 6;
   */
  username?: string | undefined;

  /**
   * @generated from field: optional string private_key_path = 7;
   */
  privateKeyPath?: string | undefined;

  /**
   * @generated from field: optional int64 remote_gateway_port = 8;
   */
  remoteGatewayPort?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.AddSshWorkspaceRequest.
 * Use `create(AddSshWorkspaceRequestSchema)` to create a new message.
 */
export declare const AddSshWorkspaceRequestSchema: GenMessage<AddSshWorkspaceRequest>;

/**
 * @generated from message boxteam.gateway.v1.ChangePortForwardLabelRequest
 */
export declare type ChangePortForwardLabelRequest = Message<"boxteam.gateway.v1.ChangePortForwardLabelRequest"> & {
  /**
   * @generated from field: optional string label = 1;
   */
  label?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.ChangePortForwardLabelRequest.
 * Use `create(ChangePortForwardLabelRequestSchema)` to create a new message.
 */
export declare const ChangePortForwardLabelRequestSchema: GenMessage<ChangePortForwardLabelRequest>;

/**
 * @generated from message boxteam.gateway.v1.ChangePortForwardLocalPortRequest
 */
export declare type ChangePortForwardLocalPortRequest = Message<"boxteam.gateway.v1.ChangePortForwardLocalPortRequest"> & {
  /**
   * @generated from field: int64 local_port = 1;
   */
  localPort: bigint;
};

/**
 * Describes the message boxteam.gateway.v1.ChangePortForwardLocalPortRequest.
 * Use `create(ChangePortForwardLocalPortRequestSchema)` to create a new message.
 */
export declare const ChangePortForwardLocalPortRequestSchema: GenMessage<ChangePortForwardLocalPortRequest>;

/**
 * @generated from message boxteam.gateway.v1.CreateFederationManagedWorkspaceRequest
 */
export declare type CreateFederationManagedWorkspaceRequest = Message<"boxteam.gateway.v1.CreateFederationManagedWorkspaceRequest"> & {
  /**
   * @generated from field: string root_path = 1;
   */
  rootPath: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional bool create_directory = 3;
   */
  createDirectory?: boolean | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.CreateFederationManagedWorkspaceRequest.
 * Use `create(CreateFederationManagedWorkspaceRequestSchema)` to create a new message.
 */
export declare const CreateFederationManagedWorkspaceRequestSchema: GenMessage<CreateFederationManagedWorkspaceRequest>;

/**
 * @generated from message boxteam.gateway.v1.CreateGatewayGuestRequest
 */
export declare type CreateGatewayGuestRequest = Message<"boxteam.gateway.v1.CreateGatewayGuestRequest"> & {
  /**
   * @generated from field: optional google.protobuf.Struct tracking = 1;
   */
  tracking?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.CreateGatewayGuestRequest.
 * Use `create(CreateGatewayGuestRequestSchema)` to create a new message.
 */
export declare const CreateGatewayGuestRequestSchema: GenMessage<CreateGatewayGuestRequest>;

/**
 * @generated from message boxteam.gateway.v1.CreateGatewayManagedWorkspaceRequest
 */
export declare type CreateGatewayManagedWorkspaceRequest = Message<"boxteam.gateway.v1.CreateGatewayManagedWorkspaceRequest"> & {
  /**
   * @generated from field: string root_path = 1;
   */
  rootPath: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional bool create_directory = 3;
   */
  createDirectory?: boolean | undefined;

  /**
   * @generated from field: optional string gateway_connection_id = 4;
   */
  gatewayConnectionId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.CreateGatewayManagedWorkspaceRequest.
 * Use `create(CreateGatewayManagedWorkspaceRequestSchema)` to create a new message.
 */
export declare const CreateGatewayManagedWorkspaceRequestSchema: GenMessage<CreateGatewayManagedWorkspaceRequest>;

/**
 * @generated from message boxteam.gateway.v1.CreateGatewayUserRequest
 */
export declare type CreateGatewayUserRequest = Message<"boxteam.gateway.v1.CreateGatewayUserRequest"> & {
  /**
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * @generated from field: optional string user_id = 2;
   */
  userId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.CreateGatewayUserRequest.
 * Use `create(CreateGatewayUserRequestSchema)` to create a new message.
 */
export declare const CreateGatewayUserRequestSchema: GenMessage<CreateGatewayUserRequest>;

/**
 * @generated from message boxteam.gateway.v1.CreatePortForwardRequest
 */
export declare type CreatePortForwardRequest = Message<"boxteam.gateway.v1.CreatePortForwardRequest"> & {
  /**
   * @generated from field: int64 remote_port = 1;
   */
  remotePort: bigint;

  /**
   * @generated from field: optional int64 local_port = 2;
   */
  localPort?: bigint | undefined;

  /**
   * @generated from field: optional string protocol = 3;
   */
  protocol?: string | undefined;

  /**
   * @generated from field: optional string label = 4;
   */
  label?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.CreatePortForwardRequest.
 * Use `create(CreatePortForwardRequestSchema)` to create a new message.
 */
export declare const CreatePortForwardRequestSchema: GenMessage<CreatePortForwardRequest>;

/**
 * @generated from message boxteam.gateway.v1.DevelopmentRuntimeRestartDTO
 */
export declare type DevelopmentRuntimeRestartDTO = Message<"boxteam.gateway.v1.DevelopmentRuntimeRestartDTO"> & {
  /**
   * @generated from field: optional string status = 1;
   */
  status?: string | undefined;

  /**
   * @generated from field: int64 previous_process_id = 2;
   */
  previousProcessId: bigint;

  /**
   * @generated from field: int64 helper_process_id = 3;
   */
  helperProcessId: bigint;

  /**
   * @generated from field: int64 delay_ms = 4;
   */
  delayMs: bigint;
};

/**
 * Describes the message boxteam.gateway.v1.DevelopmentRuntimeRestartDTO.
 * Use `create(DevelopmentRuntimeRestartDTOSchema)` to create a new message.
 */
export declare const DevelopmentRuntimeRestartDTOSchema: GenMessage<DevelopmentRuntimeRestartDTO>;

/**
 * @generated from message boxteam.gateway.v1.FederationProtocolManifestDTO
 */
export declare type FederationProtocolManifestDTO = Message<"boxteam.gateway.v1.FederationProtocolManifestDTO"> & {
  /**
   * @generated from field: int64 protocol_version = 1;
   */
  protocolVersion: bigint;

  /**
   * @generated from field: string gateway_id = 2;
   */
  gatewayId: string;

  /**
   * @generated from field: optional int64 federation_depth = 3;
   */
  federationDepth?: bigint | undefined;

  /**
   * @generated from field: repeated string capabilities = 4;
   */
  capabilities: string[];
};

/**
 * Describes the message boxteam.gateway.v1.FederationProtocolManifestDTO.
 * Use `create(FederationProtocolManifestDTOSchema)` to create a new message.
 */
export declare const FederationProtocolManifestDTOSchema: GenMessage<FederationProtocolManifestDTO>;

/**
 * @generated from message boxteam.gateway.v1.FederationWorkspaceDTO
 */
export declare type FederationWorkspaceDTO = Message<"boxteam.gateway.v1.FederationWorkspaceDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string root_path = 3;
   */
  rootPath: string;

  /**
   * @generated from field: bool managed = 4;
   */
  managed: boolean;

  /**
   * @generated from field: string connection_kind = 5;
   */
  connectionKind: string;

  /**
   * @generated from field: repeated string services = 6;
   */
  services: string[];
};

/**
 * Describes the message boxteam.gateway.v1.FederationWorkspaceDTO.
 * Use `create(FederationWorkspaceDTOSchema)` to create a new message.
 */
export declare const FederationWorkspaceDTOSchema: GenMessage<FederationWorkspaceDTO>;

/**
 * @generated from message boxteam.gateway.v1.FederationWorkspaceListDTO
 */
export declare type FederationWorkspaceListDTO = Message<"boxteam.gateway.v1.FederationWorkspaceListDTO"> & {
  /**
   * @generated from field: int64 protocol_version = 1;
   */
  protocolVersion: bigint;

  /**
   * @generated from field: string gateway_id = 2;
   */
  gatewayId: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.FederationWorkspaceDTO items = 3;
   */
  items: FederationWorkspaceDTO[];

  /**
   * @generated from field: repeated string excluded = 4;
   */
  excluded: string[];
};

/**
 * Describes the message boxteam.gateway.v1.FederationWorkspaceListDTO.
 * Use `create(FederationWorkspaceListDTOSchema)` to create a new message.
 */
export declare const FederationWorkspaceListDTOSchema: GenMessage<FederationWorkspaceListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayConfigReloadStatusDTO
 */
export declare type GatewayConfigReloadStatusDTO = Message<"boxteam.gateway.v1.GatewayConfigReloadStatusDTO"> & {
  /**
   * @generated from field: optional bool available = 1;
   */
  available?: boolean | undefined;

  /**
   * @generated from field: optional bool healthy = 2;
   */
  healthy?: boolean | undefined;

  /**
   * @generated from field: optional string revision = 3;
   */
  revision?: string | undefined;

  /**
   * @generated from field: optional bool restart_required = 4;
   */
  restartRequired?: boolean | undefined;

  /**
   * @generated from field: optional string reason = 5;
   */
  reason?: string | undefined;

  /**
   * @generated from field: repeated string changed_sections = 6;
   */
  changedSections: string[];

  /**
   * @generated from field: optional string last_error = 7;
   */
  lastError?: string | undefined;

  /**
   * @generated from field: optional string error = 8;
   */
  error?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayConfigReloadStatusDTO.
 * Use `create(GatewayConfigReloadStatusDTOSchema)` to create a new message.
 */
export declare const GatewayConfigReloadStatusDTOSchema: GenMessage<GatewayConfigReloadStatusDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayConfigSourceDTO
 */
export declare type GatewayConfigSourceDTO = Message<"boxteam.gateway.v1.GatewayConfigSourceDTO"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string layer = 2;
   */
  layer: string;

  /**
   * @generated from field: int64 precedence = 3;
   */
  precedence: bigint;

  /**
   * @generated from field: bool loaded = 4;
   */
  loaded: boolean;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayConfigSourceDTO.
 * Use `create(GatewayConfigSourceDTOSchema)` to create a new message.
 */
export declare const GatewayConfigSourceDTOSchema: GenMessage<GatewayConfigSourceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayConfigSourcesDTO
 */
export declare type GatewayConfigSourcesDTO = Message<"boxteam.gateway.v1.GatewayConfigSourcesDTO"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;

  /**
   * @generated from field: string schema_path = 2;
   */
  schemaPath: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayConfigSourceDTO sources = 3;
   */
  sources: GatewayConfigSourceDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayConfigSourcesDTO.
 * Use `create(GatewayConfigSourcesDTOSchema)` to create a new message.
 */
export declare const GatewayConfigSourcesDTOSchema: GenMessage<GatewayConfigSourcesDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayDiagnosticLogDTO
 */
export declare type GatewayDiagnosticLogDTO = Message<"boxteam.gateway.v1.GatewayDiagnosticLogDTO"> & {
  /**
   * @generated from field: string log_id = 1;
   */
  logId: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: optional string workspace_id = 3;
   */
  workspaceId?: string | undefined;

  /**
   * @generated from field: optional string workspace_name = 4;
   */
  workspaceName?: string | undefined;

  /**
   * @generated from field: string service = 5;
   */
  service: string;

  /**
   * @generated from field: string label = 6;
   */
  label: string;

  /**
   * @generated from field: string status = 7;
   */
  status: string;

  /**
   * @generated from field: optional string tail = 8;
   */
  tail?: string | undefined;

  /**
   * @generated from field: optional bool truncated = 9;
   */
  truncated?: boolean | undefined;

  /**
   * @generated from field: optional int64 line_count = 10;
   */
  lineCount?: bigint | undefined;

  /**
   * @generated from field: optional int64 size_bytes = 11;
   */
  sizeBytes?: bigint | undefined;

  /**
   * @generated from field: optional string updated_at = 12;
   */
  updatedAt?: string | undefined;

  /**
   * @generated from field: optional string error = 13;
   */
  error?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayDiagnosticLogDTO.
 * Use `create(GatewayDiagnosticLogDTOSchema)` to create a new message.
 */
export declare const GatewayDiagnosticLogDTOSchema: GenMessage<GatewayDiagnosticLogDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayDiagnosticWorkspaceDTO
 */
export declare type GatewayDiagnosticWorkspaceDTO = Message<"boxteam.gateway.v1.GatewayDiagnosticWorkspaceDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string root_path = 3;
   */
  rootPath: string;

  /**
   * @generated from field: string connection_kind = 4;
   */
  connectionKind: string;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: bool managed = 6;
   */
  managed: boolean;

  /**
   * @generated from field: bool system_default = 7;
   */
  systemDefault: boolean;

  /**
   * @generated from field: optional string connection_error = 8;
   */
  connectionError?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayDiagnosticWorkspaceDTO.
 * Use `create(GatewayDiagnosticWorkspaceDTOSchema)` to create a new message.
 */
export declare const GatewayDiagnosticWorkspaceDTOSchema: GenMessage<GatewayDiagnosticWorkspaceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayDiagnosticsDTO
 */
export declare type GatewayDiagnosticsDTO = Message<"boxteam.gateway.v1.GatewayDiagnosticsDTO"> & {
  /**
   * @generated from field: string gateway_id = 1;
   */
  gatewayId: string;

  /**
   * @generated from field: string gateway_name = 2;
   */
  gatewayName: string;

  /**
   * @generated from field: optional string gateway_connection_id = 3;
   */
  gatewayConnectionId?: string | undefined;

  /**
   * @generated from field: string connection_kind = 4;
   */
  connectionKind: string;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: string checked_at = 6;
   */
  checkedAt: string;

  /**
   * @generated from field: optional string selected_workspace_id = 7;
   */
  selectedWorkspaceId?: string | undefined;

  /**
   * @generated from field: optional string selected_log_id = 8;
   */
  selectedLogId?: string | undefined;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayDiagnosticWorkspaceDTO workspaces = 9;
   */
  workspaces: GatewayDiagnosticWorkspaceDTO[];

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayDiagnosticLogDTO logs = 10;
   */
  logs: GatewayDiagnosticLogDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayDiagnosticsDTO.
 * Use `create(GatewayDiagnosticsDTOSchema)` to create a new message.
 */
export declare const GatewayDiagnosticsDTOSchema: GenMessage<GatewayDiagnosticsDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayDirectoryEntryDTO
 */
export declare type GatewayDirectoryEntryDTO = Message<"boxteam.gateway.v1.GatewayDirectoryEntryDTO"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayDirectoryEntryDTO.
 * Use `create(GatewayDirectoryEntryDTOSchema)` to create a new message.
 */
export declare const GatewayDirectoryEntryDTOSchema: GenMessage<GatewayDirectoryEntryDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayDirectoryListDTO
 */
export declare type GatewayDirectoryListDTO = Message<"boxteam.gateway.v1.GatewayDirectoryListDTO"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: optional string parent_path = 2;
   */
  parentPath?: string | undefined;

  /**
   * @generated from field: string home_path = 3;
   */
  homePath: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayDirectoryEntryDTO entries = 4;
   */
  entries: GatewayDirectoryEntryDTO[];

  /**
   * @generated from field: optional bool truncated = 5;
   */
  truncated?: boolean | undefined;

  /**
   * @generated from field: int64 limit = 6;
   */
  limit: bigint;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayDirectoryListDTO.
 * Use `create(GatewayDirectoryListDTOSchema)` to create a new message.
 */
export declare const GatewayDirectoryListDTOSchema: GenMessage<GatewayDirectoryListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayHealthDTO
 */
export declare type GatewayHealthDTO = Message<"boxteam.gateway.v1.GatewayHealthDTO"> & {
  /**
   * @generated from field: optional string status = 1;
   */
  status?: string | undefined;

  /**
   * @generated from field: optional string active_workspace_id = 2;
   */
  activeWorkspaceId?: string | undefined;

  /**
   * @generated from field: int64 process_id = 3;
   */
  processId: bigint;

  /**
   * @generated from field: optional bool development_restart_available = 4;
   */
  developmentRestartAvailable?: boolean | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayHealthDTO.
 * Use `create(GatewayHealthDTOSchema)` to create a new message.
 */
export declare const GatewayHealthDTOSchema: GenMessage<GatewayHealthDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayInboundAccessListDTO
 */
export declare type GatewayInboundAccessListDTO = Message<"boxteam.gateway.v1.GatewayInboundAccessListDTO"> & {
  /**
   * @generated from field: string gateway_id = 1;
   */
  gatewayId: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayInboundPeerDTO peers = 2;
   */
  peers: GatewayInboundPeerDTO[];

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayInboundWorkspaceDTO items = 3;
   */
  items: GatewayInboundWorkspaceDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayInboundAccessListDTO.
 * Use `create(GatewayInboundAccessListDTOSchema)` to create a new message.
 */
export declare const GatewayInboundAccessListDTOSchema: GenMessage<GatewayInboundAccessListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayInboundPeerDTO
 */
export declare type GatewayInboundPeerDTO = Message<"boxteam.gateway.v1.GatewayInboundPeerDTO"> & {
  /**
   * @generated from field: string connection_id = 1;
   */
  connectionId: string;

  /**
   * @generated from field: string peer_gateway_id = 2;
   */
  peerGatewayId: string;

  /**
   * @generated from field: string credential_expires_at = 3;
   */
  credentialExpiresAt: string;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayInboundPeerDTO.
 * Use `create(GatewayInboundPeerDTOSchema)` to create a new message.
 */
export declare const GatewayInboundPeerDTOSchema: GenMessage<GatewayInboundPeerDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayInboundWorkspaceDTO
 */
export declare type GatewayInboundWorkspaceDTO = Message<"boxteam.gateway.v1.GatewayInboundWorkspaceDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string root_path = 3;
   */
  rootPath: string;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: bool managed = 5;
   */
  managed: boolean;

  /**
   * @generated from field: bool system_default = 6;
   */
  systemDefault: boolean;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayInboundWorkspaceDTO.
 * Use `create(GatewayInboundWorkspaceDTOSchema)` to create a new message.
 */
export declare const GatewayInboundWorkspaceDTOSchema: GenMessage<GatewayInboundWorkspaceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayManagedWorkspaceDTO
 */
export declare type GatewayManagedWorkspaceDTO = Message<"boxteam.gateway.v1.GatewayManagedWorkspaceDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string root_path = 3;
   */
  rootPath: string;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: bool removable = 5;
   */
  removable: boolean;

  /**
   * @generated from field: bool system_default = 6;
   */
  systemDefault: boolean;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayManagedWorkspaceDTO.
 * Use `create(GatewayManagedWorkspaceDTOSchema)` to create a new message.
 */
export declare const GatewayManagedWorkspaceDTOSchema: GenMessage<GatewayManagedWorkspaceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayManagedWorkspaceListDTO
 */
export declare type GatewayManagedWorkspaceListDTO = Message<"boxteam.gateway.v1.GatewayManagedWorkspaceListDTO"> & {
  /**
   * @generated from field: optional string gateway_connection_id = 1;
   */
  gatewayConnectionId?: string | undefined;

  /**
   * @generated from field: string gateway_id = 2;
   */
  gatewayId: string;

  /**
   * @generated from field: string gateway_name = 3;
   */
  gatewayName: string;

  /**
   * @generated from field: string connection_kind = 4;
   */
  connectionKind: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayManagedWorkspaceDTO items = 5;
   */
  items: GatewayManagedWorkspaceDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayManagedWorkspaceListDTO.
 * Use `create(GatewayManagedWorkspaceListDTOSchema)` to create a new message.
 */
export declare const GatewayManagedWorkspaceListDTOSchema: GenMessage<GatewayManagedWorkspaceListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayRemoteConnectionSummaryDTO
 */
export declare type GatewayRemoteConnectionSummaryDTO = Message<"boxteam.gateway.v1.GatewayRemoteConnectionSummaryDTO"> & {
  /**
   * @generated from field: string gateway_connection_id = 1;
   */
  gatewayConnectionId: string;

  /**
   * @generated from field: string remote_workspace_id = 2;
   */
  remoteWorkspaceId: string;

  /**
   * @generated from field: string gateway_id = 3;
   */
  gatewayId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string host = 5;
   */
  host: string;

  /**
   * @generated from field: int64 port = 6;
   */
  port: bigint;

  /**
   * @generated from field: string username = 7;
   */
  username: string;

  /**
   * @generated from field: optional string ssh_config_host = 8;
   */
  sshConfigHost?: string | undefined;

  /**
   * @generated from field: int64 remote_gateway_port = 9;
   */
  remoteGatewayPort: bigint;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayRemoteConnectionSummaryDTO.
 * Use `create(GatewayRemoteConnectionSummaryDTOSchema)` to create a new message.
 */
export declare const GatewayRemoteConnectionSummaryDTOSchema: GenMessage<GatewayRemoteConnectionSummaryDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayResourceDTO
 */
export declare type GatewayResourceDTO = Message<"boxteam.gateway.v1.GatewayResourceDTO"> & {
  /**
   * @generated from field: optional string gateway_connection_id = 1;
   */
  gatewayConnectionId?: string | undefined;

  /**
   * @generated from field: string gateway_name = 2;
   */
  gatewayName: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string workspace_name = 4;
   */
  workspaceName: string;

  /**
   * @generated from field: string connection_kind = 5;
   */
  connectionKind: string;

  /**
   * @generated from field: string session_id = 6;
   */
  sessionId: string;

  /**
   * @generated from field: string session_title = 7;
   */
  sessionTitle: string;

  /**
   * @generated from field: google.protobuf.Struct resource = 8;
   */
  resource?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayResourceDTO.
 * Use `create(GatewayResourceDTOSchema)` to create a new message.
 */
export declare const GatewayResourceDTOSchema: GenMessage<GatewayResourceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayResourceListDTO
 */
export declare type GatewayResourceListDTO = Message<"boxteam.gateway.v1.GatewayResourceListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayResourceDTO items = 1;
   */
  items: GatewayResourceDTO[];

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayResourceScopeErrorDTO errors = 2;
   */
  errors: GatewayResourceScopeErrorDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayResourceListDTO.
 * Use `create(GatewayResourceListDTOSchema)` to create a new message.
 */
export declare const GatewayResourceListDTOSchema: GenMessage<GatewayResourceListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayResourceScopeErrorDTO
 */
export declare type GatewayResourceScopeErrorDTO = Message<"boxteam.gateway.v1.GatewayResourceScopeErrorDTO"> & {
  /**
   * @generated from field: string scope_key = 1;
   */
  scopeKey: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayResourceScopeErrorDTO.
 * Use `create(GatewayResourceScopeErrorDTOSchema)` to create a new message.
 */
export declare const GatewayResourceScopeErrorDTOSchema: GenMessage<GatewayResourceScopeErrorDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayRuntimeBlockerDTO
 */
export declare type GatewayRuntimeBlockerDTO = Message<"boxteam.gateway.v1.GatewayRuntimeBlockerDTO"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: string resource_id = 2;
   */
  resourceId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: optional string detail = 5;
   */
  detail?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayRuntimeBlockerDTO.
 * Use `create(GatewayRuntimeBlockerDTOSchema)` to create a new message.
 */
export declare const GatewayRuntimeBlockerDTOSchema: GenMessage<GatewayRuntimeBlockerDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayRuntimeRestartResultDTO
 */
export declare type GatewayRuntimeRestartResultDTO = Message<"boxteam.gateway.v1.GatewayRuntimeRestartResultDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: bool forced = 3;
   */
  forced: boolean;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayRuntimeBlockerDTO blockers = 4;
   */
  blockers: GatewayRuntimeBlockerDTO[];

  /**
   * @generated from field: boxteam.gateway.v1.GatewayWorkspaceListDTO workspaces = 5;
   */
  workspaces?: GatewayWorkspaceListDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayRuntimeRestartResultDTO.
 * Use `create(GatewayRuntimeRestartResultDTOSchema)` to create a new message.
 */
export declare const GatewayRuntimeRestartResultDTOSchema: GenMessage<GatewayRuntimeRestartResultDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayRuntimeStateResultDTO
 */
export declare type GatewayRuntimeStateResultDTO = Message<"boxteam.gateway.v1.GatewayRuntimeStateResultDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayRuntimeBlockerDTO blockers = 3;
   */
  blockers: GatewayRuntimeBlockerDTO[];

  /**
   * @generated from field: boxteam.gateway.v1.GatewayWorkspaceListDTO workspaces = 4;
   */
  workspaces?: GatewayWorkspaceListDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayRuntimeStateResultDTO.
 * Use `create(GatewayRuntimeStateResultDTOSchema)` to create a new message.
 */
export declare const GatewayRuntimeStateResultDTOSchema: GenMessage<GatewayRuntimeStateResultDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayServiceStatusDTO
 */
export declare type GatewayServiceStatusDTO = Message<"boxteam.gateway.v1.GatewayServiceStatusDTO"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: string health_path = 2;
   */
  healthPath: string;

  /**
   * @generated from field: optional string local_url = 3;
   */
  localUrl?: string | undefined;

  /**
   * @generated from field: optional int64 local_port = 4;
   */
  localPort?: bigint | undefined;

  /**
   * @generated from field: optional string remote_host = 5;
   */
  remoteHost?: string | undefined;

  /**
   * @generated from field: optional int64 remote_port = 6;
   */
  remotePort?: bigint | undefined;

  /**
   * @generated from field: optional string error = 7;
   */
  error?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayServiceStatusDTO.
 * Use `create(GatewayServiceStatusDTOSchema)` to create a new message.
 */
export declare const GatewayServiceStatusDTOSchema: GenMessage<GatewayServiceStatusDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewaySessionSearchMatchDTO
 */
export declare type GatewaySessionSearchMatchDTO = Message<"boxteam.gateway.v1.GatewaySessionSearchMatchDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string workspace_name = 2;
   */
  workspaceName: string;

  /**
   * @generated from field: string node_id = 3;
   */
  nodeId: string;

  /**
   * @generated from field: string node_kind = 4;
   */
  nodeKind: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: optional string session_id = 6;
   */
  sessionId?: string | undefined;

  /**
   * @generated from field: string relative_path = 7;
   */
  relativePath: string;

  /**
   * @generated from field: optional string storage_relative_path = 8;
   */
  storageRelativePath?: string | undefined;

  /**
   * @generated from field: repeated string breadcrumb_names = 9;
   */
  breadcrumbNames: string[];

  /**
   * @generated from field: repeated string breadcrumb_node_ids = 10;
   */
  breadcrumbNodeIds: string[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewaySessionSearchMatchDTO.
 * Use `create(GatewaySessionSearchMatchDTOSchema)` to create a new message.
 */
export declare const GatewaySessionSearchMatchDTOSchema: GenMessage<GatewaySessionSearchMatchDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewaySessionSearchResultsDTO
 */
export declare type GatewaySessionSearchResultsDTO = Message<"boxteam.gateway.v1.GatewaySessionSearchResultsDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewaySessionSearchMatchDTO items = 1;
   */
  items: GatewaySessionSearchMatchDTO[];

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewaySessionSearchWorkspaceStatusDTO workspaces = 2;
   */
  workspaces: GatewaySessionSearchWorkspaceStatusDTO[];

  /**
   * @generated from field: optional int64 total = 3;
   */
  total?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewaySessionSearchResultsDTO.
 * Use `create(GatewaySessionSearchResultsDTOSchema)` to create a new message.
 */
export declare const GatewaySessionSearchResultsDTOSchema: GenMessage<GatewaySessionSearchResultsDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewaySessionSearchWorkspaceStatusDTO
 */
export declare type GatewaySessionSearchWorkspaceStatusDTO = Message<"boxteam.gateway.v1.GatewaySessionSearchWorkspaceStatusDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string workspace_name = 2;
   */
  workspaceName: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: optional string error = 4;
   */
  error?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewaySessionSearchWorkspaceStatusDTO.
 * Use `create(GatewaySessionSearchWorkspaceStatusDTOSchema)` to create a new message.
 */
export declare const GatewaySessionSearchWorkspaceStatusDTOSchema: GenMessage<GatewaySessionSearchWorkspaceStatusDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayThemeBackgroundDTO
 */
export declare type GatewayThemeBackgroundDTO = Message<"boxteam.gateway.v1.GatewayThemeBackgroundDTO"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: optional string url = 2;
   */
  url?: string | undefined;

  /**
   * @generated from field: optional string asset_id = 3;
   */
  assetId?: string | undefined;

  /**
   * @generated from field: optional string position = 4;
   */
  position?: string | undefined;

  /**
   * @generated from field: optional string size = 5;
   */
  size?: string | undefined;

  /**
   * @generated from field: optional string repeat = 6;
   */
  repeat?: string | undefined;

  /**
   * @generated from field: optional string appearance = 7;
   */
  appearance?: string | undefined;

  /**
   * @generated from field: optional string overlay = 8;
   */
  overlay?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayThemeBackgroundDTO.
 * Use `create(GatewayThemeBackgroundDTOSchema)` to create a new message.
 */
export declare const GatewayThemeBackgroundDTOSchema: GenMessage<GatewayThemeBackgroundDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayThemeCatalogDTO
 */
export declare type GatewayThemeCatalogDTO = Message<"boxteam.gateway.v1.GatewayThemeCatalogDTO"> & {
  /**
   * @generated from field: string current_theme_id = 1;
   */
  currentThemeId: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayThemeOptionDTO items = 2;
   */
  items: GatewayThemeOptionDTO[];

  /**
   * @generated from field: boxteam.gateway.v1.ResolvedGatewayThemeDTO current_theme = 3;
   */
  currentTheme?: ResolvedGatewayThemeDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayThemeCatalogDTO.
 * Use `create(GatewayThemeCatalogDTOSchema)` to create a new message.
 */
export declare const GatewayThemeCatalogDTOSchema: GenMessage<GatewayThemeCatalogDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayThemeOptionDTO
 */
export declare type GatewayThemeOptionDTO = Message<"boxteam.gateway.v1.GatewayThemeOptionDTO"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string extends = 3;
   */
  extends: string;

  /**
   * @generated from field: string source = 4;
   */
  source: string;

  /**
   * @generated from field: google.protobuf.Struct preview_tokens = 5;
   */
  previewTokens?: JsonObject | undefined;

  /**
   * @generated from field: optional string background_image_url = 6;
   */
  backgroundImageUrl?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayThemeOptionDTO.
 * Use `create(GatewayThemeOptionDTOSchema)` to create a new message.
 */
export declare const GatewayThemeOptionDTOSchema: GenMessage<GatewayThemeOptionDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUIAssetDTO
 */
export declare type GatewayUIAssetDTO = Message<"boxteam.gateway.v1.GatewayUIAssetDTO"> & {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId: string;

  /**
   * @generated from field: string original_filename = 2;
   */
  originalFilename: string;

  /**
   * @generated from field: string content_type = 3;
   */
  contentType: string;

  /**
   * @generated from field: int64 size = 4;
   */
  size: bigint;

  /**
   * @generated from field: string sha256 = 5;
   */
  sha256: string;

  /**
   * @generated from field: string imported_at = 6;
   */
  importedAt: string;

  /**
   * @generated from field: string url = 7;
   */
  url: string;

  /**
   * @generated from field: repeated string referenced_theme_ids = 8;
   */
  referencedThemeIds: string[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUIAssetDTO.
 * Use `create(GatewayUIAssetDTOSchema)` to create a new message.
 */
export declare const GatewayUIAssetDTOSchema: GenMessage<GatewayUIAssetDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUIAssetListDTO
 */
export declare type GatewayUIAssetListDTO = Message<"boxteam.gateway.v1.GatewayUIAssetListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayUIAssetDTO items = 1;
   */
  items: GatewayUIAssetDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUIAssetListDTO.
 * Use `create(GatewayUIAssetListDTOSchema)` to create a new message.
 */
export declare const GatewayUIAssetListDTOSchema: GenMessage<GatewayUIAssetListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserAccessDTO
 */
export declare type GatewayUserAccessDTO = Message<"boxteam.gateway.v1.GatewayUserAccessDTO"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: optional string user_id = 2;
   */
  userId?: string | undefined;

  /**
   * @generated from field: int64 lease_generation = 3;
   */
  leaseGeneration: bigint;

  /**
   * @generated from field: optional string expires_at = 4;
   */
  expiresAt?: string | undefined;

  /**
   * @generated from field: optional bool takeover = 5;
   */
  takeover?: boolean | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserAccessDTO.
 * Use `create(GatewayUserAccessDTOSchema)` to create a new message.
 */
export declare const GatewayUserAccessDTOSchema: GenMessage<GatewayUserAccessDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserDTO
 */
export declare type GatewayUserDTO = Message<"boxteam.gateway.v1.GatewayUserDTO"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string created_at = 3;
   */
  createdAt: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GatewayUserLeaseDTO lease = 4;
   */
  lease?: GatewayUserLeaseDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserDTO.
 * Use `create(GatewayUserDTOSchema)` to create a new message.
 */
export declare const GatewayUserDTOSchema: GenMessage<GatewayUserDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserLeaseDTO
 */
export declare type GatewayUserLeaseDTO = Message<"boxteam.gateway.v1.GatewayUserLeaseDTO"> & {
  /**
   * @generated from field: optional bool occupied = 1;
   */
  occupied?: boolean | undefined;

  /**
   * @generated from field: optional string client_label = 2;
   */
  clientLabel?: string | undefined;

  /**
   * @generated from field: optional string heartbeat_at = 3;
   */
  heartbeatAt?: string | undefined;

  /**
   * @generated from field: optional string expires_at = 4;
   */
  expiresAt?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserLeaseDTO.
 * Use `create(GatewayUserLeaseDTOSchema)` to create a new message.
 */
export declare const GatewayUserLeaseDTOSchema: GenMessage<GatewayUserLeaseDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserListDTO
 */
export declare type GatewayUserListDTO = Message<"boxteam.gateway.v1.GatewayUserListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayUserDTO items = 1;
   */
  items: GatewayUserDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserListDTO.
 * Use `create(GatewayUserListDTOSchema)` to create a new message.
 */
export declare const GatewayUserListDTOSchema: GenMessage<GatewayUserListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserViewStateDTO
 */
export declare type GatewayUserViewStateDTO = Message<"boxteam.gateway.v1.GatewayUserViewStateDTO"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: optional string turn_anchor = 4;
   */
  turnAnchor?: string | undefined;

  /**
   * @generated from field: double scroll_offset = 5;
   */
  scrollOffset: number;

  /**
   * @generated from field: optional bool follow_latest = 6;
   */
  followLatest?: boolean | undefined;

  /**
   * @generated from field: int64 projection_version = 7;
   */
  projectionVersion: bigint;

  /**
   * @generated from field: optional bool tool_details_expanded = 8;
   */
  toolDetailsExpanded?: boolean | undefined;

  /**
   * @generated from field: string updated_at = 9;
   */
  updatedAt: string;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserViewStateDTO.
 * Use `create(GatewayUserViewStateDTOSchema)` to create a new message.
 */
export declare const GatewayUserViewStateDTOSchema: GenMessage<GatewayUserViewStateDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayUserViewStateUpdateRequest
 */
export declare type GatewayUserViewStateUpdateRequest = Message<"boxteam.gateway.v1.GatewayUserViewStateUpdateRequest"> & {
  /**
   * @generated from field: optional string turn_anchor = 1;
   */
  turnAnchor?: string | undefined;

  /**
   * @generated from field: optional double scroll_offset = 2;
   */
  scrollOffset?: number | undefined;

  /**
   * @generated from field: optional bool follow_latest = 3;
   */
  followLatest?: boolean | undefined;

  /**
   * @generated from field: optional int64 projection_version = 4;
   */
  projectionVersion?: bigint | undefined;

  /**
   * @generated from field: optional bool tool_details_expanded = 5;
   */
  toolDetailsExpanded?: boolean | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayUserViewStateUpdateRequest.
 * Use `create(GatewayUserViewStateUpdateRequestSchema)` to create a new message.
 */
export declare const GatewayUserViewStateUpdateRequestSchema: GenMessage<GatewayUserViewStateUpdateRequest>;

/**
 * @generated from message boxteam.gateway.v1.GatewayWorkspaceDTO
 */
export declare type GatewayWorkspaceDTO = Message<"boxteam.gateway.v1.GatewayWorkspaceDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: optional string parent_workspace_id = 2;
   */
  parentWorkspaceId?: string | undefined;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string root_path = 4;
   */
  rootPath: string;

  /**
   * @generated from field: string backend_url = 5;
   */
  backendUrl: string;

  /**
   * @generated from field: string connection_kind = 6;
   */
  connectionKind: string;

  /**
   * @generated from field: string status = 7;
   */
  status: string;

  /**
   * @generated from field: optional bool active = 8;
   */
  active?: boolean | undefined;

  /**
   * @generated from field: optional bool managed = 9;
   */
  managed?: boolean | undefined;

  /**
   * @generated from field: optional bool removable = 10;
   */
  removable?: boolean | undefined;

  /**
   * @generated from field: optional bool system_default = 11;
   */
  systemDefault?: boolean | undefined;

  /**
   * @generated from field: string runtime_action = 12;
   */
  runtimeAction: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GatewayConfigReloadStatusDTO config_reload = 13;
   */
  configReload?: GatewayConfigReloadStatusDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GatewayRemoteConnectionSummaryDTO remote = 14;
   */
  remote?: GatewayRemoteConnectionSummaryDTO | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct services = 15;
   */
  services?: JsonObject | undefined;

  /**
   * @generated from field: optional string connection_error = 16;
   */
  connectionError?: string | undefined;

  /**
   * @generated from field: string checked_at = 17;
   */
  checkedAt: string;
};

/**
 * Describes the message boxteam.gateway.v1.GatewayWorkspaceDTO.
 * Use `create(GatewayWorkspaceDTOSchema)` to create a new message.
 */
export declare const GatewayWorkspaceDTOSchema: GenMessage<GatewayWorkspaceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GatewayWorkspaceListDTO
 */
export declare type GatewayWorkspaceListDTO = Message<"boxteam.gateway.v1.GatewayWorkspaceListDTO"> & {
  /**
   * @generated from field: optional string active_workspace_id = 1;
   */
  activeWorkspaceId?: string | undefined;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GatewayWorkspaceDTO items = 2;
   */
  items: GatewayWorkspaceDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GatewayWorkspaceListDTO.
 * Use `create(GatewayWorkspaceListDTOSchema)` to create a new message.
 */
export declare const GatewayWorkspaceListDTOSchema: GenMessage<GatewayWorkspaceListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GenerationOutputDTO
 */
export declare type GenerationOutputDTO = Message<"boxteam.gateway.v1.GenerationOutputDTO"> & {
  /**
   * @generated from field: optional string kind = 1;
   */
  kind?: string | undefined;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: optional string title = 4;
   */
  title?: string | undefined;

  /**
   * @generated from field: repeated string navigation_path = 5;
   */
  navigationPath: string[];

  /**
   * @generated from field: optional string storage_relative_path = 6;
   */
  storageRelativePath?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GenerationOutputDTO.
 * Use `create(GenerationOutputDTOSchema)` to create a new message.
 */
export declare const GenerationOutputDTOSchema: GenMessage<GenerationOutputDTO>;

/**
 * @generated from message boxteam.gateway.v1.GenerationRunDTO
 */
export declare type GenerationRunDTO = Message<"boxteam.gateway.v1.GenerationRunDTO"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: string generator_id = 2;
   */
  generatorId: string;

  /**
   * @generated from field: string idempotency_key = 3;
   */
  idempotencyKey: string;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: string trigger_type = 5;
   */
  triggerType: string;

  /**
   * @generated from field: google.protobuf.Timestamp scheduled_for = 6;
   */
  scheduledFor?: Timestamp | undefined;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GenerationOutputDTO outputs = 7;
   */
  outputs: GenerationOutputDTO[];

  /**
   * @generated from field: optional string execution_workspace_id = 8;
   */
  executionWorkspaceId?: string | undefined;

  /**
   * @generated from field: optional string message_id = 9;
   */
  messageId?: string | undefined;

  /**
   * @generated from field: optional string job_id = 10;
   */
  jobId?: string | undefined;

  /**
   * @generated from field: optional string report_back_job_id = 11;
   */
  reportBackJobId?: string | undefined;

  /**
   * @generated from field: optional string error = 12;
   */
  error?: string | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp started_at = 13;
   */
  startedAt?: Timestamp | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp ended_at = 14;
   */
  endedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GenerationRunDTO.
 * Use `create(GenerationRunDTOSchema)` to create a new message.
 */
export declare const GenerationRunDTOSchema: GenMessage<GenerationRunDTO>;

/**
 * @generated from message boxteam.gateway.v1.GenerationRunListDTO
 */
export declare type GenerationRunListDTO = Message<"boxteam.gateway.v1.GenerationRunListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.GenerationRunDTO items = 1;
   */
  items: GenerationRunDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GenerationRunListDTO.
 * Use `create(GenerationRunListDTOSchema)` to create a new message.
 */
export declare const GenerationRunListDTOSchema: GenMessage<GenerationRunListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorContextSourceDTO
 */
export declare type GeneratorContextSourceDTO = Message<"boxteam.gateway.v1.GeneratorContextSourceDTO"> & {
  /**
   * @generated from field: optional string kind = 1;
   */
  kind?: string | undefined;

  /**
   * @generated from field: optional string workspace_id = 2;
   */
  workspaceId?: string | undefined;

  /**
   * @generated from field: optional string session_id = 3;
   */
  sessionId?: string | undefined;

  /**
   * @generated from field: optional string snapshot_id = 4;
   */
  snapshotId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorContextSourceDTO.
 * Use `create(GeneratorContextSourceDTOSchema)` to create a new message.
 */
export declare const GeneratorContextSourceDTOSchema: GenMessage<GeneratorContextSourceDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorDefinitionCreateRequest
 */
export declare type GeneratorDefinitionCreateRequest = Message<"boxteam.gateway.v1.GeneratorDefinitionCreateRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorTypeRefDTO generator_type = 2;
   */
  generatorType?: GeneratorTypeRefDTO | undefined;

  /**
   * @generated from field: optional bool enabled = 3;
   */
  enabled?: boolean | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorTriggerDTO trigger = 4;
   */
  trigger?: GeneratorTriggerDTO | undefined;

  /**
   * @generated from field: boxteam.gateway.v1.GeneratorPlacementDTO placement = 5;
   */
  placement?: GeneratorPlacementDTO | undefined;

  /**
   * @generated from field: string execution_workspace_id = 6;
   */
  executionWorkspaceId: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorContextSourceDTO context_source = 7;
   */
  contextSource?: GeneratorContextSourceDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.SessionLocatorDTO created_from = 8;
   */
  createdFrom?: SessionLocatorDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorNamingDTO naming = 9;
   */
  naming?: GeneratorNamingDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorSessionStrategyDTO session_strategy = 10;
   */
  sessionStrategy?: GeneratorSessionStrategyDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorPoliciesDTO policies = 11;
   */
  policies?: GeneratorPoliciesDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorUIPolicyDTO ui_policy = 12;
   */
  uiPolicy?: GeneratorUIPolicyDTO | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct config = 13;
   */
  config?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorDefinitionCreateRequest.
 * Use `create(GeneratorDefinitionCreateRequestSchema)` to create a new message.
 */
export declare const GeneratorDefinitionCreateRequestSchema: GenMessage<GeneratorDefinitionCreateRequest>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorDefinitionDTO
 */
export declare type GeneratorDefinitionDTO = Message<"boxteam.gateway.v1.GeneratorDefinitionDTO"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorTypeRefDTO generator_type = 2;
   */
  generatorType?: GeneratorTypeRefDTO | undefined;

  /**
   * @generated from field: optional bool enabled = 3;
   */
  enabled?: boolean | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorTriggerDTO trigger = 4;
   */
  trigger?: GeneratorTriggerDTO | undefined;

  /**
   * @generated from field: boxteam.gateway.v1.GeneratorPlacementDTO placement = 5;
   */
  placement?: GeneratorPlacementDTO | undefined;

  /**
   * @generated from field: string execution_workspace_id = 6;
   */
  executionWorkspaceId: string;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorContextSourceDTO context_source = 7;
   */
  contextSource?: GeneratorContextSourceDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.SessionLocatorDTO created_from = 8;
   */
  createdFrom?: SessionLocatorDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorNamingDTO naming = 9;
   */
  naming?: GeneratorNamingDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorSessionStrategyDTO session_strategy = 10;
   */
  sessionStrategy?: GeneratorSessionStrategyDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorPoliciesDTO policies = 11;
   */
  policies?: GeneratorPoliciesDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorUIPolicyDTO ui_policy = 12;
   */
  uiPolicy?: GeneratorUIPolicyDTO | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct config = 13;
   */
  config?: JsonObject | undefined;

  /**
   * @generated from field: string generator_id = 14;
   */
  generatorId: string;

  /**
   * @generated from field: optional string status = 15;
   */
  status?: string | undefined;

  /**
   * @generated from field: optional string status_reason = 16;
   */
  statusReason?: string | undefined;

  /**
   * @generated from field: optional int64 revision = 17;
   */
  revision?: bigint | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 18;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 19;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorDefinitionDTO.
 * Use `create(GeneratorDefinitionDTOSchema)` to create a new message.
 */
export declare const GeneratorDefinitionDTOSchema: GenMessage<GeneratorDefinitionDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorDefinitionListDTO
 */
export declare type GeneratorDefinitionListDTO = Message<"boxteam.gateway.v1.GeneratorDefinitionListDTO"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.GeneratorDefinitionDTO items = 2;
   */
  items: GeneratorDefinitionDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorDefinitionListDTO.
 * Use `create(GeneratorDefinitionListDTOSchema)` to create a new message.
 */
export declare const GeneratorDefinitionListDTOSchema: GenMessage<GeneratorDefinitionListDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorDefinitionUpdateRequest
 */
export declare type GeneratorDefinitionUpdateRequest = Message<"boxteam.gateway.v1.GeneratorDefinitionUpdateRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional bool enabled = 2;
   */
  enabled?: boolean | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorTriggerDTO trigger = 3;
   */
  trigger?: GeneratorTriggerDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorPlacementDTO placement = 4;
   */
  placement?: GeneratorPlacementDTO | undefined;

  /**
   * @generated from field: optional string execution_workspace_id = 5;
   */
  executionWorkspaceId?: string | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorContextSourceDTO context_source = 6;
   */
  contextSource?: GeneratorContextSourceDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorNamingDTO naming = 7;
   */
  naming?: GeneratorNamingDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorSessionStrategyDTO session_strategy = 8;
   */
  sessionStrategy?: GeneratorSessionStrategyDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorPoliciesDTO policies = 9;
   */
  policies?: GeneratorPoliciesDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorUIPolicyDTO ui_policy = 10;
   */
  uiPolicy?: GeneratorUIPolicyDTO | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct config = 11;
   */
  config?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorDefinitionUpdateRequest.
 * Use `create(GeneratorDefinitionUpdateRequestSchema)` to create a new message.
 */
export declare const GeneratorDefinitionUpdateRequestSchema: GenMessage<GeneratorDefinitionUpdateRequest>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorManualRunRequest
 */
export declare type GeneratorManualRunRequest = Message<"boxteam.gateway.v1.GeneratorManualRunRequest"> & {
  /**
   * @generated from field: optional string idempotency_key = 1;
   */
  idempotencyKey?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorManualRunRequest.
 * Use `create(GeneratorManualRunRequestSchema)` to create a new message.
 */
export declare const GeneratorManualRunRequestSchema: GenMessage<GeneratorManualRunRequest>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorNamingDTO
 */
export declare type GeneratorNamingDTO = Message<"boxteam.gateway.v1.GeneratorNamingDTO"> & {
  /**
   * @generated from field: optional string title_template = 1;
   */
  titleTemplate?: string | undefined;

  /**
   * @generated from field: repeated string path_template = 2;
   */
  pathTemplate: string[];
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorNamingDTO.
 * Use `create(GeneratorNamingDTOSchema)` to create a new message.
 */
export declare const GeneratorNamingDTOSchema: GenMessage<GeneratorNamingDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorPlacementDTO
 */
export declare type GeneratorPlacementDTO = Message<"boxteam.gateway.v1.GeneratorPlacementDTO"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: optional string session_id = 3;
   */
  sessionId?: string | undefined;

  /**
   * @generated from field: optional string folder_id = 4;
   */
  folderId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorPlacementDTO.
 * Use `create(GeneratorPlacementDTOSchema)` to create a new message.
 */
export declare const GeneratorPlacementDTOSchema: GenMessage<GeneratorPlacementDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorPlacementPreviewDTO
 */
export declare type GeneratorPlacementPreviewDTO = Message<"boxteam.gateway.v1.GeneratorPlacementPreviewDTO"> & {
  /**
   * @generated from field: optional string preview_kind = 1;
   */
  previewKind?: string | undefined;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated string path_segments = 3;
   */
  pathSegments: string[];

  /**
   * @generated from field: string session_path_segment = 4;
   */
  sessionPathSegment: string;

  /**
   * @generated from field: string relative_path = 5;
   */
  relativePath: string;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorPlacementPreviewDTO.
 * Use `create(GeneratorPlacementPreviewDTOSchema)` to create a new message.
 */
export declare const GeneratorPlacementPreviewDTOSchema: GenMessage<GeneratorPlacementPreviewDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorPlacementPreviewRequest
 */
export declare type GeneratorPlacementPreviewRequest = Message<"boxteam.gateway.v1.GeneratorPlacementPreviewRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: boxteam.gateway.v1.GeneratorNamingDTO naming = 2;
   */
  naming?: GeneratorNamingDTO | undefined;

  /**
   * @generated from field: optional string session_title = 3;
   */
  sessionTitle?: string | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp generated_at = 4;
   */
  generatedAt?: Timestamp | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorPlacementDTO placement = 5;
   */
  placement?: GeneratorPlacementDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GeneratorSessionStrategyDTO session_strategy = 6;
   */
  sessionStrategy?: GeneratorSessionStrategyDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorPlacementPreviewRequest.
 * Use `create(GeneratorPlacementPreviewRequestSchema)` to create a new message.
 */
export declare const GeneratorPlacementPreviewRequestSchema: GenMessage<GeneratorPlacementPreviewRequest>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorPoliciesDTO
 */
export declare type GeneratorPoliciesDTO = Message<"boxteam.gateway.v1.GeneratorPoliciesDTO"> & {
  /**
   * @generated from field: optional string overlap = 1;
   */
  overlap?: string | undefined;

  /**
   * @generated from field: optional string misfire = 2;
   */
  misfire?: string | undefined;

  /**
   * @generated from field: optional string mount_missing = 3;
   */
  mountMissing?: string | undefined;

  /**
   * @generated from field: optional string delete_outputs = 4;
   */
  deleteOutputs?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorPoliciesDTO.
 * Use `create(GeneratorPoliciesDTOSchema)` to create a new message.
 */
export declare const GeneratorPoliciesDTOSchema: GenMessage<GeneratorPoliciesDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorSessionStrategyDTO
 */
export declare type GeneratorSessionStrategyDTO = Message<"boxteam.gateway.v1.GeneratorSessionStrategyDTO"> & {
  /**
   * @generated from field: optional string mode = 1;
   */
  mode?: string | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.SessionLocatorDTO target = 2;
   */
  target?: SessionLocatorDTO | undefined;

  /**
   * @generated from field: optional string concurrency = 3;
   */
  concurrency?: string | undefined;

  /**
   * @generated from field: optional string report_back = 4;
   */
  reportBack?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorSessionStrategyDTO.
 * Use `create(GeneratorSessionStrategyDTOSchema)` to create a new message.
 */
export declare const GeneratorSessionStrategyDTOSchema: GenMessage<GeneratorSessionStrategyDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorTriggerDTO
 */
export declare type GeneratorTriggerDTO = Message<"boxteam.gateway.v1.GeneratorTriggerDTO"> & {
  /**
   * @generated from field: optional string type = 1;
   */
  type?: string | undefined;

  /**
   * @generated from field: optional string expression = 2;
   */
  expression?: string | undefined;

  /**
   * @generated from field: optional int64 interval_seconds = 3;
   */
  intervalSeconds?: bigint | undefined;

  /**
   * @generated from field: optional string timezone = 4;
   */
  timezone?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorTriggerDTO.
 * Use `create(GeneratorTriggerDTOSchema)` to create a new message.
 */
export declare const GeneratorTriggerDTOSchema: GenMessage<GeneratorTriggerDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorTypeRefDTO
 */
export declare type GeneratorTypeRefDTO = Message<"boxteam.gateway.v1.GeneratorTypeRefDTO"> & {
  /**
   * @generated from field: string type_id = 1;
   */
  typeId: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorTypeRefDTO.
 * Use `create(GeneratorTypeRefDTOSchema)` to create a new message.
 */
export declare const GeneratorTypeRefDTOSchema: GenMessage<GeneratorTypeRefDTO>;

/**
 * @generated from message boxteam.gateway.v1.GeneratorUIPolicyDTO
 */
export declare type GeneratorUIPolicyDTO = Message<"boxteam.gateway.v1.GeneratorUIPolicyDTO"> & {
  /**
   * @generated from field: optional string on_run_started = 1;
   */
  onRunStarted?: string | undefined;

  /**
   * @generated from field: optional string on_run_completed = 2;
   */
  onRunCompleted?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.GeneratorUIPolicyDTO.
 * Use `create(GeneratorUIPolicyDTOSchema)` to create a new message.
 */
export declare const GeneratorUIPolicyDTOSchema: GenMessage<GeneratorUIPolicyDTO>;

/**
 * @generated from message boxteam.gateway.v1.PortForwardDTO
 */
export declare type PortForwardDTO = Message<"boxteam.gateway.v1.PortForwardDTO"> & {
  /**
   * @generated from field: string forward_id = 1;
   */
  forwardId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string connection_id = 3;
   */
  connectionId: string;

  /**
   * @generated from field: string remote_host = 4;
   */
  remoteHost: string;

  /**
   * @generated from field: int64 remote_port = 5;
   */
  remotePort: bigint;

  /**
   * @generated from field: string local_host = 6;
   */
  localHost: string;

  /**
   * @generated from field: int64 local_port = 7;
   */
  localPort: bigint;

  /**
   * @generated from field: string protocol = 8;
   */
  protocol: string;

  /**
   * @generated from field: string label = 9;
   */
  label: string;

  /**
   * @generated from field: string status = 10;
   */
  status: string;

  /**
   * @generated from field: string error = 11;
   */
  error: string;

  /**
   * @generated from field: string local_url = 12;
   */
  localUrl: string;
};

/**
 * Describes the message boxteam.gateway.v1.PortForwardDTO.
 * Use `create(PortForwardDTOSchema)` to create a new message.
 */
export declare const PortForwardDTOSchema: GenMessage<PortForwardDTO>;

/**
 * @generated from message boxteam.gateway.v1.PortForwardListDTO
 */
export declare type PortForwardListDTO = Message<"boxteam.gateway.v1.PortForwardListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.PortForwardDTO items = 1;
   */
  items: PortForwardDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.PortForwardListDTO.
 * Use `create(PortForwardListDTOSchema)` to create a new message.
 */
export declare const PortForwardListDTOSchema: GenMessage<PortForwardListDTO>;

/**
 * @generated from message boxteam.gateway.v1.ReorderGatewayWorkspacesRequest
 */
export declare type ReorderGatewayWorkspacesRequest = Message<"boxteam.gateway.v1.ReorderGatewayWorkspacesRequest"> & {
  /**
   * @generated from field: repeated string workspace_ids = 1;
   */
  workspaceIds: string[];
};

/**
 * Describes the message boxteam.gateway.v1.ReorderGatewayWorkspacesRequest.
 * Use `create(ReorderGatewayWorkspacesRequestSchema)` to create a new message.
 */
export declare const ReorderGatewayWorkspacesRequestSchema: GenMessage<ReorderGatewayWorkspacesRequest>;

/**
 * @generated from message boxteam.gateway.v1.ResolvedGatewayThemeDTO
 */
export declare type ResolvedGatewayThemeDTO = Message<"boxteam.gateway.v1.ResolvedGatewayThemeDTO"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string color_scheme = 3;
   */
  colorScheme: string;

  /**
   * @generated from field: google.protobuf.Struct tokens = 4;
   */
  tokens?: JsonObject | undefined;

  /**
   * @generated from field: optional string background_image_url = 5;
   */
  backgroundImageUrl?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.ResolvedGatewayThemeDTO.
 * Use `create(ResolvedGatewayThemeDTOSchema)` to create a new message.
 */
export declare const ResolvedGatewayThemeDTOSchema: GenMessage<ResolvedGatewayThemeDTO>;

/**
 * @generated from message boxteam.gateway.v1.SessionLocatorDTO
 */
export declare type SessionLocatorDTO = Message<"boxteam.gateway.v1.SessionLocatorDTO"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;
};

/**
 * Describes the message boxteam.gateway.v1.SessionLocatorDTO.
 * Use `create(SessionLocatorDTOSchema)` to create a new message.
 */
export declare const SessionLocatorDTOSchema: GenMessage<SessionLocatorDTO>;

/**
 * @generated from message boxteam.gateway.v1.SshConnectionOptionDTO
 */
export declare type SshConnectionOptionDTO = Message<"boxteam.gateway.v1.SshConnectionOptionDTO"> & {
  /**
   * @generated from field: string connection_id = 1;
   */
  connectionId: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: string label = 3;
   */
  label: string;

  /**
   * @generated from field: string host = 4;
   */
  host: string;

  /**
   * @generated from field: int64 port = 5;
   */
  port: bigint;

  /**
   * @generated from field: string username = 6;
   */
  username: string;

  /**
   * @generated from field: optional string workspace_id = 7;
   */
  workspaceId?: string | undefined;

  /**
   * @generated from field: optional string ssh_config_host = 8;
   */
  sshConfigHost?: string | undefined;

  /**
   * @generated from field: optional string initial_path = 9;
   */
  initialPath?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.SshConnectionOptionDTO.
 * Use `create(SshConnectionOptionDTOSchema)` to create a new message.
 */
export declare const SshConnectionOptionDTOSchema: GenMessage<SshConnectionOptionDTO>;

/**
 * @generated from message boxteam.gateway.v1.SshConnectionOptionListDTO
 */
export declare type SshConnectionOptionListDTO = Message<"boxteam.gateway.v1.SshConnectionOptionListDTO"> & {
  /**
   * @generated from field: repeated boxteam.gateway.v1.SshConnectionOptionDTO items = 1;
   */
  items: SshConnectionOptionDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.SshConnectionOptionListDTO.
 * Use `create(SshConnectionOptionListDTOSchema)` to create a new message.
 */
export declare const SshConnectionOptionListDTOSchema: GenMessage<SshConnectionOptionListDTO>;

/**
 * @generated from message boxteam.gateway.v1.UpdateGatewayWorkspaceRequest
 */
export declare type UpdateGatewayWorkspaceRequest = Message<"boxteam.gateway.v1.UpdateGatewayWorkspaceRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string parent_workspace_id = 2;
   */
  parentWorkspaceId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.UpdateGatewayWorkspaceRequest.
 * Use `create(UpdateGatewayWorkspaceRequestSchema)` to create a new message.
 */
export declare const UpdateGatewayWorkspaceRequestSchema: GenMessage<UpdateGatewayWorkspaceRequest>;

/**
 * @generated from message boxteam.gateway.v1.WebUIGatewayConsoleSettingsDTO
 */
export declare type WebUIGatewayConsoleSettingsDTO = Message<"boxteam.gateway.v1.WebUIGatewayConsoleSettingsDTO"> & {
  /**
   * @generated from field: optional string view = 1;
   */
  view?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIGatewayConsoleSettingsDTO.
 * Use `create(WebUIGatewayConsoleSettingsDTOSchema)` to create a new message.
 */
export declare const WebUIGatewayConsoleSettingsDTOSchema: GenMessage<WebUIGatewayConsoleSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUILayoutSettingsDTO
 */
export declare type WebUILayoutSettingsDTO = Message<"boxteam.gateway.v1.WebUILayoutSettingsDTO"> & {
  /**
   * @generated from field: optional string workbench_view = 1;
   */
  workbenchView?: string | undefined;

  /**
   * @generated from field: optional bool agent_sessions_panel_open = 2;
   */
  agentSessionsPanelOpen?: boolean | undefined;

  /**
   * @generated from field: optional bool chat_visible = 3;
   */
  chatVisible?: boolean | undefined;

  /**
   * @generated from field: optional bool auxiliary_visible = 4;
   */
  auxiliaryVisible?: boolean | undefined;

  /**
   * @generated from field: optional bool panel_visible = 5;
   */
  panelVisible?: boolean | undefined;

  /**
   * @generated from field: optional string auxiliary_tab = 6;
   */
  auxiliaryTab?: string | undefined;

  /**
   * @generated from field: repeated string auxiliary_tab_order = 7;
   */
  auxiliaryTabOrder: string[];

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIMainAreaRatiosDTO main_area_ratios = 8;
   */
  mainAreaRatios?: WebUIMainAreaRatiosDTO | undefined;

  /**
   * @generated from field: optional google.protobuf.Struct bottom_panel_by_workspace = 9;
   */
  bottomPanelByWorkspace?: JsonObject | undefined;

  /**
   * @generated from field: optional bool workspace_preview_visible = 10;
   */
  workspacePreviewVisible?: boolean | undefined;

  /**
   * @generated from field: optional bool workspace_preview_maximized = 11;
   */
  workspacePreviewMaximized?: boolean | undefined;

  /**
   * @generated from field: repeated string workspace_preview_file_paths = 12;
   */
  workspacePreviewFilePaths: string[];

  /**
   * @generated from field: optional string workspace_preview_active_file_path = 13;
   */
  workspacePreviewActiveFilePath?: string | undefined;

  /**
   * @generated from field: optional bool customizations_collapsed = 14;
   */
  customizationsCollapsed?: boolean | undefined;

  /**
   * @generated from field: optional int64 customizations_height = 15;
   */
  customizationsHeight?: bigint | undefined;

  /**
   * @generated from field: optional int64 panel_height = 16;
   */
  panelHeight?: bigint | undefined;

  /**
   * @generated from field: optional string content_view = 17;
   */
  contentView?: string | undefined;

  /**
   * @generated from field: optional string delivery_policy_default = 18;
   */
  deliveryPolicyDefault?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUILayoutSettingsDTO.
 * Use `create(WebUILayoutSettingsDTOSchema)` to create a new message.
 */
export declare const WebUILayoutSettingsDTOSchema: GenMessage<WebUILayoutSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUIMainAreaRatiosDTO
 */
export declare type WebUIMainAreaRatiosDTO = Message<"boxteam.gateway.v1.WebUIMainAreaRatiosDTO"> & {
  /**
   * @generated from field: optional double agent_sessions = 1;
   */
  agentSessions?: number | undefined;

  /**
   * @generated from field: optional double chat = 2;
   */
  chat?: number | undefined;

  /**
   * @generated from field: optional double workspace_preview = 3;
   */
  workspacePreview?: number | undefined;

  /**
   * @generated from field: optional double auxiliary = 4;
   */
  auxiliary?: number | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIMainAreaRatiosDTO.
 * Use `create(WebUIMainAreaRatiosDTOSchema)` to create a new message.
 */
export declare const WebUIMainAreaRatiosDTOSchema: GenMessage<WebUIMainAreaRatiosDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUISessionSidebarSettingsDTO
 */
export declare type WebUISessionSidebarSettingsDTO = Message<"boxteam.gateway.v1.WebUISessionSidebarSettingsDTO"> & {
  /**
   * @generated from field: optional string filter_mode = 1;
   */
  filterMode?: string | undefined;

  /**
   * @generated from field: optional string sort_mode = 2;
   */
  sortMode?: string | undefined;

  /**
   * @generated from field: optional string grouping_mode = 3;
   */
  groupingMode?: string | undefined;

  /**
   * @generated from field: optional bool workspace_group_capped = 4;
   */
  workspaceGroupCapped?: boolean | undefined;

  /**
   * @generated from field: repeated string collapsed_workspace_ids = 5;
   */
  collapsedWorkspaceIds: string[];

  /**
   * @generated from field: repeated string collapsed_session_ids = 6;
   */
  collapsedSessionIds: string[];

  /**
   * @generated from field: repeated string expanded_root_tree_ids = 7;
   */
  expandedRootTreeIds: string[];

  /**
   * @generated from field: repeated string collapsed_section_ids = 8;
   */
  collapsedSectionIds: string[];
};

/**
 * Describes the message boxteam.gateway.v1.WebUISessionSidebarSettingsDTO.
 * Use `create(WebUISessionSidebarSettingsDTOSchema)` to create a new message.
 */
export declare const WebUISessionSidebarSettingsDTOSchema: GenMessage<WebUISessionSidebarSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUISettingsDTO
 */
export declare type WebUISettingsDTO = Message<"boxteam.gateway.v1.WebUISettingsDTO"> & {
  /**
   * @generated from field: optional boxteam.gateway.v1.WebUILayoutSettingsDTO layout = 1;
   */
  layout?: WebUILayoutSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUISessionSidebarSettingsDTO session_sidebar = 2;
   */
  sessionSidebar?: WebUISessionSidebarSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIWorkspaceFileTreeSettingsDTO workspace_file_tree = 3;
   */
  workspaceFileTree?: WebUIWorkspaceFileTreeSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIGatewayConsoleSettingsDTO gateway_console = 4;
   */
  gatewayConsole?: WebUIGatewayConsoleSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIThemeSettingsDTO theme = 5;
   */
  theme?: WebUIThemeSettingsDTO | undefined;

  /**
   * @generated from field: repeated string recent_local_workspace_paths = 6;
   */
  recentLocalWorkspacePaths: string[];
};

/**
 * Describes the message boxteam.gateway.v1.WebUISettingsDTO.
 * Use `create(WebUISettingsDTOSchema)` to create a new message.
 */
export declare const WebUISettingsDTOSchema: GenMessage<WebUISettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUISettingsUpdateDTO
 */
export declare type WebUISettingsUpdateDTO = Message<"boxteam.gateway.v1.WebUISettingsUpdateDTO"> & {
  /**
   * @generated from field: optional boxteam.gateway.v1.WebUILayoutSettingsDTO layout = 1;
   */
  layout?: WebUILayoutSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUISessionSidebarSettingsDTO session_sidebar = 2;
   */
  sessionSidebar?: WebUISessionSidebarSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIWorkspaceFileTreeSettingsDTO workspace_file_tree = 3;
   */
  workspaceFileTree?: WebUIWorkspaceFileTreeSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIGatewayConsoleSettingsDTO gateway_console = 4;
   */
  gatewayConsole?: WebUIGatewayConsoleSettingsDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.WebUIThemeSettingsUpdateDTO theme = 5;
   */
  theme?: WebUIThemeSettingsUpdateDTO | undefined;

  /**
   * @generated from field: repeated string recent_local_workspace_paths = 6;
   */
  recentLocalWorkspacePaths: string[];
};

/**
 * Describes the message boxteam.gateway.v1.WebUISettingsUpdateDTO.
 * Use `create(WebUISettingsUpdateDTOSchema)` to create a new message.
 */
export declare const WebUISettingsUpdateDTOSchema: GenMessage<WebUISettingsUpdateDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUIThemeSettingsDTO
 */
export declare type WebUIThemeSettingsDTO = Message<"boxteam.gateway.v1.WebUIThemeSettingsDTO"> & {
  /**
   * @generated from field: optional string theme_id = 1;
   */
  themeId?: string | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GatewayThemeBackgroundDTO background = 2;
   */
  background?: GatewayThemeBackgroundDTO | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.ResolvedGatewayThemeDTO resolved_theme = 3;
   */
  resolvedTheme?: ResolvedGatewayThemeDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIThemeSettingsDTO.
 * Use `create(WebUIThemeSettingsDTOSchema)` to create a new message.
 */
export declare const WebUIThemeSettingsDTOSchema: GenMessage<WebUIThemeSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUIThemeSettingsUpdateDTO
 */
export declare type WebUIThemeSettingsUpdateDTO = Message<"boxteam.gateway.v1.WebUIThemeSettingsUpdateDTO"> & {
  /**
   * @generated from field: optional string theme_id = 1;
   */
  themeId?: string | undefined;

  /**
   * @generated from field: optional boxteam.gateway.v1.GatewayThemeBackgroundDTO background = 2;
   */
  background?: GatewayThemeBackgroundDTO | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIThemeSettingsUpdateDTO.
 * Use `create(WebUIThemeSettingsUpdateDTOSchema)` to create a new message.
 */
export declare const WebUIThemeSettingsUpdateDTOSchema: GenMessage<WebUIThemeSettingsUpdateDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUIWorkspaceBottomPanelSettingsDTO
 */
export declare type WebUIWorkspaceBottomPanelSettingsDTO = Message<"boxteam.gateway.v1.WebUIWorkspaceBottomPanelSettingsDTO"> & {
  /**
   * @generated from field: optional bool visible = 1;
   */
  visible?: boolean | undefined;

  /**
   * @generated from field: optional int64 height = 2;
   */
  height?: bigint | undefined;

  /**
   * @generated from field: optional string tab = 3;
   */
  tab?: string | undefined;

  /**
   * @generated from field: optional string terminal_id = 4;
   */
  terminalId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIWorkspaceBottomPanelSettingsDTO.
 * Use `create(WebUIWorkspaceBottomPanelSettingsDTOSchema)` to create a new message.
 */
export declare const WebUIWorkspaceBottomPanelSettingsDTOSchema: GenMessage<WebUIWorkspaceBottomPanelSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WebUIWorkspaceFileTreeSettingsDTO
 */
export declare type WebUIWorkspaceFileTreeSettingsDTO = Message<"boxteam.gateway.v1.WebUIWorkspaceFileTreeSettingsDTO"> & {
  /**
   * @generated from field: optional google.protobuf.Struct expanded_paths_by_workspace = 1;
   */
  expandedPathsByWorkspace?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WebUIWorkspaceFileTreeSettingsDTO.
 * Use `create(WebUIWorkspaceFileTreeSettingsDTOSchema)` to create a new message.
 */
export declare const WebUIWorkspaceFileTreeSettingsDTOSchema: GenMessage<WebUIWorkspaceFileTreeSettingsDTO>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceFolderCreateRequest
 */
export declare type WorkspaceFolderCreateRequest = Message<"boxteam.gateway.v1.WorkspaceFolderCreateRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional string parent_node_id = 2;
   */
  parentNodeId?: string | undefined;

  /**
   * @generated from field: optional int64 position = 3;
   */
  position?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceFolderCreateRequest.
 * Use `create(WorkspaceFolderCreateRequestSchema)` to create a new message.
 */
export declare const WorkspaceFolderCreateRequestSchema: GenMessage<WorkspaceFolderCreateRequest>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationBreadcrumbDTO
 */
export declare type WorkspaceNavigationBreadcrumbDTO = Message<"boxteam.gateway.v1.WorkspaceNavigationBreadcrumbDTO"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.WorkspaceNavigationNodeDTO items = 2;
   */
  items: WorkspaceNavigationNodeDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationBreadcrumbDTO.
 * Use `create(WorkspaceNavigationBreadcrumbDTOSchema)` to create a new message.
 */
export declare const WorkspaceNavigationBreadcrumbDTOSchema: GenMessage<WorkspaceNavigationBreadcrumbDTO>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationNodeDTO
 */
export declare type WorkspaceNavigationNodeDTO = Message<"boxteam.gateway.v1.WorkspaceNavigationNodeDTO"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: optional string parent_node_id = 4;
   */
  parentNodeId?: string | undefined;

  /**
   * @generated from field: optional string workspace_id = 5;
   */
  workspaceId?: string | undefined;

  /**
   * @generated from field: optional int64 position = 6;
   */
  position?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationNodeDTO.
 * Use `create(WorkspaceNavigationNodeDTOSchema)` to create a new message.
 */
export declare const WorkspaceNavigationNodeDTOSchema: GenMessage<WorkspaceNavigationNodeDTO>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationNodeUpdateRequest
 */
export declare type WorkspaceNavigationNodeUpdateRequest = Message<"boxteam.gateway.v1.WorkspaceNavigationNodeUpdateRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string parent_node_id = 2;
   */
  parentNodeId?: string | undefined;

  /**
   * @generated from field: optional int64 position = 3;
   */
  position?: bigint | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationNodeUpdateRequest.
 * Use `create(WorkspaceNavigationNodeUpdateRequestSchema)` to create a new message.
 */
export declare const WorkspaceNavigationNodeUpdateRequestSchema: GenMessage<WorkspaceNavigationNodeUpdateRequest>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationPlacementRequest
 */
export declare type WorkspaceNavigationPlacementRequest = Message<"boxteam.gateway.v1.WorkspaceNavigationPlacementRequest"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: optional string parent_node_id = 2;
   */
  parentNodeId?: string | undefined;

  /**
   * @generated from field: string mode = 3;
   */
  mode: string;

  /**
   * @generated from field: optional string target_node_id = 4;
   */
  targetNodeId?: string | undefined;
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationPlacementRequest.
 * Use `create(WorkspaceNavigationPlacementRequestSchema)` to create a new message.
 */
export declare const WorkspaceNavigationPlacementRequestSchema: GenMessage<WorkspaceNavigationPlacementRequest>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationReorderRequest
 */
export declare type WorkspaceNavigationReorderRequest = Message<"boxteam.gateway.v1.WorkspaceNavigationReorderRequest"> & {
  /**
   * @generated from field: optional string parent_node_id = 1;
   */
  parentNodeId?: string | undefined;

  /**
   * @generated from field: repeated string node_ids = 2;
   */
  nodeIds: string[];
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationReorderRequest.
 * Use `create(WorkspaceNavigationReorderRequestSchema)` to create a new message.
 */
export declare const WorkspaceNavigationReorderRequestSchema: GenMessage<WorkspaceNavigationReorderRequest>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceNavigationTreeDTO
 */
export declare type WorkspaceNavigationTreeDTO = Message<"boxteam.gateway.v1.WorkspaceNavigationTreeDTO"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.WorkspaceNavigationNodeDTO nodes = 2;
   */
  nodes: WorkspaceNavigationNodeDTO[];
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceNavigationTreeDTO.
 * Use `create(WorkspaceNavigationTreeDTOSchema)` to create a new message.
 */
export declare const WorkspaceNavigationTreeDTOSchema: GenMessage<WorkspaceNavigationTreeDTO>;

