// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/gateway/v1/workspace_registry.proto (package boxteam.gateway.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file boxteam/gateway/v1/workspace_registry.proto.
 */
export declare const file_boxteam_gateway_v1_workspace_registry: GenFile;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceSummary
 */
export declare type WorkspaceSummary = Message<"boxteam.gateway.v1.WorkspaceSummary"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string root_path = 3;
   */
  rootPath: string;

  /**
   * @generated from field: string backend_url = 4;
   */
  backendUrl: string;

  /**
   * @generated from field: boxteam.gateway.v1.WorkspaceStatus status = 5;
   */
  status: WorkspaceStatus;

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;

  /**
   * @generated from field: string connection_kind = 7;
   */
  connectionKind: string;
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceSummary.
 * Use `create(WorkspaceSummarySchema)` to create a new message.
 */
export declare const WorkspaceSummarySchema: GenMessage<WorkspaceSummary>;

/**
 * @generated from message boxteam.gateway.v1.WorkspaceRegistry
 */
export declare type WorkspaceRegistry = Message<"boxteam.gateway.v1.WorkspaceRegistry"> & {
  /**
   * @generated from field: string active_workspace_id = 1;
   */
  activeWorkspaceId: string;

  /**
   * @generated from field: repeated boxteam.gateway.v1.WorkspaceSummary items = 2;
   */
  items: WorkspaceSummary[];
};

/**
 * Describes the message boxteam.gateway.v1.WorkspaceRegistry.
 * Use `create(WorkspaceRegistrySchema)` to create a new message.
 */
export declare const WorkspaceRegistrySchema: GenMessage<WorkspaceRegistry>;

/**
 * @generated from enum boxteam.gateway.v1.WorkspaceStatus
 */
export enum WorkspaceStatus {
  /**
   * @generated from enum value: WORKSPACE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORKSPACE_STATUS_READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: WORKSPACE_STATUS_OFFLINE = 2;
   */
  OFFLINE = 2,
}

/**
 * Describes the enum boxteam.gateway.v1.WorkspaceStatus.
 */
export declare const WorkspaceStatusSchema: GenEnum<WorkspaceStatus>;

