// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/workspace/v2/job.proto (package boxteam.workspace.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/workspace/v2/job.proto.
 */
export const file_boxteam_workspace_v2_job = /*@__PURE__*/
  fileDesc("Ch5ib3h0ZWFtL3dvcmtzcGFjZS92Mi9qb2IucHJvdG8SFGJveHRlYW0ud29ya3NwYWNlLnYyIucDCgNKb2ISDgoGam9iX2lkGAEgASgJEhIKCm1lc3NhZ2VfaWQYAiABKAkSEgoKc2Vzc2lvbl9pZBgDIAEoCRIrCgRtb2RlGAQgASgOMh0uYm94dGVhbS53b3Jrc3BhY2UudjIuUnVuTW9kZRIvCgZzdGF0dXMYBSABKA4yHy5ib3h0ZWFtLndvcmtzcGFjZS52Mi5Kb2JTdGF0dXMSEwoLZW50cnlfYWdlbnQYBiABKAkSEAoIcHJvZ3Jlc3MYByABKA0SGQoMY3VycmVudF9zdGVwGAggASgJSACIAQESGgoNZXJyb3JfbWVzc2FnZRgJIAEoCUgBiAEBEikKCG1ldGFkYXRhGAogASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBIuCgpjcmVhdGVkX2F0GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAwgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIxCghlbmRlZF9hdBgNIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAogBAUIPCg1fY3VycmVudF9zdGVwQhAKDl9lcnJvcl9tZXNzYWdlQgsKCV9lbmRlZF9hdCK0AQoLSm9iUHJvZ3Jlc3MSDgoGam9iX2lkGAEgASgJEi8KBnN0YXR1cxgCIAEoDjIfLmJveHRlYW0ud29ya3NwYWNlLnYyLkpvYlN0YXR1cxIcCg9jdXJyZW50X3N0ZXBfaWQYAyABKAlIAIgBARIQCghwcm9ncmVzcxgEIAEoDRIUCgdtZXNzYWdlGAUgASgJSAGIAQFCEgoQX2N1cnJlbnRfc3RlcF9pZEIKCghfbWVzc2FnZSr6AgoJSm9iU3RhdHVzEhoKFkpPQl9TVEFUVVNfVU5TUEVDSUZJRUQQABIXChNKT0JfU1RBVFVTX0FDQ0VQVEVEEAESFQoRSk9CX1NUQVRVU19RVUVVRUQQAhIWChJKT0JfU1RBVFVTX1JVTk5JTkcQAxIYChRKT0JfU1RBVFVTX1NUUkVBTUlORxAEEhwKGEpPQl9TVEFUVVNfV0FJVElOR19JTlBVVBAFEhUKEUpPQl9TVEFUVVNfUEFVU0VEEAYSIAocSk9CX1NUQVRVU19JTlRFUlJVUFRfUEVORElORxAHEhkKFUpPQl9TVEFUVVNfQ0FOQ0VMTElORxAIEhgKFEpPQl9TVEFUVVNfQ09NUExFVEVEEAkSGAoUSk9CX1NUQVRVU19TVUNDRUVERUQQChIVChFKT0JfU1RBVFVTX0ZBSUxFRBALEhgKFEpPQl9TVEFUVVNfQ0FOQ0VMTEVEEAwSGAoUSk9CX1NUQVRVU19USU1FRF9PVVQQDSpYCgdSdW5Nb2RlEhgKFFJVTl9NT0RFX1VOU1BFQ0lGSUVEEAASGQoVUlVOX01PREVfU0lOR0xFX0FHRU5UEAESGAoUUlVOX01PREVfTVVMVElfQUdFTlQQAmIGcHJvdG8z", [file_google_protobuf_struct, file_google_protobuf_timestamp]);

/**
 * Describes the message boxteam.workspace.v2.Job.
 * Use `create(JobSchema)` to create a new message.
 */
export const JobSchema = /*@__PURE__*/
  messageDesc(file_boxteam_workspace_v2_job, 0);

/**
 * Describes the message boxteam.workspace.v2.JobProgress.
 * Use `create(JobProgressSchema)` to create a new message.
 */
export const JobProgressSchema = /*@__PURE__*/
  messageDesc(file_boxteam_workspace_v2_job, 1);

/**
 * Describes the enum boxteam.workspace.v2.JobStatus.
 */
export const JobStatusSchema = /*@__PURE__*/
  enumDesc(file_boxteam_workspace_v2_job, 0);

/**
 * @generated from enum boxteam.workspace.v2.JobStatus
 */
export const JobStatus = /*@__PURE__*/
  tsEnum(JobStatusSchema);

/**
 * Describes the enum boxteam.workspace.v2.RunMode.
 */
export const RunModeSchema = /*@__PURE__*/
  enumDesc(file_boxteam_workspace_v2_job, 1);

/**
 * @generated from enum boxteam.workspace.v2.RunMode
 */
export const RunMode = /*@__PURE__*/
  tsEnum(RunModeSchema);

