// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/workspace/v2/job.proto (package boxteam.workspace.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/workspace/v2/job.proto.
 */
export declare const file_boxteam_workspace_v2_job: GenFile;

/**
 * @generated from message boxteam.workspace.v2.Job
 */
export declare type Job = Message<"boxteam.workspace.v2.Job"> & {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId: string;

  /**
   * @generated from field: string message_id = 2;
   */
  messageId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: boxteam.workspace.v2.RunMode mode = 4;
   */
  mode: RunMode;

  /**
   * @generated from field: boxteam.workspace.v2.JobStatus status = 5;
   */
  status: JobStatus;

  /**
   * @generated from field: string entry_agent = 6;
   */
  entryAgent: string;

  /**
   * @generated from field: uint32 progress = 7;
   */
  progress: number;

  /**
   * @generated from field: optional string current_step = 8;
   */
  currentStep?: string | undefined;

  /**
   * @generated from field: optional string error_message = 9;
   */
  errorMessage?: string | undefined;

  /**
   * @generated from field: google.protobuf.Struct metadata = 10;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp ended_at = 13;
   */
  endedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.workspace.v2.Job.
 * Use `create(JobSchema)` to create a new message.
 */
export declare const JobSchema: GenMessage<Job>;

/**
 * @generated from message boxteam.workspace.v2.JobProgress
 */
export declare type JobProgress = Message<"boxteam.workspace.v2.JobProgress"> & {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId: string;

  /**
   * @generated from field: boxteam.workspace.v2.JobStatus status = 2;
   */
  status: JobStatus;

  /**
   * @generated from field: optional string current_step_id = 3;
   */
  currentStepId?: string | undefined;

  /**
   * @generated from field: uint32 progress = 4;
   */
  progress: number;

  /**
   * @generated from field: optional string message = 5;
   */
  message?: string | undefined;
};

/**
 * Describes the message boxteam.workspace.v2.JobProgress.
 * Use `create(JobProgressSchema)` to create a new message.
 */
export declare const JobProgressSchema: GenMessage<JobProgress>;

/**
 * @generated from enum boxteam.workspace.v2.JobStatus
 */
export enum JobStatus {
  /**
   * @generated from enum value: JOB_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: JOB_STATUS_ACCEPTED = 1;
   */
  ACCEPTED = 1,

  /**
   * @generated from enum value: JOB_STATUS_QUEUED = 2;
   */
  QUEUED = 2,

  /**
   * @generated from enum value: JOB_STATUS_RUNNING = 3;
   */
  RUNNING = 3,

  /**
   * @generated from enum value: JOB_STATUS_STREAMING = 4;
   */
  STREAMING = 4,

  /**
   * @generated from enum value: JOB_STATUS_WAITING_INPUT = 5;
   */
  WAITING_INPUT = 5,

  /**
   * @generated from enum value: JOB_STATUS_PAUSED = 6;
   */
  PAUSED = 6,

  /**
   * @generated from enum value: JOB_STATUS_INTERRUPT_PENDING = 7;
   */
  INTERRUPT_PENDING = 7,

  /**
   * @generated from enum value: JOB_STATUS_CANCELLING = 8;
   */
  CANCELLING = 8,

  /**
   * @generated from enum value: JOB_STATUS_COMPLETED = 9;
   */
  COMPLETED = 9,

  /**
   * @generated from enum value: JOB_STATUS_SUCCEEDED = 10;
   */
  SUCCEEDED = 10,

  /**
   * @generated from enum value: JOB_STATUS_FAILED = 11;
   */
  FAILED = 11,

  /**
   * @generated from enum value: JOB_STATUS_CANCELLED = 12;
   */
  CANCELLED = 12,

  /**
   * @generated from enum value: JOB_STATUS_TIMED_OUT = 13;
   */
  TIMED_OUT = 13,
}

/**
 * Describes the enum boxteam.workspace.v2.JobStatus.
 */
export declare const JobStatusSchema: GenEnum<JobStatus>;

/**
 * @generated from enum boxteam.workspace.v2.RunMode
 */
export enum RunMode {
  /**
   * @generated from enum value: RUN_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUN_MODE_SINGLE_AGENT = 1;
   */
  SINGLE_AGENT = 1,

  /**
   * @generated from enum value: RUN_MODE_MULTI_AGENT = 2;
   */
  MULTI_AGENT = 2,
}

/**
 * Describes the enum boxteam.workspace.v2.RunMode.
 */
export declare const RunModeSchema: GenEnum<RunMode>;

