// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/workspace/v2/message.proto (package boxteam.workspace.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/workspace/v2/message.proto.
 */
export declare const file_boxteam_workspace_v2_message: GenFile;

/**
 * @generated from message boxteam.workspace.v2.AttachmentRef
 */
export declare type AttachmentRef = Message$1<"boxteam.workspace.v2.AttachmentRef"> & {
  /**
   * @generated from field: string file_id = 1;
   */
  fileId: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string content_type = 3;
   */
  contentType?: string | undefined;

  /**
   * @generated from field: optional string data_url = 4;
   */
  dataUrl?: string | undefined;
};

/**
 * Describes the message boxteam.workspace.v2.AttachmentRef.
 * Use `create(AttachmentRefSchema)` to create a new message.
 */
export declare const AttachmentRefSchema: GenMessage<AttachmentRef>;

/**
 * @generated from message boxteam.workspace.v2.Message
 */
export declare type Message = Message$1<"boxteam.workspace.v2.Message"> & {
  /**
   * @generated from field: string message_id = 1;
   */
  messageId: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: boxteam.workspace.v2.MessageRole role = 3;
   */
  role: MessageRole;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * @generated from field: repeated boxteam.workspace.v2.AttachmentRef attachments = 5;
   */
  attachments: AttachmentRef[];

  /**
   * @generated from field: google.protobuf.Struct metadata = 6;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message boxteam.workspace.v2.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from enum boxteam.workspace.v2.MessageRole
 */
export enum MessageRole {
  /**
   * @generated from enum value: MESSAGE_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: MESSAGE_ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,

  /**
   * @generated from enum value: MESSAGE_ROLE_SYSTEM = 3;
   */
  SYSTEM = 3,

  /**
   * @generated from enum value: MESSAGE_ROLE_TOOL = 4;
   */
  TOOL = 4,
}

/**
 * Describes the enum boxteam.workspace.v2.MessageRole.
 */
export declare const MessageRoleSchema: GenEnum<MessageRole>;

