// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/workspace/v2/session_stream.proto (package boxteam.workspace.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { SessionExecutionEvent } from "./session_interaction_pb.js";

/**
 * Describes the file boxteam/workspace/v2/session_stream.proto.
 */
export declare const file_boxteam_workspace_v2_session_stream: GenFile;

/**
 * @generated from message boxteam.workspace.v2.SessionExecutionSse
 */
export declare type SessionExecutionSse = Message<"boxteam.workspace.v2.SessionExecutionSse"> & {
  /**
   * @generated from field: boxteam.workspace.v2.SessionExecutionEvent event = 1;
   */
  event?: SessionExecutionEvent | undefined;

  /**
   * @generated from field: string raw_type = 2;
   */
  rawType: string;

  /**
   * @generated from field: google.protobuf.Struct raw_payload = 3;
   */
  rawPayload?: JsonObject | undefined;
};

/**
 * Describes the message boxteam.workspace.v2.SessionExecutionSse.
 * Use `create(SessionExecutionSseSchema)` to create a new message.
 */
export declare const SessionExecutionSseSchema: GenMessage<SessionExecutionSse>;

