// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/workspace/v2/session_stream.proto (package boxteam.workspace.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_boxteam_workspace_v2_session_interaction } from "./session_interaction_pb.js";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file boxteam/workspace/v2/session_stream.proto.
 */
export const file_boxteam_workspace_v2_session_stream = /*@__PURE__*/
  fileDesc("Cilib3h0ZWFtL3dvcmtzcGFjZS92Mi9zZXNzaW9uX3N0cmVhbS5wcm90bxIUYm94dGVhbS53b3Jrc3BhY2UudjIikQEKE1Nlc3Npb25FeGVjdXRpb25Tc2USOgoFZXZlbnQYASABKAsyKy5ib3h0ZWFtLndvcmtzcGFjZS52Mi5TZXNzaW9uRXhlY3V0aW9uRXZlbnQSEAoIcmF3X3R5cGUYAiABKAkSLAoLcmF3X3BheWxvYWQYAyABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0YgZwcm90bzM", [file_boxteam_workspace_v2_session_interaction, file_google_protobuf_struct]);

/**
 * Describes the message boxteam.workspace.v2.SessionExecutionSse.
 * Use `create(SessionExecutionSseSchema)` to create a new message.
 */
export const SessionExecutionSseSchema = /*@__PURE__*/
  messageDesc(file_boxteam_workspace_v2_session_stream, 0);

