// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/common/v1/pagination.proto

/* eslint-disable */

export const protobufPackage = "boxteam.common.v1";

export interface PageCursor {
  cursor: string;
  limit: number;
}

export interface PageInfo {
  next_cursor: string;
  has_more: boolean;
}

function createBasePageCursor(): PageCursor {
  return { cursor: "", limit: 0 };
}

export const PageCursor: MessageFns<PageCursor> = {
  fromJSON(object: any): PageCursor {
    return {
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: PageCursor): unknown {
    const obj: any = {};
    if (message.cursor !== "") {
      obj.cursor = message.cursor;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageCursor>, I>>(base?: I): PageCursor {
    return PageCursor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageCursor>, I>>(object: I): PageCursor {
    const message = createBasePageCursor();
    message.cursor = object.cursor ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBasePageInfo(): PageInfo {
  return { next_cursor: "", has_more: false };
}

export const PageInfo: MessageFns<PageInfo> = {
  fromJSON(object: any): PageInfo {
    return {
      next_cursor: isSet(object.next_cursor) ? globalThis.String(object.next_cursor) : "",
      has_more: isSet(object.has_more) ? globalThis.Boolean(object.has_more) : false,
    };
  },

  toJSON(message: PageInfo): unknown {
    const obj: any = {};
    if (message.next_cursor !== "") {
      obj.next_cursor = message.next_cursor;
    }
    if (message.has_more !== false) {
      obj.has_more = message.has_more;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageInfo>, I>>(base?: I): PageInfo {
    return PageInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageInfo>, I>>(object: I): PageInfo {
    const message = createBasePageInfo();
    message.next_cursor = object.next_cursor ?? "";
    message.has_more = object.has_more ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
