// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/common/v1/service_lifecycle.proto

/* eslint-disable */

export const protobufPackage = "boxteam.common.v1";

export enum ServiceStatus {
  SERVICE_STATUS_UNSPECIFIED = 0,
  SERVICE_STATUS_READY = 1,
  SERVICE_STATUS_DEGRADED = 2,
  SERVICE_STATUS_OFFLINE = 3,
  SERVICE_STATUS_UNAVAILABLE = 4,
  UNRECOGNIZED = -1,
}

export function serviceStatusFromJSON(object: any): ServiceStatus {
  switch (object) {
    case 0:
    case "SERVICE_STATUS_UNSPECIFIED":
      return ServiceStatus.SERVICE_STATUS_UNSPECIFIED;
    case 1:
    case "SERVICE_STATUS_READY":
      return ServiceStatus.SERVICE_STATUS_READY;
    case 2:
    case "SERVICE_STATUS_DEGRADED":
      return ServiceStatus.SERVICE_STATUS_DEGRADED;
    case 3:
    case "SERVICE_STATUS_OFFLINE":
      return ServiceStatus.SERVICE_STATUS_OFFLINE;
    case 4:
    case "SERVICE_STATUS_UNAVAILABLE":
      return ServiceStatus.SERVICE_STATUS_UNAVAILABLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServiceStatus.UNRECOGNIZED;
  }
}

export function serviceStatusToJSON(object: ServiceStatus): string {
  switch (object) {
    case ServiceStatus.SERVICE_STATUS_UNSPECIFIED:
      return "SERVICE_STATUS_UNSPECIFIED";
    case ServiceStatus.SERVICE_STATUS_READY:
      return "SERVICE_STATUS_READY";
    case ServiceStatus.SERVICE_STATUS_DEGRADED:
      return "SERVICE_STATUS_DEGRADED";
    case ServiceStatus.SERVICE_STATUS_OFFLINE:
      return "SERVICE_STATUS_OFFLINE";
    case ServiceStatus.SERVICE_STATUS_UNAVAILABLE:
      return "SERVICE_STATUS_UNAVAILABLE";
    case ServiceStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ServiceHealth {
  service_id: string;
  status: ServiceStatus;
  health_path: string;
  error: string;
  checked_at: string | undefined;
}

function createBaseServiceHealth(): ServiceHealth {
  return { service_id: "", status: 0, health_path: "", error: "", checked_at: undefined };
}

export const ServiceHealth: MessageFns<ServiceHealth> = {
  fromJSON(object: any): ServiceHealth {
    return {
      service_id: isSet(object.service_id) ? globalThis.String(object.service_id) : "",
      status: isSet(object.status) ? serviceStatusFromJSON(object.status) : 0,
      health_path: isSet(object.health_path) ? globalThis.String(object.health_path) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      checked_at: isSet(object.checked_at) ? globalThis.String(object.checked_at) : undefined,
    };
  },

  toJSON(message: ServiceHealth): unknown {
    const obj: any = {};
    if (message.service_id !== "") {
      obj.service_id = message.service_id;
    }
    if (message.status !== 0) {
      obj.status = serviceStatusToJSON(message.status);
    }
    if (message.health_path !== "") {
      obj.health_path = message.health_path;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.checked_at !== undefined) {
      obj.checked_at = message.checked_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceHealth>, I>>(base?: I): ServiceHealth {
    return ServiceHealth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceHealth>, I>>(object: I): ServiceHealth {
    const message = createBaseServiceHealth();
    message.service_id = object.service_id ?? "";
    message.status = object.status ?? 0;
    message.health_path = object.health_path ?? "";
    message.error = object.error ?? "";
    message.checked_at = object.checked_at ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
