// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/file_events.proto

/* eslint-disable */

export const protobufPackage = "boxteam.workspace.v2";

export interface WorkspaceFileChange {
  kind: string;
  path: string;
}

export interface WorkspaceFileChangeBatch {
  changes: WorkspaceFileChange[];
  overflow: boolean;
}

export interface SseError {
  message: string;
}

function createBaseWorkspaceFileChange(): WorkspaceFileChange {
  return { kind: "", path: "" };
}

export const WorkspaceFileChange: MessageFns<WorkspaceFileChange> = {
  fromJSON(object: any): WorkspaceFileChange {
    return {
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: WorkspaceFileChange): unknown {
    const obj: any = {};
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkspaceFileChange>, I>>(base?: I): WorkspaceFileChange {
    return WorkspaceFileChange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkspaceFileChange>, I>>(object: I): WorkspaceFileChange {
    const message = createBaseWorkspaceFileChange();
    message.kind = object.kind ?? "";
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseWorkspaceFileChangeBatch(): WorkspaceFileChangeBatch {
  return { changes: [], overflow: false };
}

export const WorkspaceFileChangeBatch: MessageFns<WorkspaceFileChangeBatch> = {
  fromJSON(object: any): WorkspaceFileChangeBatch {
    return {
      changes: globalThis.Array.isArray(object?.changes)
        ? object.changes.map((e: any) => WorkspaceFileChange.fromJSON(e))
        : [],
      overflow: isSet(object.overflow) ? globalThis.Boolean(object.overflow) : false,
    };
  },

  toJSON(message: WorkspaceFileChangeBatch): unknown {
    const obj: any = {};
    if (message.changes?.length) {
      obj.changes = message.changes.map((e) => WorkspaceFileChange.toJSON(e));
    }
    if (message.overflow !== false) {
      obj.overflow = message.overflow;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkspaceFileChangeBatch>, I>>(base?: I): WorkspaceFileChangeBatch {
    return WorkspaceFileChangeBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkspaceFileChangeBatch>, I>>(object: I): WorkspaceFileChangeBatch {
    const message = createBaseWorkspaceFileChangeBatch();
    message.changes = object.changes?.map((e) => WorkspaceFileChange.fromPartial(e)) || [];
    message.overflow = object.overflow ?? false;
    return message;
  },
};

function createBaseSseError(): SseError {
  return { message: "" };
}

export const SseError: MessageFns<SseError> = {
  fromJSON(object: any): SseError {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: SseError): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SseError>, I>>(base?: I): SseError {
    return SseError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SseError>, I>>(object: I): SseError {
    const message = createBaseSseError();
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
