// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/job.proto

/* eslint-disable */

export const protobufPackage = "boxteam.workspace.v2";

export enum JobStatus {
  JOB_STATUS_UNSPECIFIED = 0,
  JOB_STATUS_ACCEPTED = 1,
  JOB_STATUS_QUEUED = 2,
  JOB_STATUS_RUNNING = 3,
  JOB_STATUS_STREAMING = 4,
  JOB_STATUS_WAITING_INPUT = 5,
  JOB_STATUS_PAUSED = 6,
  JOB_STATUS_INTERRUPT_PENDING = 7,
  JOB_STATUS_CANCELLING = 8,
  JOB_STATUS_COMPLETED = 9,
  JOB_STATUS_SUCCEEDED = 10,
  JOB_STATUS_FAILED = 11,
  JOB_STATUS_CANCELLED = 12,
  JOB_STATUS_TIMED_OUT = 13,
  UNRECOGNIZED = -1,
}

export function jobStatusFromJSON(object: any): JobStatus {
  switch (object) {
    case 0:
    case "JOB_STATUS_UNSPECIFIED":
      return JobStatus.JOB_STATUS_UNSPECIFIED;
    case 1:
    case "JOB_STATUS_ACCEPTED":
      return JobStatus.JOB_STATUS_ACCEPTED;
    case 2:
    case "JOB_STATUS_QUEUED":
      return JobStatus.JOB_STATUS_QUEUED;
    case 3:
    case "JOB_STATUS_RUNNING":
      return JobStatus.JOB_STATUS_RUNNING;
    case 4:
    case "JOB_STATUS_STREAMING":
      return JobStatus.JOB_STATUS_STREAMING;
    case 5:
    case "JOB_STATUS_WAITING_INPUT":
      return JobStatus.JOB_STATUS_WAITING_INPUT;
    case 6:
    case "JOB_STATUS_PAUSED":
      return JobStatus.JOB_STATUS_PAUSED;
    case 7:
    case "JOB_STATUS_INTERRUPT_PENDING":
      return JobStatus.JOB_STATUS_INTERRUPT_PENDING;
    case 8:
    case "JOB_STATUS_CANCELLING":
      return JobStatus.JOB_STATUS_CANCELLING;
    case 9:
    case "JOB_STATUS_COMPLETED":
      return JobStatus.JOB_STATUS_COMPLETED;
    case 10:
    case "JOB_STATUS_SUCCEEDED":
      return JobStatus.JOB_STATUS_SUCCEEDED;
    case 11:
    case "JOB_STATUS_FAILED":
      return JobStatus.JOB_STATUS_FAILED;
    case 12:
    case "JOB_STATUS_CANCELLED":
      return JobStatus.JOB_STATUS_CANCELLED;
    case 13:
    case "JOB_STATUS_TIMED_OUT":
      return JobStatus.JOB_STATUS_TIMED_OUT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JobStatus.UNRECOGNIZED;
  }
}

export function jobStatusToJSON(object: JobStatus): string {
  switch (object) {
    case JobStatus.JOB_STATUS_UNSPECIFIED:
      return "JOB_STATUS_UNSPECIFIED";
    case JobStatus.JOB_STATUS_ACCEPTED:
      return "JOB_STATUS_ACCEPTED";
    case JobStatus.JOB_STATUS_QUEUED:
      return "JOB_STATUS_QUEUED";
    case JobStatus.JOB_STATUS_RUNNING:
      return "JOB_STATUS_RUNNING";
    case JobStatus.JOB_STATUS_STREAMING:
      return "JOB_STATUS_STREAMING";
    case JobStatus.JOB_STATUS_WAITING_INPUT:
      return "JOB_STATUS_WAITING_INPUT";
    case JobStatus.JOB_STATUS_PAUSED:
      return "JOB_STATUS_PAUSED";
    case JobStatus.JOB_STATUS_INTERRUPT_PENDING:
      return "JOB_STATUS_INTERRUPT_PENDING";
    case JobStatus.JOB_STATUS_CANCELLING:
      return "JOB_STATUS_CANCELLING";
    case JobStatus.JOB_STATUS_COMPLETED:
      return "JOB_STATUS_COMPLETED";
    case JobStatus.JOB_STATUS_SUCCEEDED:
      return "JOB_STATUS_SUCCEEDED";
    case JobStatus.JOB_STATUS_FAILED:
      return "JOB_STATUS_FAILED";
    case JobStatus.JOB_STATUS_CANCELLED:
      return "JOB_STATUS_CANCELLED";
    case JobStatus.JOB_STATUS_TIMED_OUT:
      return "JOB_STATUS_TIMED_OUT";
    case JobStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RunMode {
  RUN_MODE_UNSPECIFIED = 0,
  RUN_MODE_SINGLE_AGENT = 1,
  RUN_MODE_MULTI_AGENT = 2,
  UNRECOGNIZED = -1,
}

export function runModeFromJSON(object: any): RunMode {
  switch (object) {
    case 0:
    case "RUN_MODE_UNSPECIFIED":
      return RunMode.RUN_MODE_UNSPECIFIED;
    case 1:
    case "RUN_MODE_SINGLE_AGENT":
      return RunMode.RUN_MODE_SINGLE_AGENT;
    case 2:
    case "RUN_MODE_MULTI_AGENT":
      return RunMode.RUN_MODE_MULTI_AGENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RunMode.UNRECOGNIZED;
  }
}

export function runModeToJSON(object: RunMode): string {
  switch (object) {
    case RunMode.RUN_MODE_UNSPECIFIED:
      return "RUN_MODE_UNSPECIFIED";
    case RunMode.RUN_MODE_SINGLE_AGENT:
      return "RUN_MODE_SINGLE_AGENT";
    case RunMode.RUN_MODE_MULTI_AGENT:
      return "RUN_MODE_MULTI_AGENT";
    case RunMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Job {
  job_id: string;
  message_id: string;
  session_id: string;
  mode: RunMode;
  status: JobStatus;
  entry_agent: string;
  progress: number;
  current_step?: string | undefined;
  error_message?: string | undefined;
  metadata: { [key: string]: any } | undefined;
  created_at: string | undefined;
  updated_at: string | undefined;
  ended_at?: string | undefined;
}

export interface JobProgress {
  job_id: string;
  status: JobStatus;
  current_step_id?: string | undefined;
  progress: number;
  message?: string | undefined;
}

function createBaseJob(): Job {
  return {
    job_id: "",
    message_id: "",
    session_id: "",
    mode: 0,
    status: 0,
    entry_agent: "",
    progress: 0,
    current_step: undefined,
    error_message: undefined,
    metadata: undefined,
    created_at: undefined,
    updated_at: undefined,
    ended_at: undefined,
  };
}

export const Job: MessageFns<Job> = {
  fromJSON(object: any): Job {
    return {
      job_id: isSet(object.job_id) ? globalThis.String(object.job_id) : "",
      message_id: isSet(object.message_id) ? globalThis.String(object.message_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      mode: isSet(object.mode) ? runModeFromJSON(object.mode) : 0,
      status: isSet(object.status) ? jobStatusFromJSON(object.status) : 0,
      entry_agent: isSet(object.entry_agent) ? globalThis.String(object.entry_agent) : "",
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
      current_step: isSet(object.current_step) ? globalThis.String(object.current_step) : undefined,
      error_message: isSet(object.error_message) ? globalThis.String(object.error_message) : undefined,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : undefined,
      updated_at: isSet(object.updated_at) ? globalThis.String(object.updated_at) : undefined,
      ended_at: isSet(object.ended_at) ? globalThis.String(object.ended_at) : undefined,
    };
  },

  toJSON(message: Job): unknown {
    const obj: any = {};
    if (message.job_id !== "") {
      obj.job_id = message.job_id;
    }
    if (message.message_id !== "") {
      obj.message_id = message.message_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.mode !== 0) {
      obj.mode = runModeToJSON(message.mode);
    }
    if (message.status !== 0) {
      obj.status = jobStatusToJSON(message.status);
    }
    if (message.entry_agent !== "") {
      obj.entry_agent = message.entry_agent;
    }
    if (message.progress !== 0) {
      obj.progress = Math.round(message.progress);
    }
    if (message.current_step !== undefined) {
      obj.current_step = message.current_step;
    }
    if (message.error_message !== undefined) {
      obj.error_message = message.error_message;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at;
    }
    if (message.updated_at !== undefined) {
      obj.updated_at = message.updated_at;
    }
    if (message.ended_at !== undefined) {
      obj.ended_at = message.ended_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Job>, I>>(base?: I): Job {
    return Job.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Job>, I>>(object: I): Job {
    const message = createBaseJob();
    message.job_id = object.job_id ?? "";
    message.message_id = object.message_id ?? "";
    message.session_id = object.session_id ?? "";
    message.mode = object.mode ?? 0;
    message.status = object.status ?? 0;
    message.entry_agent = object.entry_agent ?? "";
    message.progress = object.progress ?? 0;
    message.current_step = object.current_step ?? undefined;
    message.error_message = object.error_message ?? undefined;
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? undefined;
    message.updated_at = object.updated_at ?? undefined;
    message.ended_at = object.ended_at ?? undefined;
    return message;
  },
};

function createBaseJobProgress(): JobProgress {
  return { job_id: "", status: 0, current_step_id: undefined, progress: 0, message: undefined };
}

export const JobProgress: MessageFns<JobProgress> = {
  fromJSON(object: any): JobProgress {
    return {
      job_id: isSet(object.job_id) ? globalThis.String(object.job_id) : "",
      status: isSet(object.status) ? jobStatusFromJSON(object.status) : 0,
      current_step_id: isSet(object.current_step_id) ? globalThis.String(object.current_step_id) : undefined,
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
    };
  },

  toJSON(message: JobProgress): unknown {
    const obj: any = {};
    if (message.job_id !== "") {
      obj.job_id = message.job_id;
    }
    if (message.status !== 0) {
      obj.status = jobStatusToJSON(message.status);
    }
    if (message.current_step_id !== undefined) {
      obj.current_step_id = message.current_step_id;
    }
    if (message.progress !== 0) {
      obj.progress = Math.round(message.progress);
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobProgress>, I>>(base?: I): JobProgress {
    return JobProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobProgress>, I>>(object: I): JobProgress {
    const message = createBaseJobProgress();
    message.job_id = object.job_id ?? "";
    message.status = object.status ?? 0;
    message.current_step_id = object.current_step_id ?? undefined;
    message.progress = object.progress ?? 0;
    message.message = object.message ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
