// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/message.proto

/* eslint-disable */

export const protobufPackage = "boxteam.workspace.v2";

export enum MessageRole {
  MESSAGE_ROLE_UNSPECIFIED = 0,
  MESSAGE_ROLE_USER = 1,
  MESSAGE_ROLE_ASSISTANT = 2,
  MESSAGE_ROLE_SYSTEM = 3,
  MESSAGE_ROLE_TOOL = 4,
  UNRECOGNIZED = -1,
}

export function messageRoleFromJSON(object: any): MessageRole {
  switch (object) {
    case 0:
    case "MESSAGE_ROLE_UNSPECIFIED":
      return MessageRole.MESSAGE_ROLE_UNSPECIFIED;
    case 1:
    case "MESSAGE_ROLE_USER":
      return MessageRole.MESSAGE_ROLE_USER;
    case 2:
    case "MESSAGE_ROLE_ASSISTANT":
      return MessageRole.MESSAGE_ROLE_ASSISTANT;
    case 3:
    case "MESSAGE_ROLE_SYSTEM":
      return MessageRole.MESSAGE_ROLE_SYSTEM;
    case 4:
    case "MESSAGE_ROLE_TOOL":
      return MessageRole.MESSAGE_ROLE_TOOL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageRole.UNRECOGNIZED;
  }
}

export function messageRoleToJSON(object: MessageRole): string {
  switch (object) {
    case MessageRole.MESSAGE_ROLE_UNSPECIFIED:
      return "MESSAGE_ROLE_UNSPECIFIED";
    case MessageRole.MESSAGE_ROLE_USER:
      return "MESSAGE_ROLE_USER";
    case MessageRole.MESSAGE_ROLE_ASSISTANT:
      return "MESSAGE_ROLE_ASSISTANT";
    case MessageRole.MESSAGE_ROLE_SYSTEM:
      return "MESSAGE_ROLE_SYSTEM";
    case MessageRole.MESSAGE_ROLE_TOOL:
      return "MESSAGE_ROLE_TOOL";
    case MessageRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AttachmentRef {
  file_id: string;
  name?: string | undefined;
  content_type?: string | undefined;
  data_url?: string | undefined;
}

export interface Message {
  message_id: string;
  session_id: string;
  role: MessageRole;
  content: string;
  attachments: AttachmentRef[];
  metadata: { [key: string]: any } | undefined;
  created_at: string | undefined;
  updated_at: string | undefined;
}

function createBaseAttachmentRef(): AttachmentRef {
  return { file_id: "", name: undefined, content_type: undefined, data_url: undefined };
}

export const AttachmentRef: MessageFns<AttachmentRef> = {
  fromJSON(object: any): AttachmentRef {
    return {
      file_id: isSet(object.file_id) ? globalThis.String(object.file_id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      content_type: isSet(object.content_type) ? globalThis.String(object.content_type) : undefined,
      data_url: isSet(object.data_url) ? globalThis.String(object.data_url) : undefined,
    };
  },

  toJSON(message: AttachmentRef): unknown {
    const obj: any = {};
    if (message.file_id !== "") {
      obj.file_id = message.file_id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.content_type !== undefined) {
      obj.content_type = message.content_type;
    }
    if (message.data_url !== undefined) {
      obj.data_url = message.data_url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttachmentRef>, I>>(base?: I): AttachmentRef {
    return AttachmentRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttachmentRef>, I>>(object: I): AttachmentRef {
    const message = createBaseAttachmentRef();
    message.file_id = object.file_id ?? "";
    message.name = object.name ?? undefined;
    message.content_type = object.content_type ?? undefined;
    message.data_url = object.data_url ?? undefined;
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    message_id: "",
    session_id: "",
    role: 0,
    content: "",
    attachments: [],
    metadata: undefined,
    created_at: undefined,
    updated_at: undefined,
  };
}

export const Message: MessageFns<Message> = {
  fromJSON(object: any): Message {
    return {
      message_id: isSet(object.message_id) ? globalThis.String(object.message_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      role: isSet(object.role) ? messageRoleFromJSON(object.role) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      attachments: globalThis.Array.isArray(object?.attachments)
        ? object.attachments.map((e: any) => AttachmentRef.fromJSON(e))
        : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : undefined,
      updated_at: isSet(object.updated_at) ? globalThis.String(object.updated_at) : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.message_id !== "") {
      obj.message_id = message.message_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.role !== 0) {
      obj.role = messageRoleToJSON(message.role);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.attachments?.length) {
      obj.attachments = message.attachments.map((e) => AttachmentRef.toJSON(e));
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at;
    }
    if (message.updated_at !== undefined) {
      obj.updated_at = message.updated_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.message_id = object.message_id ?? "";
    message.session_id = object.session_id ?? "";
    message.role = object.role ?? 0;
    message.content = object.content ?? "";
    message.attachments = object.attachments?.map((e) => AttachmentRef.fromPartial(e)) || [];
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? undefined;
    message.updated_at = object.updated_at ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
