// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/session_stream.proto

/* eslint-disable */
import { SessionExecutionEvent } from "./session_interaction.js";

export const protobufPackage = "boxteam.workspace.v2";

export interface SessionExecutionSse {
  event: SessionExecutionEvent | undefined;
  raw_type: string;
  raw_payload: { [key: string]: any } | undefined;
}

function createBaseSessionExecutionSse(): SessionExecutionSse {
  return { event: undefined, raw_type: "", raw_payload: undefined };
}

export const SessionExecutionSse: MessageFns<SessionExecutionSse> = {
  fromJSON(object: any): SessionExecutionSse {
    return {
      event: isSet(object.event) ? SessionExecutionEvent.fromJSON(object.event) : undefined,
      raw_type: isSet(object.raw_type) ? globalThis.String(object.raw_type) : "",
      raw_payload: isObject(object.raw_payload) ? object.raw_payload : undefined,
    };
  },

  toJSON(message: SessionExecutionSse): unknown {
    const obj: any = {};
    if (message.event !== undefined) {
      obj.event = SessionExecutionEvent.toJSON(message.event);
    }
    if (message.raw_type !== "") {
      obj.raw_type = message.raw_type;
    }
    if (message.raw_payload !== undefined) {
      obj.raw_payload = message.raw_payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionExecutionSse>, I>>(base?: I): SessionExecutionSse {
    return SessionExecutionSse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionExecutionSse>, I>>(object: I): SessionExecutionSse {
    const message = createBaseSessionExecutionSse();
    message.event = (object.event !== undefined && object.event !== null)
      ? SessionExecutionEvent.fromPartial(object.event)
      : undefined;
    message.raw_type = object.raw_type ?? "";
    message.raw_payload = object.raw_payload ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
