// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/session_interaction.proto

/* eslint-disable */
import { JobProgress } from "./job.js";

export const protobufPackage = "boxteam.workspace.v2";

export interface SessionExecutionEventHeader {
  event_id: string;
  session_id: string;
  job_id?: string | undefined;
  time: string | undefined;
}

export interface MessageObservation {
  message_id: string;
  session_id: string;
  role: string;
  content: string;
  attachments: any[];
  metadata: { [key: string]: any } | undefined;
  created_at: string | undefined;
}

export interface JobStepProgress {
  agent_id?: string | undefined;
  message?: string | undefined;
  phase?: string | undefined;
}

export interface SessionStatus {
  session_id: string;
  status: string;
  message?: string | undefined;
  active_job_id?: string | undefined;
  observation_state?: string | undefined;
  is_streaming: boolean;
  is_idle: boolean;
  waiting: { [key: string]: any } | undefined;
}

export interface SessionError {
  error: string;
}

export interface TraceObserved {
  raw_type: string;
}

export interface SessionExecutionEvent {
  type: string;
  header: SessionExecutionEventHeader | undefined;
  payload:
    | { $case: "message_updated"; message_updated: MessageObservation }
    | { $case: "job_updated"; job_updated: JobProgress }
    | { $case: "job_step_updated"; job_step_updated: JobStepProgress }
    | { $case: "job_status_changed"; job_status_changed: JobProgress }
    | { $case: "session_status_changed"; session_status_changed: SessionStatus }
    | { $case: "session_completed"; session_completed: JobProgress }
    | { $case: "session_error"; session_error: SessionError }
    | { $case: "trace_observed"; trace_observed: TraceObserved }
    | undefined;
}

function createBaseSessionExecutionEventHeader(): SessionExecutionEventHeader {
  return { event_id: "", session_id: "", job_id: undefined, time: undefined };
}

export const SessionExecutionEventHeader: MessageFns<SessionExecutionEventHeader> = {
  fromJSON(object: any): SessionExecutionEventHeader {
    return {
      event_id: isSet(object.event_id) ? globalThis.String(object.event_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      job_id: isSet(object.job_id) ? globalThis.String(object.job_id) : undefined,
      time: isSet(object.time) ? globalThis.String(object.time) : undefined,
    };
  },

  toJSON(message: SessionExecutionEventHeader): unknown {
    const obj: any = {};
    if (message.event_id !== "") {
      obj.event_id = message.event_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.job_id !== undefined) {
      obj.job_id = message.job_id;
    }
    if (message.time !== undefined) {
      obj.time = message.time;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionExecutionEventHeader>, I>>(base?: I): SessionExecutionEventHeader {
    return SessionExecutionEventHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionExecutionEventHeader>, I>>(object: I): SessionExecutionEventHeader {
    const message = createBaseSessionExecutionEventHeader();
    message.event_id = object.event_id ?? "";
    message.session_id = object.session_id ?? "";
    message.job_id = object.job_id ?? undefined;
    message.time = object.time ?? undefined;
    return message;
  },
};

function createBaseMessageObservation(): MessageObservation {
  return {
    message_id: "",
    session_id: "",
    role: "",
    content: "",
    attachments: [],
    metadata: undefined,
    created_at: undefined,
  };
}

export const MessageObservation: MessageFns<MessageObservation> = {
  fromJSON(object: any): MessageObservation {
    return {
      message_id: isSet(object.message_id) ? globalThis.String(object.message_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      attachments: globalThis.Array.isArray(object?.attachments) ? [...object.attachments] : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : undefined,
    };
  },

  toJSON(message: MessageObservation): unknown {
    const obj: any = {};
    if (message.message_id !== "") {
      obj.message_id = message.message_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.attachments?.length) {
      obj.attachments = message.attachments;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageObservation>, I>>(base?: I): MessageObservation {
    return MessageObservation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageObservation>, I>>(object: I): MessageObservation {
    const message = createBaseMessageObservation();
    message.message_id = object.message_id ?? "";
    message.session_id = object.session_id ?? "";
    message.role = object.role ?? "";
    message.content = object.content ?? "";
    message.attachments = object.attachments?.map((e) => e) || [];
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? undefined;
    return message;
  },
};

function createBaseJobStepProgress(): JobStepProgress {
  return { agent_id: undefined, message: undefined, phase: undefined };
}

export const JobStepProgress: MessageFns<JobStepProgress> = {
  fromJSON(object: any): JobStepProgress {
    return {
      agent_id: isSet(object.agent_id) ? globalThis.String(object.agent_id) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
      phase: isSet(object.phase) ? globalThis.String(object.phase) : undefined,
    };
  },

  toJSON(message: JobStepProgress): unknown {
    const obj: any = {};
    if (message.agent_id !== undefined) {
      obj.agent_id = message.agent_id;
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    if (message.phase !== undefined) {
      obj.phase = message.phase;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobStepProgress>, I>>(base?: I): JobStepProgress {
    return JobStepProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobStepProgress>, I>>(object: I): JobStepProgress {
    const message = createBaseJobStepProgress();
    message.agent_id = object.agent_id ?? undefined;
    message.message = object.message ?? undefined;
    message.phase = object.phase ?? undefined;
    return message;
  },
};

function createBaseSessionStatus(): SessionStatus {
  return {
    session_id: "",
    status: "",
    message: undefined,
    active_job_id: undefined,
    observation_state: undefined,
    is_streaming: false,
    is_idle: false,
    waiting: undefined,
  };
}

export const SessionStatus: MessageFns<SessionStatus> = {
  fromJSON(object: any): SessionStatus {
    return {
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
      active_job_id: isSet(object.active_job_id) ? globalThis.String(object.active_job_id) : undefined,
      observation_state: isSet(object.observation_state) ? globalThis.String(object.observation_state) : undefined,
      is_streaming: isSet(object.is_streaming) ? globalThis.Boolean(object.is_streaming) : false,
      is_idle: isSet(object.is_idle) ? globalThis.Boolean(object.is_idle) : false,
      waiting: isObject(object.waiting) ? object.waiting : undefined,
    };
  },

  toJSON(message: SessionStatus): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    if (message.active_job_id !== undefined) {
      obj.active_job_id = message.active_job_id;
    }
    if (message.observation_state !== undefined) {
      obj.observation_state = message.observation_state;
    }
    if (message.is_streaming !== false) {
      obj.is_streaming = message.is_streaming;
    }
    if (message.is_idle !== false) {
      obj.is_idle = message.is_idle;
    }
    if (message.waiting !== undefined) {
      obj.waiting = message.waiting;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionStatus>, I>>(base?: I): SessionStatus {
    return SessionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionStatus>, I>>(object: I): SessionStatus {
    const message = createBaseSessionStatus();
    message.session_id = object.session_id ?? "";
    message.status = object.status ?? "";
    message.message = object.message ?? undefined;
    message.active_job_id = object.active_job_id ?? undefined;
    message.observation_state = object.observation_state ?? undefined;
    message.is_streaming = object.is_streaming ?? false;
    message.is_idle = object.is_idle ?? false;
    message.waiting = object.waiting ?? undefined;
    return message;
  },
};

function createBaseSessionError(): SessionError {
  return { error: "" };
}

export const SessionError: MessageFns<SessionError> = {
  fromJSON(object: any): SessionError {
    return { error: isSet(object.error) ? globalThis.String(object.error) : "" };
  },

  toJSON(message: SessionError): unknown {
    const obj: any = {};
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionError>, I>>(base?: I): SessionError {
    return SessionError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionError>, I>>(object: I): SessionError {
    const message = createBaseSessionError();
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseTraceObserved(): TraceObserved {
  return { raw_type: "" };
}

export const TraceObserved: MessageFns<TraceObserved> = {
  fromJSON(object: any): TraceObserved {
    return { raw_type: isSet(object.raw_type) ? globalThis.String(object.raw_type) : "" };
  },

  toJSON(message: TraceObserved): unknown {
    const obj: any = {};
    if (message.raw_type !== "") {
      obj.raw_type = message.raw_type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TraceObserved>, I>>(base?: I): TraceObserved {
    return TraceObserved.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TraceObserved>, I>>(object: I): TraceObserved {
    const message = createBaseTraceObserved();
    message.raw_type = object.raw_type ?? "";
    return message;
  },
};

function createBaseSessionExecutionEvent(): SessionExecutionEvent {
  return { type: "", header: undefined, payload: undefined };
}

export const SessionExecutionEvent: MessageFns<SessionExecutionEvent> = {
  fromJSON(object: any): SessionExecutionEvent {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      header: isSet(object.header) ? SessionExecutionEventHeader.fromJSON(object.header) : undefined,
      payload: isSet(object.message_updated)
        ? { $case: "message_updated", message_updated: MessageObservation.fromJSON(object.message_updated) }
        : isSet(object.job_updated)
        ? { $case: "job_updated", job_updated: JobProgress.fromJSON(object.job_updated) }
        : isSet(object.job_step_updated)
        ? { $case: "job_step_updated", job_step_updated: JobStepProgress.fromJSON(object.job_step_updated) }
        : isSet(object.job_status_changed)
        ? { $case: "job_status_changed", job_status_changed: JobProgress.fromJSON(object.job_status_changed) }
        : isSet(object.session_status_changed)
        ? {
          $case: "session_status_changed",
          session_status_changed: SessionStatus.fromJSON(object.session_status_changed),
        }
        : isSet(object.session_completed)
        ? { $case: "session_completed", session_completed: JobProgress.fromJSON(object.session_completed) }
        : isSet(object.session_error)
        ? { $case: "session_error", session_error: SessionError.fromJSON(object.session_error) }
        : isSet(object.trace_observed)
        ? { $case: "trace_observed", trace_observed: TraceObserved.fromJSON(object.trace_observed) }
        : undefined,
    };
  },

  toJSON(message: SessionExecutionEvent): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.header !== undefined) {
      obj.header = SessionExecutionEventHeader.toJSON(message.header);
    }
    if (message.payload?.$case === "message_updated") {
      obj.message_updated = MessageObservation.toJSON(message.payload.message_updated);
    } else if (message.payload?.$case === "job_updated") {
      obj.job_updated = JobProgress.toJSON(message.payload.job_updated);
    } else if (message.payload?.$case === "job_step_updated") {
      obj.job_step_updated = JobStepProgress.toJSON(message.payload.job_step_updated);
    } else if (message.payload?.$case === "job_status_changed") {
      obj.job_status_changed = JobProgress.toJSON(message.payload.job_status_changed);
    } else if (message.payload?.$case === "session_status_changed") {
      obj.session_status_changed = SessionStatus.toJSON(message.payload.session_status_changed);
    } else if (message.payload?.$case === "session_completed") {
      obj.session_completed = JobProgress.toJSON(message.payload.session_completed);
    } else if (message.payload?.$case === "session_error") {
      obj.session_error = SessionError.toJSON(message.payload.session_error);
    } else if (message.payload?.$case === "trace_observed") {
      obj.trace_observed = TraceObserved.toJSON(message.payload.trace_observed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionExecutionEvent>, I>>(base?: I): SessionExecutionEvent {
    return SessionExecutionEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionExecutionEvent>, I>>(object: I): SessionExecutionEvent {
    const message = createBaseSessionExecutionEvent();
    message.type = object.type ?? "";
    message.header = (object.header !== undefined && object.header !== null)
      ? SessionExecutionEventHeader.fromPartial(object.header)
      : undefined;
    switch (object.payload?.$case) {
      case "message_updated": {
        if (object.payload?.message_updated !== undefined && object.payload?.message_updated !== null) {
          message.payload = {
            $case: "message_updated",
            message_updated: MessageObservation.fromPartial(object.payload.message_updated),
          };
        }
        break;
      }
      case "job_updated": {
        if (object.payload?.job_updated !== undefined && object.payload?.job_updated !== null) {
          message.payload = { $case: "job_updated", job_updated: JobProgress.fromPartial(object.payload.job_updated) };
        }
        break;
      }
      case "job_step_updated": {
        if (object.payload?.job_step_updated !== undefined && object.payload?.job_step_updated !== null) {
          message.payload = {
            $case: "job_step_updated",
            job_step_updated: JobStepProgress.fromPartial(object.payload.job_step_updated),
          };
        }
        break;
      }
      case "job_status_changed": {
        if (object.payload?.job_status_changed !== undefined && object.payload?.job_status_changed !== null) {
          message.payload = {
            $case: "job_status_changed",
            job_status_changed: JobProgress.fromPartial(object.payload.job_status_changed),
          };
        }
        break;
      }
      case "session_status_changed": {
        if (object.payload?.session_status_changed !== undefined && object.payload?.session_status_changed !== null) {
          message.payload = {
            $case: "session_status_changed",
            session_status_changed: SessionStatus.fromPartial(object.payload.session_status_changed),
          };
        }
        break;
      }
      case "session_completed": {
        if (object.payload?.session_completed !== undefined && object.payload?.session_completed !== null) {
          message.payload = {
            $case: "session_completed",
            session_completed: JobProgress.fromPartial(object.payload.session_completed),
          };
        }
        break;
      }
      case "session_error": {
        if (object.payload?.session_error !== undefined && object.payload?.session_error !== null) {
          message.payload = {
            $case: "session_error",
            session_error: SessionError.fromPartial(object.payload.session_error),
          };
        }
        break;
      }
      case "trace_observed": {
        if (object.payload?.trace_observed !== undefined && object.payload?.trace_observed !== null) {
          message.payload = {
            $case: "trace_observed",
            trace_observed: TraceObserved.fromPartial(object.payload.trace_observed),
          };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
