// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/workspace/v2/trace.proto

/* eslint-disable */

export const protobufPackage = "boxteam.workspace.v2";

export interface TraceEvent {
  event_id: string;
  part_id?: string | undefined;
  session_id: string;
  job_id: string;
  type: string;
  phase: string;
  title: string;
  content: string;
  status?: string | undefined;
  tool_name?: string | undefined;
  skill_names: string[];
  step_id?: string | undefined;
  timestamp: string | undefined;
  raw: { [key: string]: any } | undefined;
}

function createBaseTraceEvent(): TraceEvent {
  return {
    event_id: "",
    part_id: undefined,
    session_id: "",
    job_id: "",
    type: "",
    phase: "",
    title: "",
    content: "",
    status: undefined,
    tool_name: undefined,
    skill_names: [],
    step_id: undefined,
    timestamp: undefined,
    raw: undefined,
  };
}

export const TraceEvent: MessageFns<TraceEvent> = {
  fromJSON(object: any): TraceEvent {
    return {
      event_id: isSet(object.event_id) ? globalThis.String(object.event_id) : "",
      part_id: isSet(object.part_id) ? globalThis.String(object.part_id) : undefined,
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      job_id: isSet(object.job_id) ? globalThis.String(object.job_id) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
      tool_name: isSet(object.tool_name) ? globalThis.String(object.tool_name) : undefined,
      skill_names: globalThis.Array.isArray(object?.skill_names)
        ? object.skill_names.map((e: any) => globalThis.String(e))
        : [],
      step_id: isSet(object.step_id) ? globalThis.String(object.step_id) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : undefined,
      raw: isObject(object.raw) ? object.raw : undefined,
    };
  },

  toJSON(message: TraceEvent): unknown {
    const obj: any = {};
    if (message.event_id !== "") {
      obj.event_id = message.event_id;
    }
    if (message.part_id !== undefined) {
      obj.part_id = message.part_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.job_id !== "") {
      obj.job_id = message.job_id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    if (message.tool_name !== undefined) {
      obj.tool_name = message.tool_name;
    }
    if (message.skill_names?.length) {
      obj.skill_names = message.skill_names;
    }
    if (message.step_id !== undefined) {
      obj.step_id = message.step_id;
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp;
    }
    if (message.raw !== undefined) {
      obj.raw = message.raw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TraceEvent>, I>>(base?: I): TraceEvent {
    return TraceEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TraceEvent>, I>>(object: I): TraceEvent {
    const message = createBaseTraceEvent();
    message.event_id = object.event_id ?? "";
    message.part_id = object.part_id ?? undefined;
    message.session_id = object.session_id ?? "";
    message.job_id = object.job_id ?? "";
    message.type = object.type ?? "";
    message.phase = object.phase ?? "";
    message.title = object.title ?? "";
    message.content = object.content ?? "";
    message.status = object.status ?? undefined;
    message.tool_name = object.tool_name ?? undefined;
    message.skill_names = object.skill_names?.map((e) => e) || [];
    message.step_id = object.step_id ?? undefined;
    message.timestamp = object.timestamp ?? undefined;
    message.raw = object.raw ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
