// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file boxteam/terminal/v1/terminal_input.proto (package boxteam.terminal.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_boxteam_terminal_v1_terminal } from "./terminal_pb.js";

/**
 * Describes the file boxteam/terminal/v1/terminal_input.proto.
 */
export const file_boxteam_terminal_v1_terminal_input = /*@__PURE__*/
  fileDesc("Cihib3h0ZWFtL3Rlcm1pbmFsL3YxL3Rlcm1pbmFsX2lucHV0LnByb3RvEhNib3h0ZWFtLnRlcm1pbmFsLnYxIo0BCg5UZXJtaW5hbEF0dGFjaBITCgt0ZXJtaW5hbF9pZBgBIAEoCRIRCgRjb2xzGAIgASgNSACIAQESEQoEcm93cxgDIAEoDUgBiAEBEhsKDmFmdGVyX3NlcXVlbmNlGAQgASgNSAKIAQFCBwoFX2NvbHNCBwoFX3Jvd3NCEQoPX2FmdGVyX3NlcXVlbmNlIjoKDlRlcm1pbmFsRGV0YWNoEhgKC3Rlcm1pbmFsX2lkGAEgASgJSACIAQFCDgoMX3Rlcm1pbmFsX2lkIi0KDVRlcm1pbmFsSW5wdXQSDAoEZGF0YRgBIAEoCRIOCgZzb3VyY2UYAiABKAkiLAoOVGVybWluYWxSZXNpemUSDAoEY29scxgBIAEoDRIMCgRyb3dzGAIgASgNIicKE1Rlcm1pbmFsQWNrbm93bGVkZ2USEAoIc2VxdWVuY2UYASABKA0isgMKFVRlcm1pbmFsQ2xpZW50TWVzc2FnZRI1CgZhdHRhY2gYASABKAsyIy5ib3h0ZWFtLnRlcm1pbmFsLnYxLlRlcm1pbmFsQXR0YWNoSAASNQoGZGV0YWNoGAIgASgLMiMuYm94dGVhbS50ZXJtaW5hbC52MS5UZXJtaW5hbERldGFjaEgAEjMKBWlucHV0GAMgASgLMiIuYm94dGVhbS50ZXJtaW5hbC52MS5UZXJtaW5hbElucHV0SAASOQoLYWdlbnRfaW5wdXQYBCABKAsyIi5ib3h0ZWFtLnRlcm1pbmFsLnYxLlRlcm1pbmFsSW5wdXRIABI1CgZyZXNpemUYBSABKAsyIy5ib3h0ZWFtLnRlcm1pbmFsLnYxLlRlcm1pbmFsUmVzaXplSAASPwoLYWNrbm93bGVkZ2UYBiABKAsyKC5ib3h0ZWFtLnRlcm1pbmFsLnYxLlRlcm1pbmFsQWNrbm93bGVkZ2VIABI4CgRqc29uGAcgASgLMiguYm94dGVhbS50ZXJtaW5hbC52MS5UZXJtaW5hbEpzb25NZXNzYWdlSABCCQoHcGF5bG9hZGIGcHJvdG8z", [file_boxteam_terminal_v1_terminal]);

/**
 * Describes the message boxteam.terminal.v1.TerminalAttach.
 * Use `create(TerminalAttachSchema)` to create a new message.
 */
export const TerminalAttachSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 0);

/**
 * Describes the message boxteam.terminal.v1.TerminalDetach.
 * Use `create(TerminalDetachSchema)` to create a new message.
 */
export const TerminalDetachSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 1);

/**
 * Describes the message boxteam.terminal.v1.TerminalInput.
 * Use `create(TerminalInputSchema)` to create a new message.
 */
export const TerminalInputSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 2);

/**
 * Describes the message boxteam.terminal.v1.TerminalResize.
 * Use `create(TerminalResizeSchema)` to create a new message.
 */
export const TerminalResizeSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 3);

/**
 * Describes the message boxteam.terminal.v1.TerminalAcknowledge.
 * Use `create(TerminalAcknowledgeSchema)` to create a new message.
 */
export const TerminalAcknowledgeSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 4);

/**
 * Describes the message boxteam.terminal.v1.TerminalClientMessage.
 * Use `create(TerminalClientMessageSchema)` to create a new message.
 */
export const TerminalClientMessageSchema = /*@__PURE__*/
  messageDesc(file_boxteam_terminal_v1_terminal_input, 5);

