// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/browser/v1/browser.proto

/* eslint-disable */

export const protobufPackage = "boxteam.browser.v1";

export enum BrowserStatus {
  BROWSER_STATUS_UNSPECIFIED = 0,
  BROWSER_STATUS_CREATED = 1,
  BROWSER_STATUS_RUNNING = 2,
  BROWSER_STATUS_FROZEN = 3,
  BROWSER_STATUS_DISCARDED = 4,
  BROWSER_STATUS_LOST = 5,
  BROWSER_STATUS_CLOSED = 6,
  BROWSER_STATUS_DELETED = 7,
  BROWSER_STATUS_FAILED = 8,
  UNRECOGNIZED = -1,
}

export function browserStatusFromJSON(object: any): BrowserStatus {
  switch (object) {
    case 0:
    case "BROWSER_STATUS_UNSPECIFIED":
      return BrowserStatus.BROWSER_STATUS_UNSPECIFIED;
    case 1:
    case "BROWSER_STATUS_CREATED":
      return BrowserStatus.BROWSER_STATUS_CREATED;
    case 2:
    case "BROWSER_STATUS_RUNNING":
      return BrowserStatus.BROWSER_STATUS_RUNNING;
    case 3:
    case "BROWSER_STATUS_FROZEN":
      return BrowserStatus.BROWSER_STATUS_FROZEN;
    case 4:
    case "BROWSER_STATUS_DISCARDED":
      return BrowserStatus.BROWSER_STATUS_DISCARDED;
    case 5:
    case "BROWSER_STATUS_LOST":
      return BrowserStatus.BROWSER_STATUS_LOST;
    case 6:
    case "BROWSER_STATUS_CLOSED":
      return BrowserStatus.BROWSER_STATUS_CLOSED;
    case 7:
    case "BROWSER_STATUS_DELETED":
      return BrowserStatus.BROWSER_STATUS_DELETED;
    case 8:
    case "BROWSER_STATUS_FAILED":
      return BrowserStatus.BROWSER_STATUS_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BrowserStatus.UNRECOGNIZED;
  }
}

export function browserStatusToJSON(object: BrowserStatus): string {
  switch (object) {
    case BrowserStatus.BROWSER_STATUS_UNSPECIFIED:
      return "BROWSER_STATUS_UNSPECIFIED";
    case BrowserStatus.BROWSER_STATUS_CREATED:
      return "BROWSER_STATUS_CREATED";
    case BrowserStatus.BROWSER_STATUS_RUNNING:
      return "BROWSER_STATUS_RUNNING";
    case BrowserStatus.BROWSER_STATUS_FROZEN:
      return "BROWSER_STATUS_FROZEN";
    case BrowserStatus.BROWSER_STATUS_DISCARDED:
      return "BROWSER_STATUS_DISCARDED";
    case BrowserStatus.BROWSER_STATUS_LOST:
      return "BROWSER_STATUS_LOST";
    case BrowserStatus.BROWSER_STATUS_CLOSED:
      return "BROWSER_STATUS_CLOSED";
    case BrowserStatus.BROWSER_STATUS_DELETED:
      return "BROWSER_STATUS_DELETED";
    case BrowserStatus.BROWSER_STATUS_FAILED:
      return "BROWSER_STATUS_FAILED";
    case BrowserStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface BrowserViewport {
  width: number;
  height: number;
}

export interface BrowserPage {
  browser_id: string;
  page_id: string;
  session_id: string;
  title: string;
  url: string;
  viewport: BrowserViewport | undefined;
  status: BrowserStatus;
  sequence: number;
  metadata: { [key: string]: any } | undefined;
  created_at: string | undefined;
  updated_at: string | undefined;
}

export interface BrowserJsonMessage {
  type: string;
  payload: { [key: string]: any } | undefined;
}

function createBaseBrowserViewport(): BrowserViewport {
  return { width: 0, height: 0 };
}

export const BrowserViewport: MessageFns<BrowserViewport> = {
  fromJSON(object: any): BrowserViewport {
    return {
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    };
  },

  toJSON(message: BrowserViewport): unknown {
    const obj: any = {};
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserViewport>, I>>(base?: I): BrowserViewport {
    return BrowserViewport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserViewport>, I>>(object: I): BrowserViewport {
    const message = createBaseBrowserViewport();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseBrowserPage(): BrowserPage {
  return {
    browser_id: "",
    page_id: "",
    session_id: "",
    title: "",
    url: "",
    viewport: undefined,
    status: 0,
    sequence: 0,
    metadata: undefined,
    created_at: undefined,
    updated_at: undefined,
  };
}

export const BrowserPage: MessageFns<BrowserPage> = {
  fromJSON(object: any): BrowserPage {
    return {
      browser_id: isSet(object.browser_id) ? globalThis.String(object.browser_id) : "",
      page_id: isSet(object.page_id) ? globalThis.String(object.page_id) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      viewport: isSet(object.viewport) ? BrowserViewport.fromJSON(object.viewport) : undefined,
      status: isSet(object.status) ? browserStatusFromJSON(object.status) : 0,
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : undefined,
      updated_at: isSet(object.updated_at) ? globalThis.String(object.updated_at) : undefined,
    };
  },

  toJSON(message: BrowserPage): unknown {
    const obj: any = {};
    if (message.browser_id !== "") {
      obj.browser_id = message.browser_id;
    }
    if (message.page_id !== "") {
      obj.page_id = message.page_id;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.viewport !== undefined) {
      obj.viewport = BrowserViewport.toJSON(message.viewport);
    }
    if (message.status !== 0) {
      obj.status = browserStatusToJSON(message.status);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at;
    }
    if (message.updated_at !== undefined) {
      obj.updated_at = message.updated_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserPage>, I>>(base?: I): BrowserPage {
    return BrowserPage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserPage>, I>>(object: I): BrowserPage {
    const message = createBaseBrowserPage();
    message.browser_id = object.browser_id ?? "";
    message.page_id = object.page_id ?? "";
    message.session_id = object.session_id ?? "";
    message.title = object.title ?? "";
    message.url = object.url ?? "";
    message.viewport = (object.viewport !== undefined && object.viewport !== null)
      ? BrowserViewport.fromPartial(object.viewport)
      : undefined;
    message.status = object.status ?? 0;
    message.sequence = object.sequence ?? 0;
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? undefined;
    message.updated_at = object.updated_at ?? undefined;
    return message;
  },
};

function createBaseBrowserJsonMessage(): BrowserJsonMessage {
  return { type: "", payload: undefined };
}

export const BrowserJsonMessage: MessageFns<BrowserJsonMessage> = {
  fromJSON(object: any): BrowserJsonMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      payload: isObject(object.payload) ? object.payload : undefined,
    };
  },

  toJSON(message: BrowserJsonMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserJsonMessage>, I>>(base?: I): BrowserJsonMessage {
    return BrowserJsonMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserJsonMessage>, I>>(object: I): BrowserJsonMessage {
    const message = createBaseBrowserJsonMessage();
    message.type = object.type ?? "";
    message.payload = object.payload ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
