// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/browser/v1/browser_page.proto

/* eslint-disable */
import { Error } from "../../common/v1/error.js";
import { BrowserJsonMessage, BrowserPage } from "./browser.js";

export const protobufPackage = "boxteam.browser.v1";

export interface BrowserPageState {
  page: BrowserPage | undefined;
}

export interface BrowserFrame {
  frame_id: string;
  sequence: number;
  data: Uint8Array;
  content_type: string;
}

export interface BrowserDownloadReady {
  download_id: string;
  filename: string;
  content_type: string;
}

export interface BrowserServerMessage {
  payload:
    | { $case: "page_state"; page_state: BrowserPageState }
    | { $case: "frame"; frame: BrowserFrame }
    | { $case: "download_ready"; download_ready: BrowserDownloadReady }
    | { $case: "error"; error: Error }
    | { $case: "json"; json: BrowserJsonMessage }
    | undefined;
}

function createBaseBrowserPageState(): BrowserPageState {
  return { page: undefined };
}

export const BrowserPageState: MessageFns<BrowserPageState> = {
  fromJSON(object: any): BrowserPageState {
    return { page: isSet(object.page) ? BrowserPage.fromJSON(object.page) : undefined };
  },

  toJSON(message: BrowserPageState): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = BrowserPage.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserPageState>, I>>(base?: I): BrowserPageState {
    return BrowserPageState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserPageState>, I>>(object: I): BrowserPageState {
    const message = createBaseBrowserPageState();
    message.page = (object.page !== undefined && object.page !== null)
      ? BrowserPage.fromPartial(object.page)
      : undefined;
    return message;
  },
};

function createBaseBrowserFrame(): BrowserFrame {
  return { frame_id: "", sequence: 0, data: new Uint8Array(0), content_type: "" };
}

export const BrowserFrame: MessageFns<BrowserFrame> = {
  fromJSON(object: any): BrowserFrame {
    return {
      frame_id: isSet(object.frame_id) ? globalThis.String(object.frame_id) : "",
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      content_type: isSet(object.content_type) ? globalThis.String(object.content_type) : "",
    };
  },

  toJSON(message: BrowserFrame): unknown {
    const obj: any = {};
    if (message.frame_id !== "") {
      obj.frame_id = message.frame_id;
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.content_type !== "") {
      obj.content_type = message.content_type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserFrame>, I>>(base?: I): BrowserFrame {
    return BrowserFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserFrame>, I>>(object: I): BrowserFrame {
    const message = createBaseBrowserFrame();
    message.frame_id = object.frame_id ?? "";
    message.sequence = object.sequence ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    message.content_type = object.content_type ?? "";
    return message;
  },
};

function createBaseBrowserDownloadReady(): BrowserDownloadReady {
  return { download_id: "", filename: "", content_type: "" };
}

export const BrowserDownloadReady: MessageFns<BrowserDownloadReady> = {
  fromJSON(object: any): BrowserDownloadReady {
    return {
      download_id: isSet(object.download_id) ? globalThis.String(object.download_id) : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      content_type: isSet(object.content_type) ? globalThis.String(object.content_type) : "",
    };
  },

  toJSON(message: BrowserDownloadReady): unknown {
    const obj: any = {};
    if (message.download_id !== "") {
      obj.download_id = message.download_id;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.content_type !== "") {
      obj.content_type = message.content_type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserDownloadReady>, I>>(base?: I): BrowserDownloadReady {
    return BrowserDownloadReady.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserDownloadReady>, I>>(object: I): BrowserDownloadReady {
    const message = createBaseBrowserDownloadReady();
    message.download_id = object.download_id ?? "";
    message.filename = object.filename ?? "";
    message.content_type = object.content_type ?? "";
    return message;
  },
};

function createBaseBrowserServerMessage(): BrowserServerMessage {
  return { payload: undefined };
}

export const BrowserServerMessage: MessageFns<BrowserServerMessage> = {
  fromJSON(object: any): BrowserServerMessage {
    return {
      payload: isSet(object.page_state)
        ? { $case: "page_state", page_state: BrowserPageState.fromJSON(object.page_state) }
        : isSet(object.frame)
        ? { $case: "frame", frame: BrowserFrame.fromJSON(object.frame) }
        : isSet(object.download_ready)
        ? { $case: "download_ready", download_ready: BrowserDownloadReady.fromJSON(object.download_ready) }
        : isSet(object.error)
        ? { $case: "error", error: Error.fromJSON(object.error) }
        : isSet(object.json)
        ? { $case: "json", json: BrowserJsonMessage.fromJSON(object.json) }
        : undefined,
    };
  },

  toJSON(message: BrowserServerMessage): unknown {
    const obj: any = {};
    if (message.payload?.$case === "page_state") {
      obj.page_state = BrowserPageState.toJSON(message.payload.page_state);
    } else if (message.payload?.$case === "frame") {
      obj.frame = BrowserFrame.toJSON(message.payload.frame);
    } else if (message.payload?.$case === "download_ready") {
      obj.download_ready = BrowserDownloadReady.toJSON(message.payload.download_ready);
    } else if (message.payload?.$case === "error") {
      obj.error = Error.toJSON(message.payload.error);
    } else if (message.payload?.$case === "json") {
      obj.json = BrowserJsonMessage.toJSON(message.payload.json);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserServerMessage>, I>>(base?: I): BrowserServerMessage {
    return BrowserServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserServerMessage>, I>>(object: I): BrowserServerMessage {
    const message = createBaseBrowserServerMessage();
    switch (object.payload?.$case) {
      case "page_state": {
        if (object.payload?.page_state !== undefined && object.payload?.page_state !== null) {
          message.payload = {
            $case: "page_state",
            page_state: BrowserPageState.fromPartial(object.payload.page_state),
          };
        }
        break;
      }
      case "frame": {
        if (object.payload?.frame !== undefined && object.payload?.frame !== null) {
          message.payload = { $case: "frame", frame: BrowserFrame.fromPartial(object.payload.frame) };
        }
        break;
      }
      case "download_ready": {
        if (object.payload?.download_ready !== undefined && object.payload?.download_ready !== null) {
          message.payload = {
            $case: "download_ready",
            download_ready: BrowserDownloadReady.fromPartial(object.payload.download_ready),
          };
        }
        break;
      }
      case "error": {
        if (object.payload?.error !== undefined && object.payload?.error !== null) {
          message.payload = { $case: "error", error: Error.fromPartial(object.payload.error) };
        }
        break;
      }
      case "json": {
        if (object.payload?.json !== undefined && object.payload?.json !== null) {
          message.payload = { $case: "json", json: BrowserJsonMessage.fromPartial(object.payload.json) };
        }
        break;
      }
    }
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
