// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: boxteam/browser/v1/browser_input.proto

/* eslint-disable */
import { BrowserJsonMessage } from "./browser.js";

export const protobufPackage = "boxteam.browser.v1";

export interface BrowserAttach {
  browser_id: string;
  participant_id?: string | undefined;
}

export interface BrowserDetach {
  browser_id?: string | undefined;
}

export interface BrowserPointer {
  action: string;
  x: number;
  y: number;
  button: string;
  delta_x: number;
  delta_y: number;
}

export interface BrowserKey {
  action: string;
  key: string;
  code: string;
  text?: string | undefined;
  repeat: boolean;
}

export interface BrowserCommand {
  name: string;
  value: string;
}

export interface BrowserViewportUpdate {
  width: number;
  height: number;
}

export interface BrowserFrameAcknowledge {
  frame_id: number;
  received_bytes: number;
}

export interface BrowserClientMessage {
  payload:
    | { $case: "attach"; attach: BrowserAttach }
    | { $case: "detach"; detach: BrowserDetach }
    | { $case: "pointer"; pointer: BrowserPointer }
    | { $case: "key"; key: BrowserKey }
    | { $case: "command"; command: BrowserCommand }
    | { $case: "viewport"; viewport: BrowserViewportUpdate }
    | { $case: "frame_ack"; frame_ack: BrowserFrameAcknowledge }
    | { $case: "json"; json: BrowserJsonMessage }
    | undefined;
}

function createBaseBrowserAttach(): BrowserAttach {
  return { browser_id: "", participant_id: undefined };
}

export const BrowserAttach: MessageFns<BrowserAttach> = {
  fromJSON(object: any): BrowserAttach {
    return {
      browser_id: isSet(object.browser_id) ? globalThis.String(object.browser_id) : "",
      participant_id: isSet(object.participant_id) ? globalThis.String(object.participant_id) : undefined,
    };
  },

  toJSON(message: BrowserAttach): unknown {
    const obj: any = {};
    if (message.browser_id !== "") {
      obj.browser_id = message.browser_id;
    }
    if (message.participant_id !== undefined) {
      obj.participant_id = message.participant_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserAttach>, I>>(base?: I): BrowserAttach {
    return BrowserAttach.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserAttach>, I>>(object: I): BrowserAttach {
    const message = createBaseBrowserAttach();
    message.browser_id = object.browser_id ?? "";
    message.participant_id = object.participant_id ?? undefined;
    return message;
  },
};

function createBaseBrowserDetach(): BrowserDetach {
  return { browser_id: undefined };
}

export const BrowserDetach: MessageFns<BrowserDetach> = {
  fromJSON(object: any): BrowserDetach {
    return { browser_id: isSet(object.browser_id) ? globalThis.String(object.browser_id) : undefined };
  },

  toJSON(message: BrowserDetach): unknown {
    const obj: any = {};
    if (message.browser_id !== undefined) {
      obj.browser_id = message.browser_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserDetach>, I>>(base?: I): BrowserDetach {
    return BrowserDetach.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserDetach>, I>>(object: I): BrowserDetach {
    const message = createBaseBrowserDetach();
    message.browser_id = object.browser_id ?? undefined;
    return message;
  },
};

function createBaseBrowserPointer(): BrowserPointer {
  return { action: "", x: 0, y: 0, button: "", delta_x: 0, delta_y: 0 };
}

export const BrowserPointer: MessageFns<BrowserPointer> = {
  fromJSON(object: any): BrowserPointer {
    return {
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      button: isSet(object.button) ? globalThis.String(object.button) : "",
      delta_x: isSet(object.delta_x) ? globalThis.Number(object.delta_x) : 0,
      delta_y: isSet(object.delta_y) ? globalThis.Number(object.delta_y) : 0,
    };
  },

  toJSON(message: BrowserPointer): unknown {
    const obj: any = {};
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.button !== "") {
      obj.button = message.button;
    }
    if (message.delta_x !== 0) {
      obj.delta_x = message.delta_x;
    }
    if (message.delta_y !== 0) {
      obj.delta_y = message.delta_y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserPointer>, I>>(base?: I): BrowserPointer {
    return BrowserPointer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserPointer>, I>>(object: I): BrowserPointer {
    const message = createBaseBrowserPointer();
    message.action = object.action ?? "";
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.button = object.button ?? "";
    message.delta_x = object.delta_x ?? 0;
    message.delta_y = object.delta_y ?? 0;
    return message;
  },
};

function createBaseBrowserKey(): BrowserKey {
  return { action: "", key: "", code: "", text: undefined, repeat: false };
}

export const BrowserKey: MessageFns<BrowserKey> = {
  fromJSON(object: any): BrowserKey {
    return {
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : undefined,
      repeat: isSet(object.repeat) ? globalThis.Boolean(object.repeat) : false,
    };
  },

  toJSON(message: BrowserKey): unknown {
    const obj: any = {};
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.text !== undefined) {
      obj.text = message.text;
    }
    if (message.repeat !== false) {
      obj.repeat = message.repeat;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserKey>, I>>(base?: I): BrowserKey {
    return BrowserKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserKey>, I>>(object: I): BrowserKey {
    const message = createBaseBrowserKey();
    message.action = object.action ?? "";
    message.key = object.key ?? "";
    message.code = object.code ?? "";
    message.text = object.text ?? undefined;
    message.repeat = object.repeat ?? false;
    return message;
  },
};

function createBaseBrowserCommand(): BrowserCommand {
  return { name: "", value: "" };
}

export const BrowserCommand: MessageFns<BrowserCommand> = {
  fromJSON(object: any): BrowserCommand {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: BrowserCommand): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserCommand>, I>>(base?: I): BrowserCommand {
    return BrowserCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserCommand>, I>>(object: I): BrowserCommand {
    const message = createBaseBrowserCommand();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseBrowserViewportUpdate(): BrowserViewportUpdate {
  return { width: 0, height: 0 };
}

export const BrowserViewportUpdate: MessageFns<BrowserViewportUpdate> = {
  fromJSON(object: any): BrowserViewportUpdate {
    return {
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    };
  },

  toJSON(message: BrowserViewportUpdate): unknown {
    const obj: any = {};
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserViewportUpdate>, I>>(base?: I): BrowserViewportUpdate {
    return BrowserViewportUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserViewportUpdate>, I>>(object: I): BrowserViewportUpdate {
    const message = createBaseBrowserViewportUpdate();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseBrowserFrameAcknowledge(): BrowserFrameAcknowledge {
  return { frame_id: 0, received_bytes: 0 };
}

export const BrowserFrameAcknowledge: MessageFns<BrowserFrameAcknowledge> = {
  fromJSON(object: any): BrowserFrameAcknowledge {
    return {
      frame_id: isSet(object.frame_id) ? globalThis.Number(object.frame_id) : 0,
      received_bytes: isSet(object.received_bytes) ? globalThis.Number(object.received_bytes) : 0,
    };
  },

  toJSON(message: BrowserFrameAcknowledge): unknown {
    const obj: any = {};
    if (message.frame_id !== 0) {
      obj.frame_id = Math.round(message.frame_id);
    }
    if (message.received_bytes !== 0) {
      obj.received_bytes = Math.round(message.received_bytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserFrameAcknowledge>, I>>(base?: I): BrowserFrameAcknowledge {
    return BrowserFrameAcknowledge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserFrameAcknowledge>, I>>(object: I): BrowserFrameAcknowledge {
    const message = createBaseBrowserFrameAcknowledge();
    message.frame_id = object.frame_id ?? 0;
    message.received_bytes = object.received_bytes ?? 0;
    return message;
  },
};

function createBaseBrowserClientMessage(): BrowserClientMessage {
  return { payload: undefined };
}

export const BrowserClientMessage: MessageFns<BrowserClientMessage> = {
  fromJSON(object: any): BrowserClientMessage {
    return {
      payload: isSet(object.attach)
        ? { $case: "attach", attach: BrowserAttach.fromJSON(object.attach) }
        : isSet(object.detach)
        ? { $case: "detach", detach: BrowserDetach.fromJSON(object.detach) }
        : isSet(object.pointer)
        ? { $case: "pointer", pointer: BrowserPointer.fromJSON(object.pointer) }
        : isSet(object.key)
        ? { $case: "key", key: BrowserKey.fromJSON(object.key) }
        : isSet(object.command)
        ? { $case: "command", command: BrowserCommand.fromJSON(object.command) }
        : isSet(object.viewport)
        ? { $case: "viewport", viewport: BrowserViewportUpdate.fromJSON(object.viewport) }
        : isSet(object.frame_ack)
        ? { $case: "frame_ack", frame_ack: BrowserFrameAcknowledge.fromJSON(object.frame_ack) }
        : isSet(object.json)
        ? { $case: "json", json: BrowserJsonMessage.fromJSON(object.json) }
        : undefined,
    };
  },

  toJSON(message: BrowserClientMessage): unknown {
    const obj: any = {};
    if (message.payload?.$case === "attach") {
      obj.attach = BrowserAttach.toJSON(message.payload.attach);
    } else if (message.payload?.$case === "detach") {
      obj.detach = BrowserDetach.toJSON(message.payload.detach);
    } else if (message.payload?.$case === "pointer") {
      obj.pointer = BrowserPointer.toJSON(message.payload.pointer);
    } else if (message.payload?.$case === "key") {
      obj.key = BrowserKey.toJSON(message.payload.key);
    } else if (message.payload?.$case === "command") {
      obj.command = BrowserCommand.toJSON(message.payload.command);
    } else if (message.payload?.$case === "viewport") {
      obj.viewport = BrowserViewportUpdate.toJSON(message.payload.viewport);
    } else if (message.payload?.$case === "frame_ack") {
      obj.frame_ack = BrowserFrameAcknowledge.toJSON(message.payload.frame_ack);
    } else if (message.payload?.$case === "json") {
      obj.json = BrowserJsonMessage.toJSON(message.payload.json);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrowserClientMessage>, I>>(base?: I): BrowserClientMessage {
    return BrowserClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrowserClientMessage>, I>>(object: I): BrowserClientMessage {
    const message = createBaseBrowserClientMessage();
    switch (object.payload?.$case) {
      case "attach": {
        if (object.payload?.attach !== undefined && object.payload?.attach !== null) {
          message.payload = { $case: "attach", attach: BrowserAttach.fromPartial(object.payload.attach) };
        }
        break;
      }
      case "detach": {
        if (object.payload?.detach !== undefined && object.payload?.detach !== null) {
          message.payload = { $case: "detach", detach: BrowserDetach.fromPartial(object.payload.detach) };
        }
        break;
      }
      case "pointer": {
        if (object.payload?.pointer !== undefined && object.payload?.pointer !== null) {
          message.payload = { $case: "pointer", pointer: BrowserPointer.fromPartial(object.payload.pointer) };
        }
        break;
      }
      case "key": {
        if (object.payload?.key !== undefined && object.payload?.key !== null) {
          message.payload = { $case: "key", key: BrowserKey.fromPartial(object.payload.key) };
        }
        break;
      }
      case "command": {
        if (object.payload?.command !== undefined && object.payload?.command !== null) {
          message.payload = { $case: "command", command: BrowserCommand.fromPartial(object.payload.command) };
        }
        break;
      }
      case "viewport": {
        if (object.payload?.viewport !== undefined && object.payload?.viewport !== null) {
          message.payload = { $case: "viewport", viewport: BrowserViewportUpdate.fromPartial(object.payload.viewport) };
        }
        break;
      }
      case "frame_ack": {
        if (object.payload?.frame_ack !== undefined && object.payload?.frame_ack !== null) {
          message.payload = {
            $case: "frame_ack",
            frame_ack: BrowserFrameAcknowledge.fromPartial(object.payload.frame_ack),
          };
        }
        break;
      }
      case "json": {
        if (object.payload?.json !== undefined && object.payload?.json !== null) {
          message.payload = { $case: "json", json: BrowserJsonMessage.fromPartial(object.payload.json) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
