import { DEFAULT_BACKEND_PORT } from "../../api";
import type { AppState } from "../../types/frontend";
import {
  readCachedUiSettings,
  readUnreadSessionKeys,
} from "../../state/storage";

// 首次渲染的种子状态在模块加载时求值一次：缓存的 UI 设置与未读会话键既是初始值，
// 也是后续后端权威数据回填前的占位。这里不做任何请求，只读本地缓存。
export const INITIAL_APP_STATE: AppState = {
  apiPort: DEFAULT_BACKEND_PORT,
  gatewayWorkspaces: [],
  activeGatewayWorkspaceId: null,
  sessionsByWorkspace: new Map(),
  sessionGatewayWorkspaceById: new Map(),
  removingGatewayWorkspaceIds: new Set(),
  sessionHistoryReloadNonce: 0,
  workspaceSwitching: false,
  gatewayError: null,
  gatewayWorkspacesStale: false,
  gatewayUserAccess: null,
  gatewayUserViewStates: new Map(),
  uiSettings: readCachedUiSettings(),
  uiSettingsLoaded: false,
  themeBackgroundWarning: null,
  workspaceRoot: null,
  workspaceName: null,
  agents: [],
  sessions: [],
  sessionAttachmentSummaries: new Map(),
  currentSession: null,
  currentSessionWorkspaceId: null,
  turnTimelinesBySession: new Map(),
  traceEvents: [],
  messageStreamsByTurnStream: new Map(),
  llmRequestLogs: [],
  llmRequestLogsLoadedAt: null,
  llmRequestLogsLoading: false,
  llmRequestLogsError: null,
  sessionChangesets: [],
  selectedChangesetId: null,
  activeChangeset: null,
  sessionChangesLoadedAt: null,
  sessionChangesLoading: false,
  sessionChangesError: null,
  sessionResources: [],
  sessionResourcesLoadedAt: null,
  sessionResourcesLoading: false,
  sessionResourcesError: null,
  eventQueuesBySession: new Map(),
  sessionTraceHistoryBySession: new Map(),
  pendingConversations: new Map(),
  activeJobIdsBySession: new Map(),
  unreadSessionKeys: readUnreadSessionKeys(),
  status: "准备就绪",
  error: null,
  isBootstrapping: true,
  expandDetails: false,
  agentSessionsPanelOpen: true,
  contentView: "default",
  agentStateJsonl: "",
  agentStateMessageCount: 0,
  agentStateLoadedAt: null,
  agentStateLoading: false,
  agentStateError: null,
  compactLoading: false,
  lastCompactResult: null,
  currentGoal: null,
  currentGoalSessionId: null,
  goalLoading: false,
  goalError: null,
};
